### ISSUE TITLE
No static method loadLibrary

### ISSUE THREAD

**Issue by zhoufuqiang15** [facebook/yoga#1000]
java.lang.NoSuchMethodError: No static method loadLibrary(Ljava/lang/String;)V in class Lcom/facebook/soloader/SoLoader; or its super classes (declaration of 'com.facebook.soloader.SoLoader' appears in base.apk)
        at com.facebook.yoga.YogaNode.<clinit>(YogaNode.java:24)
        .....
com.facebook.soloader:soloader:0.5.0+

**Comment by NickGerleman** [comment]
It looks like there have been fixes in this area. https://github.com/facebook/yoga/issues/1152

Please reopen this issue if you still experience the crash on a more recent version of Yoga.
