### ISSUE TITLE
textAlign: "start" not supporting ! I hope that you implement it

### ISSUE THREAD

**Issue by EhsanSarshar** [facebook/yoga#1001]

**Comment by woehrl01** [comment]
Hi @EhsanSarshar ,

thank you for your suggestion. Unfortunately this feature is not possible to implement in Yoga. Yoga does not know about text, instead it only knows about "measurable" elements (which mostly are used for text nodes). The actual layouting of the text nodes happen in the libraries/frameworks which are consumer of Yoga. As `text-align` applies to the layout of the text node itself, this is out of scope.

**Comment by EhsanSarshar** [comment]
Thanks dear @woehrl01
I think I should open an issue in react native github

**Comment by woehrl01** [comment]
@EhsanSarshar Jep, this should be better addresses there. If you want you can even create a pull request there, it should be relative easy to implement. You probably simply need to adjust the following files. (And return left/right based on the text direction).

Android: [ReactBaseTextShadowNode.java](https://github.com/facebook/react-native/blob/ce0edca620d49597aa73c71a68b70efa170bc828/ReactAndroid/src/main/java/com/facebook/react/views/text/ReactBaseTextShadowNode.java#L440)
iOS: [RCTConvert.m](https://github.com/facebook/react-native/blob/bf5f3c6a79fba839225576da889d3b7f835a19f6/React/Base/RCTConvert.m#L315) + [RCTUITextView.m](https://github.com/facebook/react-native/blob/9cdc19a93669b37c0518bd32263e156ffc9193c7/Libraries/Text/TextInput/Multiline/RCTUITextView.m#L135)

**Comment by woehrl01** [comment]
@EhsanSarshar, actually according to [TextAttributeProps.java](https://github.com/facebook/react-native/blob/a136b34c35eec345e232ed4086411e8cf05ad35d/ReactAndroid/src/main/java/com/facebook/react/views/text/TextAttributeProps.java#L139), it is already implemented. If you specify "`left`" it gets automatically "`right`" if you change the direction.
