### ISSUE TITLE
Wrong property .getWidth instead of .getHeight used?

### ISSUE THREAD

**Issue by Robert-M-Muench** [facebook/yoga#1002]
I think the .getWidth is wrong on this case:

https://github.com/facebook/yoga/blob/83b27417ae6a1d577b1fddfa3c9433c2dc42a460/yoga/Yoga.cpp#L1815-L1816

**Comment by woehrl01** [comment]
Hi @Robert-M-Muench,

`ownerWidth` should be correct, as it is used for the percentage calculation. Why do you think this is wrong in that case? Maybe I have an oversight here.

**Comment by Robert-M-Muench** [comment]
in the block above (1795 - 1805), where the width is handled, ownerWidth is used two times and everything else is width related. So, why is owernWidth used as last parameter if we deal with heights?

**Comment by woehrl01** [comment]
I see. The reason why the `ownerWidth` is passed, is as the width is required to correctly calculate paddings which are provided as percentage values. You can find more to that in the specs for padding calculation: _Percentages: refer to logical width of containing block_ https://www.w3.org/TR/css-box-3/#margin-physical_ or the following blog post: https://css-tricks.com/oh-hey-padding-percentage-is-based-on-the-parent-elements-width/ 

Hope this makes things clearer.
