### ISSUE TITLE
Swift5.1 Error -- Crash

### ISSUE THREAD

**Issue by Aynnor** [facebook/yoga#1018]
# I want to bring yogakit to my project
# But it will lead to crash, I don't know why

Tool | Version
---|---
Xcode | 11.5
CocoaPods | 1.9.2
Podfile | platform: ios 9.0
YogaKit | 13.0.1

```swift
//Xcode Swift5.1 Project ViewController add this code, but Layout cannot be displayed, Even crash 

func createUI() {
        
        let fontNames = UIFont.fontNames(forFamilyName: "PingFang HK")
        print(fontNames)
        
        for i in 0..<fontNames.count {
            let label = UILabel()
            label.text = "the \(i) label.."
            label.font = UIFont.init(name: fontNames[i], size: 20)
            view.addSubview(label)
            
            label.configureLayout { (layout) in
                layout.isEnabled = true
            }
        }
        
        view.configureLayout { (layout) in
            layout.isEnabled = true
            layout.flexDirection = .column
            layout.justifyContent = .flexStart
            layout.alignItems = .flexStart
            layout.paddingLeft = 15
        }
        
        view.yoga.applyLayout(preservingOrigin: false)
}
```

## Message

![Xcode Crash Image](https://raw.githubusercontent.com/Aynnor/YogaKitDemo/master/xcodeImage.png)

**Comment by Aynnor** [comment]
feeling problem is on the `SceneDelegate`

**Comment by cntrump** [comment]
Because width or height is nagative, fixed in my PR: https://github.com/facebook/yoga/pull/1026

**Comment by NickGerleman** [comment]
We are deprecating YogaKit as part of the Yoga 2.0 release. We are still going to release a new revision based on the current state of the repo, but won't be accepting new contributions, since we are going to be removing it from the repo after.
