### ISSUE TITLE
Where are security vulnerabilities reported?

### ISSUE THREAD

**Issue by mrdewitt** [facebook/yoga#1020]
# Report

- [ :heavy_check_mark: ] I have searched [existing issues](https://github.com/facebook/yoga/issues) and this is not a duplicate

I am thinking of integrating with Yoga, and am wondering where security vulnerabilities are disclosed. Do you use github's security features? Are they posted with a CVE, and if so do you have a CPE prefix that I can use? 

I see that the security policy page links to facebook.com/whitehat but that does not include information about disclosures.

**Comment by mrdewitt** [comment]
Any updates available here?

**Comment by ngyikp** [comment]
Facebook does disclose valid vulnerabilities in their open source projects by issuing CVEs, example past projects include HHVM, Proxygen and Hermes.

**Comment by mrdewitt** [comment]
I am hoping for a response from an owner of this project, I'd prefer to have positive confirmation than to make an assumption.

**Comment by NickGerleman** [comment]
We would disclose any vulnerabilities. Yoga has so far not had any.
