### ISSUE TITLE
YogaKit failing testFrameAndOriginPlacement 

### ISSUE THREAD

**Issue by 100mango** [facebook/yoga#1021]
# Report

- [x] I have searched [existing issues](https://github.com/facebook/yoga/issues) and this is not a duplicate

# Issues and Steps to Reproduce

Run Yogokit test in Xcode

# Expected Behavior
Pass Test

# Actual Behavior

![image](https://user-images.githubusercontent.com/5073511/87649945-84bf6380-c783-11ea-9170-5f556e012699.png)

**Comment by cntrump** [comment]
Fixed and tested with retina 2x and 3x , please try my PR https://github.com/facebook/yoga/pull/1026

**Comment by NickGerleman** [comment]
We are deprecating YogaKit as part of the Yoga 2.0 release. We are still going to release a new revision based on the current state of the repo, but won't be accepting new contributions, since we are going to be removing it from the repo after.
