### ISSUE TITLE
YGNodeStyleGetMargin() returns nan. How to correctly initialize an YGNode

### ISSUE THREAD

**Issue by roxlu** [facebook/yoga#1031]
I've recently updated a pretty old version of Yoga (couple of years old 😂) and I noticed that `YGNodeStyleGetMargin()` returns a `nan` when I didn't explicitly set it. In the version I was using this wasn't the case and I'm wondering how to correctly initialize a `YGNode` so that it's style members have default values; e.g. 0 would be good I think.  Or is the currently recommended way to just check if the values are nan and deal with that? I'm happy with both approaches but I want to make sure I'm using the recommeded approach.

**Comment by natinusala** [comment]
`nan` is the internal value of "undefined" values. You can use `YGFloatIsUndefined` to know if the value is undefined instead of `std::is_nan` in case they change that in the future.
