### ISSUE TITLE
Why is `width` and/or `height` set to 0 when a node (or node parent) is hidden?

### ISSUE THREAD

**Issue by roxlu** [facebook/yoga#1038]
I'm using the C-api and when a parent is hidden the width of the node becomes 0. I think the width/height should stay the same regardless of the visibility. Let's say I jump behind a door and you can't see me anymore ... that doesn't mean I have no width anymore 😀

**Comment by natinusala** [comment]
The display setting is here for a layout purpose, if you don't want to draw the node just stop calling your render function on that node :P Yoga doesn't know and doesn't care about what you do with the nodes once they are laid out.

For my thing I introduced another visibility setting (!= display) that has three states, visible, invisible and gone. Invisible just prevents it from being rendered while gone sets the display property to "none" in the node.

Hope that helps!
