### ISSUE TITLE
How to add views programatically

### ISSUE THREAD

**Issue by hkawii** [facebook/yoga#1039]
# Report

- [x] I have searched [existing issues](https://github.com/facebook/yoga/issues) and this is not a duplicate

# Issues and Steps to Reproduce
```
       YogaNode rootNode = binding.yoga.getYogaNode();
        rootNode.setJustifyContent(YogaJustify.SPACE_AROUND);
        rootNode.setAlignItems(YogaAlign.AUTO);
        rootNode.setAlignContent(YogaAlign.CENTER);

        YogaNode imageNode = new YogaNodeJNIFinalizer();
        imageNode.setAlignSelf(YogaAlign.CENTER);

        ImageView image = new ImageView(getContext());
        image.setImageResource(R.drawable.geometric_outlined_call);

        binding.yoga.addView(image, imageNode);
```

# Expected Behavior
To see an image view in the layout

# Actual Behavior
No views displayed

Any help please?

**Comment by NickGerleman** [comment]
We're deprecating the `com.facebook.yoga.android.YogaLayout` ViewGroup in the next major release of Yoga. We intend to still push out a new version aligned to the core Yoga 2.0. I have bulk closed ViewGroup issues to reflect that we are not planning to invest time into functional changes of the ViewGroup. and eventually intend to remove it from the repo.
