### ISSUE TITLE
React-pdf crashes with a single text beyond 10K

### ISSUE THREAD

**Issue by sdzhangtao** [facebook/yoga#1044]
Hi,
I am using react-pdf to generate pdf on the fly, react-pdf is using yoga layout. There seems to be an issue when a text block exceeds 10k and caused pages to wrap.

When the input text size is beyong 10k, even I boosted up yoga-layout from 128M to 0.5G memory, it still crashes. I profiled the application with both CPU and memory, as shown in pictures below.

I created a simple github project to demonstrate, when you create download, the pdf with a text block longer than 10K will be generated and eventually crash out of memory.

Link to github project.

[Crashing pdf](https://github.com/sdzhangtao/crashing-react-pdf)

![crashing-pdf-cpu-profiling](https://user-images.githubusercontent.com/19583623/98885807-b2ca6100-2460-11eb-87cd-e9c0c062c599.jpg)
![crashing-pdf-memory-profiling](https://user-images.githubusercontent.com/19583623/98885810-b52cbb00-2460-11eb-9460-f6d7e9f69f64.jpg)

**Comment by NickGerleman** [comment]
As of 1813748eaa60e6129c1e1c00c08322b5687b1702 we compile with `ALLOW_MEMORY_GROWTH=1`
