### ISSUE TITLE
`nbind` browser output causes runtime errors when bundled as strict mode

### ISSUE THREAD

**Issue by zachzwy** [facebook/yoga#1048]
I was directed from [yoga-layout-prebuilt](https://github.com/vadimdemedes/yoga-layout-prebuilt).

Anyone here can help resolve this issue? https://github.com/vadimdemedes/yoga-layout-prebuilt/issues/2

Declare the variable in nbind.js: /yoga-layout-prebuilt/yoga-layout/build/Release/nbind.js
On line 1146 find this:
_a = _typeModule(_typeModule),
and change to this:
var _a = _typeModule(_typeModule);

Thanks.

**Comment by izmaelmag** [comment]
Are there any updates? I faced same error

**Comment by Saszr** [comment]
Also from [yoga-layout-prebuilt](https://github.com/vadimdemedes/yoga-layout-prebuilt).

This error related is still not updated.
I used it in rollup / vite, some workaround to get rid of the error:

rollup: https://github.com/facebook/yoga/issues/798#issuecomment-555858987

vite: reference from https://github.com/plouc/nivo/issues/1455#issuecomment-815904731 , the relevant code is replaced with`<script> var _a; </script>`

**Comment by matart15** [comment]
same error

**Comment by NickGerleman** [comment]
This issue should be on the `yoga-layout-prebuilt` repo if folks are experiencing an issue with it. We are not the contributors of the package.

**Comment by wong2** [comment]
from `yoga-layout-prebuilt` maintainer:

> Yeah, this issue should be reported on yoga-layout repo, as this module just contains the build of it.

**Comment by nikolay** [comment]
@NickGerleman The issue is, indeed, here and it's breaking a lot of other things.

**Comment by gfox1984** [comment]
As a workaround, you can fix the issue with [patch-package](https://github.com/ds300/patch-package).

The patch should be called `yoga-layout-prebuilt+1.10.0.patch` and contain:

```
diff --git a/node_modules/yoga-layout-prebuilt/yoga-layout/build/Release/nbind.js b/node_modules/yoga-layout-prebuilt/yoga-layout/build/Release/nbind.js
index 0853309..5354776 100644
--- a/node_modules/yoga-layout-prebuilt/yoga-layout/build/Release/nbind.js
+++ b/node_modules/yoga-layout-prebuilt/yoga-layout/build/Release/nbind.js
@@ -1143,7 +1143,7 @@
       }
     }_nbind.addMethod = addMethod;function throwError(message) {
       throw new Error(message);
-    }_nbind.throwError = throwError;_nbind.bigEndian = false;_a = _typeModule(_typeModule), _nbind.Type = _a.Type, _nbind.makeType = _a.makeType, _nbind.getComplexType = _a.getComplexType, _nbind.structureList = _a.structureList;var BindType = function (_super) {
+    }_nbind.throwError = throwError;_nbind.bigEndian = false;var _a; _a = _typeModule(_typeModule), _nbind.Type = _a.Type, _nbind.makeType = _a.makeType, _nbind.getComplexType = _a.getComplexType, _nbind.structureList = _a.structureList;var BindType = function (_super) {
       __extends(BindType, _super);function BindType() {
         var _this = _super !== null && _super.apply(this, arguments) || this;_this.heap = HEAPU32;_this.ptrSize = 4;return _this;
       }BindType.prototype.needsWireRead = function (policyTbl) {

```
See the readme in [patch-package](https://github.com/ds300/patch-package) if you're not sure how to use it.

**Comment by nikolay** [comment]
Thanks, @gfox1984! It works pretty well! 🙇🏻

**Comment by NickGerleman** [comment]
> @NickGerleman The issue is, indeed, here and it's breaking a lot of other things.

I took a look at the issue reported in `yoga-layout-prebuilt`. https://github.com/vadimdemedes/yoga-layout-prebuilt/issues/2#issuecomment-846339643 gives a good summary of the issue, where it looks like the underlying issue happens when bundling the output of `nbind` with some bundlers.

`nbind` is pretty dead and no longer builds on supported versions of Node (#979). We need to move the bindings off of it if we want to resolve any sort of issues from its output. There are rebindings of Yoga like [`yoga-wasm-web`](https://github.com/shuding/yoga-wasm-web) that are probably a better interim solution than using the `nbind` produced outputs, if those cause issues.

From the comment, I suspect changing the configuration of your bundler may allow `nbind` to be used. This issue does not happen in the website build, where Gatsby is using Webpack (albeit a very old version).

**Comment by NickGerleman** [comment]
1813748eaa60e6129c1e1c00c08322b5687b1702 removes usage of nbind. It is not published yet, but feedback would be appreciated in the meantime if anyone wants to test it.

**Comment by NickGerleman** [comment]
Going to use https://github.com/facebook/yoga/issues/941 to track publishing the new version to npm.

**Comment by hi019** [comment]
For those still facing this issue, check out https://github.com/shuding/yoga-wasm-web which uses a WASM build of Yoga
