### ISSUE TITLE
Yoga-prefix.pch issue

### ISSUE THREAD

**Issue by nnhan0719** [facebook/yoga#1071]
Showing All Errors Only
/<built-in>:1:10: Non-portable path to file '"/Users/Me/Project/ios/Pods/Target Support Files/Yoga/Yoga-prefix.pch"'; specified path differs in case from file name on disk

**Comment by dalabarge** [comment]
Is your path `/Userss/...` or `/Users/...`? I just got this error for first time too and trying to figure out where it's even generated or how that path got entered. I have the double `ss` on the path...

**Comment by NickGerleman** [comment]
How are you building the project? Is this through React Native, or through the Yoga OSS repo?

Please file a new issue following the template if you are still running into the problem.
