### ISSUE TITLE
Release old artefacts on maven central

### ISSUE THREAD

**Issue by pvegh** [facebook/yoga#1093]
Projects using not the newest versions cannot migrate from jcenter, one reason is 
com.facebook.yoga:proguard-annotations
not being available in those versions on maven central, only on jCenter

Fix:
Upload the last few releases to maven central

**Comment by mikehardy** [comment]
Duplicate #1065

**Comment by NickGerleman** [comment]
Thanks for filing this! Closing this issue in favor of the one mentioned by @mikehardy.
