### ISSUE TITLE
[Documentation] [Request] Add ink in the "Open Source Adoption" section of the landing page

### ISSUE THREAD

**Issue by AeonFr** [facebook/yoga#1099]
[Ink](https://github.com/vadimdemedes/ink) is a very interesting project using Yoga.

It adds a new "platform" -- the CLI -- to the list of places where Yoga can be used to create layouts.

It would be nice to list it in the Yoga homepage, besides React Native, React PDF, etc.

Note I'm not associated or involved in the development of Ink and I don't get any benefit from this, I just think it's an innovative project that deserves recognition.

**Comment by NickGerleman** [comment]
Highlighting more community usages of Yoga is a good idea. FlexLayout is another one we should definitely be leading folks to.

**Comment by NickGerleman** [comment]
The current documentation at https://www.yogalayout.dev/ no longer has a section on projects using Yoga. But I will keep this in mind if we end up wanting to build a showcase.
