### ISSUE TITLE
add a CAShapeLayer on a View

### ISSUE THREAD

**Issue by dclcs** [facebook/yoga#1100]
# Report

- [x] I have searched [existing issues](https://github.com/facebook/yoga/issues) and this is not a duplicate

# Issues and Steps to Reproduce
I add a CAShapeLayer on a UIView using method addSublayer, I found the Line I want to draw floated? Why?

**Comment by NickGerleman** [comment]
We are deprecating YogaKit as part of the Yoga 2.0 release. We are still going to release a new revision based on the current state of the repo, but won't be accepting new contributions, since we are going to be removing it from the repo after.
