### ISSUE TITLE
FlexWrap affect the layout of a single line

### ISSUE THREAD

**Issue by guoweilkd** [facebook/yoga#1113]
# Report

- [x] I have searched [existing issues](https://github.com/facebook/yoga/issues) and this is not a duplicate

# Issues and Steps to Reproduce

When I used yoga's C++ code directly, I found that when the layout is only one line, open `FLEX WRAP` will affect the setting of `ALIGN ITEMS`. In the following code, node will be aligned from center to left aligned.

```c
YGNodeStyleSetFlexDirection(node, YGFlexDirectionColumn);
YGNodeStyleSetAlignItems(node, YGAlignCenter);
YGNodeStyleSetFlexWrap(node, YGWrapWrap);
```
I checked [source code](https://github.com/facebook/yoga/blob/main/yoga/Yoga.cpp#L3219) and found that yoga does not seem to make a judgment on the single line. Is this a bug, or is it my use error?

# Expected Behavior

When all child nodes do not satisfy multiple rows on the cross axis, the`YGNodeStyleSetFlexWrap(node, YGWrapWrap)` and `YGNodeStyleSetAlignContent()` of the parent node should have no effect on the layout.

**Comment by NickGerleman** [comment]
There are situations where flex-wrap can influence the layout of a container that has only one line of content, namely, if `align-content` is something other than stretch.

I know this is a long time after the original question, but if you had a repro, that would be helpful.
