### ISSUE TITLE
Some tests fail with new chromedriver 96.0.4664.45

### ISSUE THREAD

**Issue by intergalacticspacehighway** [facebook/yoga#1115]
# Report

- [x] I have searched [existing issues](https://github.com/facebook/yoga/issues) and this is not a duplicate

# Issues and Steps to Reproduce
- Install the latest chromedriver
- Replace `chromeOptions` key with `goog:chromeOptions` in gentest.rb in `Watir::Browser.new` call (this option was changed in new chromedriver)
- run `ruby gentest.rb` and `buck test //:yoga`
- Three of the testcases will fail.

```
FAIL    <100ms 521 Passed   0 Skipped   3 Failed   //:YogaTests
FAILURE YogaTest min_height: tests/YGMinMaxDimensionTest.cpp:118
      Expected: 60
To be equal to: YGNodeLayoutGetHeight(root_child0)
      Which is: 80

====STANDARD OUT====
tests/YGMinMaxDimensionTest.cpp:118: Failure
      Expected: 60
To be equal to: YGNodeLayoutGetHeight(root_child0)
      Which is: 80
FAILURE YogaTest min_width: tests/YGMinMaxDimensionTest.cpp:172
      Expected: 60
To be equal to: YGNodeLayoutGetWidth(root_child0)
      Which is: 80

====STANDARD OUT====
tests/YGMinMaxDimensionTest.cpp:172: Failure
      Expected: 60
To be equal to: YGNodeLayoutGetWidth(root_child0)
      Which is: 80
FAILURE YogaTest percentage_flex_basis_cross_min_height: tests/YGPercentageTest.cpp:276
      Expected: 120
To be equal to: YGNodeLayoutGetHeight(root_child0)
      Which is: 140

====STANDARD OUT====
tests/YGPercentageTest.cpp:276: Failure
      Expected: 120
To be equal to: YGNodeLayoutGetHeight(root_child0)
      Which is: 140

```

I tried looking into one of them `YGMinMaxDimensionTest.cpp` `min_height`. Created a [codepen repro](https://codepen.io/nishanB/pen/WNZORLg) here. It renders different output in safari and chrome. I guess that the implementation in latest chrome could have changed. Assertions in yoga match the output of Safari instead of chrome.

# Expected Behavior
- Would be great if we can know which of the implementation is correct behaviour (safari or chrome's). I suspect using the latest chromedriver is causing this issue.

# Actual Behavior
- Three of the tests are failing

# Link to Code
[codepen repro](https://codepen.io/nishanB/pen/WNZORLg) link of the test. It renders differently on chrome and safari.

<img width="912" alt="Screenshot 2021-12-19 at 4 38 35 PM" src="https://user-images.githubusercontent.com/23293248/146677829-7fc78ed7-af02-4ec3-9c92-19f1332e661b.png">

**Comment by jacobp100** [comment]
Do you have a diff of the changed tests?

**Comment by intergalacticspacehighway** [comment]
Yes. You can find it [here](https://github.com/facebook/yoga/compare/main...intergalacticspacehighway:test-diff?expand=1). Got same changes for java, js and cs files.

**Comment by NickGerleman** [comment]
Fixed with https://github.com/facebook/yoga/commit/fd180de774824b9b639ddb7fb43d87e983a7c248

**Comment by NickGerleman** [comment]
I'm not sure what behavior is correct here, but came across the same difference, so they are no longer used as fixtures in the meantime. I have separately been looking at whether we can use any of the tests shared by browsermakers (like in https://github.com/web-platform-tests/wpt/tree/master/css).
