### ISSUE TITLE
[Documentation] how does Yoga render the final layout on screen?

### ISSUE THREAD

**Issue by gaurav5430** [facebook/yoga#1119]
From the readme or the available documentation I am not able to understand how yoga finally render the layout on screen in a cross platform way? 

I have not been able to understand this by going through the code as well.

does it delegate to the respective platform layout engines / primitives or it somehow talks to the OS in a more low level way and draws the elements on screen?

For example:
I understand there is a swift binding for yoga c++ code, which allows writing swift code which would call the c++ yoga code, the yoga code would then calculate the position of the element, but what is the next step after this? 

does the yoga code somehow talk to the OS to draw this on the screen?

or the yoga code delegates to the existing platform primitives like UIView to take care of the final rendering?

**Comment by gaurav5430** [comment]
on further reading, I think I understand that yoga does not have anything to do with how and when the elements get rendered on the screen. it just calculates the layout in a platform specific way, so that the layout parameters can be applied to that particular platform's primitives whenever they are rendered. Fro example, In case of android this would be ViewGroup amd in case of iOS it would be UIView. yoga would just calculate the layout values and expose them to these native layout primitives in a way that they understand. This is enabled by the yoga bindings for those platforms.

**Comment by nullhook** [comment]
I believe yoga core was designed to be renderer agnostic. yoga core only computes values based on enums and saves in-memory. The value primitives used are clamped to ensure overflows and in some cases you you'll see OS-level and compiler-level directives. 

The bindings is where you'll see renderer related mappings and I think this is generated via nbind. For JS, you'll see mappings from YG primitives such as certain YGValue -> px/pct, YGNode -> div and they're all inline.

**Comment by AndrewAPrice** [comment]
Late to reply, but yes, Yoga doesn't do any rendering. Yoga is a "layout engine" meaning it just calculated the positions of items.

You create yoga nodes, set CSS flex style attributes on these nodes, then yoga will calculate the position and size of these nodes.

You'd build a UI library (which has widgets like buttons, text fields, etc) by associating each widget with a yoga node Then when it comes to drawing the widget or telling if a mouse is over the widget, you use the yoga node's calculated position and size to know where it is.
