### ISSUE TITLE
Documentation about "align-content"  question

### ISSUE THREAD

**Issue by luhuaipei** [facebook/yoga#1136]
# Report 

I am learning "align-content" usage on web(https://yogalayout.com/docs/align-content).

The "space between" description is like this:

> _SPACE BETWEEN Evenly space wrapped lines across the container's main axis, distributing remaining space between the lines.
>SPACE AROUND Evenly space wrapped lines across the container's main axis, distributing remaining space around the lines. >Compared to space between using space around will result in space being distributed to the begining of the first lines and end of the >last line._

I don't understand the "across the container's main axis" part. It should be "cross axis"？

Please help to clarify.

Thanks.

**Comment by Andrey-Mishanin** [comment]
Hey @luhuaipei, your understanding is correct, it should read "cross axis"

**Comment by luhuaipei** [comment]
Thanks.
