### ISSUE TITLE
Recently added 'gap/row-gap/column-gap' properties not present in playground

### ISSUE THREAD

**Issue by inobelar** [facebook/yoga#1169]
# Report

- [x] I have searched [existing issues](https://github.com/facebook/yoga/issues) and this is not a duplicate

# Issues and Steps to Reproduce

According to this commit https://github.com/facebook/yoga/commit/582533dbc620dd6e63d1a4df1885afa086d6c8f4 (Added: `gap`/`row-gap`/`column-gap` properties), it will be useful to add them for tweaking into [playground](https://yogalayout.com/playground/).

# Expected Behavior
Recently added properties present in `Flex`, `Alignment`, or `Layout` tab.

# Actual Behavior
Recently added properties not present anywhere.

**Comment by NickGerleman** [comment]
This would be a good feature to add. Contributions are welcome, and future ones should go into less of a blackhole than before 🙂.

**Comment by brianguertin** [comment]
I think this requires first publishing a new version to NPM? Since the current version is missing gap functionality. https://github.com/facebook/yoga/issues/1169

**Comment by NickGerleman** [comment]
Not necessarily. Since its sources live in repo, the website build could link to the yoga-layout package via yarn workspaces.

I'm a bit hesitant on releasing a new npm package if it will still be stuck on Node 10, which has been EOL on security updates for the last year and a half. We can jank it to allow Node 12 support, but that's also still EOL.

**Comment by NickGerleman** [comment]
@jeetiss That would be a great contribution! It means we would be losing the `nbind` support for Node native modules, but given how long those have been unusable, I think moving to emscripten would be a great step forward (and we can always make a separate Node build if people really want it).

There are generated unit tests for JS that I don't believe are hooked up right now, but it would be a great way to verify things if there are non-mechanical changes needed.

**Comment by inobelar** [comment]
Offtop: until `Gap` properties still not present in 'yogalayout.com' playground, here is alternative:

If someone interested to test `Gap` properties in interactive 'Playground', I made similar **[Web App](https://inobelar.github.io/emscripten_samples/sample_Yoga_Playground.html)** (fresh C++ Yoga sources, compiled with Dear ImGui (for UI) into WASM, displayed with WebGL). ([sources](https://github.com/inobelar/imgui_yoga_inspect))

To tweak `Gap` properies do the next steps: In window "Yoga node properties" → Menu 'Display' →Click over 'Full' radio-button - to see full Yoga API (not website-like forms), and there you find that properties.

**Comment by inobelar** [comment]
Reminder: @NickGerleman as I can see, Yoga Team launched & internally reworked new website (yogalayout.dev) ... Maybe you take a look at missing 'Gap' properties in 'Sandbox' ? :)

**Comment by NickGerleman** [comment]
@inobelar  there’s a larger documentation revamp in the works. This includes a new playground, which does currently support gap.

https://yoga-website-next-fbopensource.vercel.app/yogalayout.dev/

**Comment by NickGerleman** [comment]
This is notably currently missing… the documentation. There’s work there too, but the Yoga playground evolved first because it also served as an opportunity to validate the JS bindings in a real world setting.

**Comment by NickGerleman** [comment]
I set it up so that edits to `/website-next` get deployed as previews for each PR, and tried to make it as painless as possible to run locally (there is no user setup needed for the toolchain apart from yarn install).

<img width="941" alt="image" src="https://github.com/facebook/yoga/assets/835219/d9712ef0-e7d2-4388-9b58-053f7db43b6a">

**Comment by NickGerleman** [comment]
New playground is published at https://www.yogalayout.dev/playground
