### ISSUE TITLE
definition of implicit copy constructor for 'Values<9>' is deprecated because it has a user-declared copy assignment operator 

### ISSUE THREAD

**Issue by summerHearts** [facebook/yoga#1174]
# Report

- [x] I have searched [existing issues](https://github.com/facebook/yoga/issues) and this is not a duplicate

# Issues and Steps to Reproduce
Xcode14.1 
<img width="1366" alt="image" src="https://user-images.githubusercontent.com/10678821/202424600-b1be4ebd-f827-4f6b-8fda-13060f6e0823.png">

In file included from Carthage/Checkouts/yoga/yoga/Utils.h:9:
In file included from Carthage/Checkouts/yoga/yoga/YGNode.h:13:
In file included from Carthage/Checkouts/yoga/yoga/YGConfig.h:9:
Carthage/Checkouts/yoga/yoga/Yoga-internal.h:135:11: error: definition of implicit copy constructor for 'Values<9>' is deprecated because it has a user-declared copy assignment operator [-Werror,-Wdeprecated-copy]
  Values& operator=(const Values& ot

# Expected Behavior
build success

# Actual Behavior
run  WildeGuess

**Comment by NickGerleman** [comment]
It seems like the explicit copy ctor isn't needed here since all it is doing is copying the underlying array anyway.

**Comment by nalounguyen** [comment]
is it fixed ?
I stil get error when build from tutorial: https://componentkit.org/docs/getting-started/
