### ISSUE TITLE
Would it work for a game?

### ISSUE THREAD

**Issue by VictorQueiroz** [facebook/yoga#1190]
I'm wondering if it'd be a good fit for a game's UI with C++ and OpenGL?

**Comment by NickGerleman** [comment]
Yoga has a public C interface, which is embeddable into different UI frameworks or drawing routines. E.g. React Native embeds Yoga for its layout implementation. So you could definitely embed Yoga into a library for game UI.

Be aware that there are some configuration flags you might want to globally set in a new project (like `UseWebDefaults` if you want your stylesheets to act like they do in a browser). The story for external package managers is also in need of some improvement, so you would want to consume Yoga as a Git submodule, GitHub archive, or just copying the source.

**Comment by KurtGokhan** [comment]
It is [already used in Unity](https://docs.unity3d.com/Manual/UIE-LayoutEngine.html). Also I am using it for another UI library for Unity called [ReactUnity](https://github.com/ReactUnity/core)

**Comment by NickGerleman** [comment]
Wow I honestly didn't know that! There has been someone recently expressing interest in getting the C# bindings up to snuff again as well (I wonder if they are using a fork of those).

**Comment by KurtGokhan** [comment]
Don't know about the recent requests, but afaik Unity have been using it since 2018. They may still be on version 1.8.

**Comment by handsomematt** [comment]
We're using it on [s&box](https://sbox.facepunch.com/)
