### ISSUE TITLE
Possibility to build with older compilers

### ISSUE THREAD

**Issue by HCCix** [facebook/yoga#1191]
This is a very usefull library and i would like to use it in my "older" projects too, but the Yoga is not buildable under ms compiler v140.
Is there any way to compile Yoga with ms v120 toolset (VS2013)? Or does somebody know about a changed to older compiler version of original yoga?

Thak you for your answers.

**Comment by NickGerleman** [comment]
There has been a history of Yoga hitting MSVC specific bugs before. There have been Yoga contributions from folks with MSVC expertise working on React Native for Windows, which targets latest or n-1 MSVC. I only remember as far back as VS 2017 being used though.

**Comment by NickGerleman** [comment]
Some foundational libraries like GTest are starting to require C++ 14, and from the perspective of authoring Yoga changes, I think we are going to want to follow.

VS 2013 had some C++ 11 support. VS 2015 has better C++ 14 support than VS 2013 had C++ 11 support, and I think will likely be able to compile Yoga. But we are not testing against it, and there are version-to-version compiler changes apart from the standard.

VS 2019 is the oldest version of VS still in [mainstream support](https://devblogs.microsoft.com/visualstudio/support-ends-for-older-versions-of-visual-studio-feb2022/) (2017 was booted earlier this year). Anything older really ideally shouldn't still be used in projects seeing active development, but I recognize it is not always simple.

**Comment by HCCix** [comment]
Thank you for all instruction. :)
