### ISSUE TITLE
Horizontal Edges Inverted on node set to YGFlexDirectionRowReverse

### ISSUE THREAD

**Issue by NickGerleman** [facebook/yoga#1208]
When a node has a direction of "YGFlexDirectionRowReverse", its own margin (and probably padding, etc) set to YGEdgeLeft or YGEdgeStart is resolved to the right side of the node under LTR.

The start and left edges on the reverse-ordered children are correct.

https://snack.expo.dev/VT0h3zE0O

```jsx
export default function App() {
  return (
    <SafeAreaView>
      <View style={styles.container}>
        <View style={[styles.child, {marginLeft: 50}]} >
          <View style={[styles.grandchild, {marginLeft: 50}]} />
        </View>
      </View>
      <View style={styles.container}>
        <View style={[styles.child, {marginRight: 50}]} >
          <View style={[styles.grandchild, {marginRight: 50}]} />
        </View>
      </View>
      <View style={styles.container}>
        <View style={[styles.child, {marginStart: 50}]} >
          <View style={[styles.grandchild, {marginStart: 50}]} />
        </View>
      </View>
      <View style={styles.container}>
        <View style={[styles.child, {marginEnd: 50}]} >
          <View style={[styles.grandchild, {marginEnd: 50}]} />
        </View>
      </View>
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  container: {
    position: 'relative',
    backgroundColor: "red",
    margin: 10,
    width: 200,
    height: 100,
    flexDirection: "row",
  },
  child: {
    flexDirection: "row-reverse",
    backgroundColor: "blue",
    flex: 1,
  },
  grandchild: {
    backgroundColor: "green",
    height: "50%",
    flex: 1,
  },
});
```

**Yoga**
<img width="163" alt="image" src="https://user-images.githubusercontent.com/835219/211182448-3ae9d36f-5026-4fc5-9d40-b54904dc4d79.png">

**Web**
<img width="218" alt="image" src="https://user-images.githubusercontent.com/835219/211182430-ca626d60-191c-4a46-91de-4ab423f88cbc.png">

**Comment by joevilches** [comment]
Closing this issue after all the changes made recently (attached above). Specifically the commit that fixed this was https://github.com/facebook/yoga/pull/1420, although there were other issues with borderStart/End, paddingStart/End, and left/right/top/bottom that were also fixed.
