### ISSUE TITLE
Static subscriber list considered harmful

### ISSUE THREAD

**Issue by jwezel** [facebook/yoga#1214]
# Question

I find the implementation of the event system with a static subscriber list problematic. I'm considering a scenario where there is more than one runtime context of Yoga layout present. A static subscriber list runs counter to this.

A solution would be a context parameter in Yoga calls. If such a parameter would be a pointer always appended to any parameters list it could be defaulted to a `nullptr` which would preserve the call sequence.

A better solution would obviously be to always include a context parameter at the head of any parameter list and to make the context mandatory and official, which would make it necessary to bump the first part of the version number.

My question is, would a pull request with default context parameter at the end of any parameter list be accepted?

- [x] I have searched [existing issues](https://github.com/facebook/yoga/issues) and this is not a duplicate

**Comment by NickGerleman** [comment]
From what I can tell, that is vaguely what `YGNodeCalculateLayoutWithContext` is meant to do, and what `layoutContext` on some of the events is for. But it is only ever currently used in the JNI bindings. My guess is folks were focused on using the events on Android and didn't hook it anywhere else.

What do you think about making it so that we call that API from `YGNodeCalculateLayout` with the root node ref as the context instead of nullptr, like the JNI bindings do?

**Comment by jwezel** [comment]
To me this parameter `layoutContext` looks more like an event context (information about the event). But all events are registered in the global variable `subscribers` in `event.cpp`.

I am developing a terminal window system and want to use Yoga to layout widgets into dialogs and the like. Each window is a separate context and would need a separate subscriber list. So I would need to have a "window context" (not node context nor event context) containing its own subscriber list and that would need to be passed as an additional parameter to the Yoga calls. I'm thinking of using Yoga to layout windows on the "desktop" ie terminal and also to layout graphic objects within a fancy widget. They all would share the one subscriber list at the moment.

While I don't think it's impossible to have several application contexts with Yoga layouts in a process sharing this one linked list, I see it as problematic when it comes to performance and organization.

**Comment by jwezel** [comment]
Oh, surprise. I wanted to notify the "real" objects of their reshaping.

**Comment by NickGerleman** [comment]
Here is the first commit introducing it for context. https://github.com/facebook/yoga/commit/e51ca9571394b874f622f3a75332bf722952d681

I think the intention might be clearer if it was named something like `tracing` instead of `events`.

**Comment by jwezel** [comment]
Last sentence is quite interesting.

**Comment by NickGerleman** [comment]
Seems like this can be closed, let me know if there is anything pending.
