### ISSUE TITLE
Request for the latest JS bundled version

### ISSUE THREAD

**Issue by xh1996819** [facebook/yoga#1241]
Hello,

I'm wondering if anyone would be able to provide the latest bundled version of the JS for Facebook/Yoga? I've been trying to find it, but I haven't had any luck yet.

Thank you in advance for your help!

**Comment by nicoburns** [comment]
I believe you want https://github.com/shuding/yoga-wasm-web

**Comment by NickGerleman** [comment]
Yes, the reference package inside of the Yoga repo hasn't been published in sometime, so there are forks like the above, which have updated to use more recent versions of Yoga as well. I still intend to publish an NPM package for what is in repo once we do a new Yoga release as well (being on vacation for the last three weeks has not helped that happen any sooner 😅).
