### ISSUE TITLE
what does flex: 1 actually do ? comparing to web

### ISSUE THREAD

**Issue by TheEhsanSarshar** [facebook/yoga#1246]
as it's mentioned here in [flex spec](https://www.w3.org/TR/css-flexbox-1/#flex-property).
`flex: <positive number>` will set `flexGrow: <positive number>, flexShrink: 0, flexBasis: 0%`
do we have the same behavior in Yoga or it's different?
sorry it seems like a StackOverflow question, but actually doesn't have a clear till now

**Comment by nicoburns** [comment]
Firstly, as per your link, `flex: N` is equivalent to `flex-grow: N, flex-shrink: 1; flex-basis: 0` not `flex-grow: N; flex-shrink: 0;flex-basis: 0`. And I also believe that the spec now specifies `0px` not `0%`.

The relevant code in Yoga is as follows (taken from [YGNode.cpp](https://github.com/facebook/yoga/blob/main/yoga/YGNode.cpp):

```cpp
static const float kDefaultFlexGrow = 0.0f;
static const float kWebDefaultFlexShrink = 1.0f
static const float kDefaultFlexShrink = 0.0f;

float YGNode::resolveFlexGrow() const {
  // Root nodes flexGrow should always be 0
  if (owner_ == nullptr) {
    return 0.0;
  }
  if (!style_.flexGrow().isUndefined()) {
    return style_.flexGrow().unwrap();
  }
  if (!style_.flex().isUndefined() && style_.flex().unwrap() > 0.0f) {
    return style_.flex().unwrap();
  }
  return kDefaultFlexGrow;
}

float YGNode::resolveFlexShrink() const {
  if (owner_ == nullptr) {
    return 0.0;
  }
  if (!style_.flexShrink().isUndefined()) {
    return style_.flexShrink().unwrap();
  }
  if (!facebook::yoga::detail::getBooleanData(flags, useWebDefaults_) &&
      !style_.flex().isUndefined() && style_.flex().unwrap() < 0.0f) {
    return -style_.flex().unwrap();
  }
  return facebook::yoga::detail::getBooleanData(flags, useWebDefaults_)
      ? kWebDefaultFlexShrink
      : kDefaultFlexShrink;
}

YGValue YGNode::resolveFlexBasisPtr() const {
  YGValue flexBasis = style_.flexBasis();
  if (flexBasis.unit != YGUnitAuto && flexBasis.unit != YGUnitUndefined) {
    return flexBasis;
  }
  if (!style_.flex().isUndefined() && style_.flex().unwrap() > 0.0f) {
    return facebook::yoga::detail::getBooleanData(flags, useWebDefaults_)
        ? YGValueAuto
        : YGValueZero;
  }
  return YGValueAuto;
}
```

Assuming the `flex` property is set, then as I read it:

- If the individual properties are set, then these always take priority (regardless of the order in which they are set
- If `flexGrow` is not set then the `flex` value is used for `flexGrow` value as on web
- `flexShrink` behaviour depends on the `useWebDefaults` feature flag
   - If `useWebDefaults=true`: then `flexShrink` gets set to `1.0` as on web
   - If `useWebDefaults=false`: then:
       - Negative values for flex will set `flexShrink` to the value of `flex` * -1
       - Non-negative values for flex lead flexShrink to get set to `0.0`
- `flexBasis` behaviour also depends on the `useWebDefaults` feature flag
   - If `useWebDefaults=true`: then `flexBasis` gets set to `auto`
   - If `useWebDefaults=false`: then `flexBasis` gets set to `0.0`
