### ISSUE TITLE
Xcode 14.3 Run Main Branch，error "cstdio file not found"

### ISSUE THREAD

**Issue by jiasongs** [facebook/yoga#1266]
The problem after removing `__cplusplus`, it will be fine after adding `__cplusplus`

The cause of the problem is this commit：https://github.com/facebook/yoga/commit/fc687653149cb887e2f63c70f16b01f65e5d75eb

**Comment by NickGerleman** [comment]
Could you provide more information, like the excerpt provided by your compiler, which should show the chain of headers/source included here.

Are you maybe importing `yoga/YGNode.h`, `yoga/YGConfig.h`, `yoga/YGStyle.h`, or similar in a C or Objective C source file? These headers are for the underlying C++ implementation, and should not be included in that environment. Just `yoga/Yoga.h` which defines the C API.

**Comment by jiasongs** [comment]
> 你能提供更多信息吗？ 就像您的编译器提供的摘录一样，它应该显示此处包含的标头/源代码链。
> 
> 你也许进口 `yoga/YGNode.h`, `yoga/YGConfig.h`, `yoga/YGStyle.h`，或 C 或 Objective C 源文件中的类似内容？ 这些标头用于底层 C++ 实现，不应包含在该环境中。 只是 `yoga/Yoga.h`（及其传递的#includes）定义了 C API。
Yes, I imported `#import <yoga/Yoga.h>` in `.m`, I need to use `YGNodeRef` to do something, what should i do next

**Comment by NickGerleman** [comment]
The build logic being used is resolving “#import "YGLayout.h"” from “YogaKit/Source” to ”yoga/YGLayout.h” instead of the one in the same directory. It looks like that is the issue here.

Re operating on a YGNodeRef, any of the C functions that look like “YGNodeXXXX” can accept a pointer to one, without having a concrete type available.

**Comment by jiasongs** [comment]
> 



> The build logic being used is resolving “#import "YGLayout.h"” from “YogaKit/Source” to ”yoga/YGLayout.h” instead of the one in the same directory. It looks like that is the issue here.
> 
> Re operating on a YGNodeRef, any of the C functions that look like “YGNodeXXXX” can accept a pointer to one, without having a concrete type available.

Okay, thank you very much for your answer
