### ISSUE TITLE
Use of bitwise '|' with boolean operands | XCode 14.3 fails builds using react-native Yoga - RN versions before 0.69 are no longer being supported. If there is a need to use an old version of RN/Yoga, an older version of XCode is required.

### ISSUE THREAD

**Issue by majirosstefan** [facebook/yoga#1270]
` RN versions before 0.69 are no longer being supported. If there is a need to use an old version of RN/Yoga, an older version of XCode is required.`

_Originally posted by @NickGerleman in https://github.com/facebook/yoga/issues/1224#issuecomment-1504946073_
                        
Here is quick solution / workaround
https://github.com/facebook/react-native/issues/36758

**Comment by NickGerleman** [comment]
Glad you have been unblocked, but as mentioned before, this issue in Yoga was fixed more than a year ago (and the version of RN where you are seeing this is unsupported, so there has not been effort to make it work with the new version of XCode).
