### ISSUE TITLE
Building for iOS Simulator for unsupported Swift architecture

### ISSUE THREAD

**Issue by morricd** [facebook/yoga#1281]
YogaKit.framework/Headers/YogaKit-Swift.h:263:2: error: unsupported Swift architecture
#error unsupported Swift architecture

**Comment by brownppfeng** [comment]
me too

**Comment by NickGerleman** [comment]
We are deprecating YogaKit as part of the Yoga 2.0 release. We are still going to release a new revision based on the current state of the repo, but won't be accepting new contributions, since we are going to be removing it from the repo after.
