### ISSUE TITLE
CMP0135 requires higher version of CMake

### ISSUE THREAD

**Issue by hubenchang0515** [facebook/yoga#1283]
# Report

- [x] I have searched [existing issues](https://github.com/facebook/yoga/issues) and this is not a duplicate

# Issues and Steps to Reproduce
`CMP0135` requires CMake version 3.24, see https://cmake.org/cmake/help/latest/policy/CMP0135.html
But in the `tests/CMakelists.txt` file is `cmake_minimum_required(VERSION 3.13)`

```bash
$ mkdir build
$ cd build
$ cmake ..
CMake Error at tests/CMakeLists.txt:18 (cmake_policy):
  Policy "CMP0135" is not known to this version of CMake.
```

# Expected Behavior
***Describe what you expected would happen.***

# Actual Behavior
***Describe what actually happened.***

# Link to Code
https://github.com/facebook/yoga/blob/main/tests/CMakeLists.txt#L7

https://github.com/facebook/yoga/blob/main/tests/CMakeLists.txt#L18

**Comment by NickGerleman** [comment]
Could you try patching in the PR for this? I think it should work.
