### ISSUE TITLE
Split core Flexbox algorithm implementation into a separate file

### ISSUE THREAD

**Issue by nicoburns** [facebook/yoga#1297]
The core Flexbox algorithm implementation currently lives in `Yoga.cpp` along with a bunch of functions like for example `YGNodeFreeRecursive` which are simple utility functions that are part of the public API. It would make it easier to navigate the code if the core algorithm code was separated from these public API functions.

# Link to Code

https://github.com/facebook/yoga/blob/main/yoga/Yoga.cpp

**Comment by NickGerleman** [comment]
There is a lot of splitting still to do, but this is now rooted at `CalculateLayout.cpp`.
