### ISSUE TITLE
Labels and image views baseline alignment support

### ISSUE THREAD

**Issue by zackhsuan** [facebook/yoga#132]
Hi all,

Flexbox natively supports baseline alignment, but it seems like react-native has not implemented this yet. 
I suppose that it would be awesome if css-layout could offer controls like labels or image views to work with baseline mode. Plus, the native auto layout tech supports baseline alignment too.

Many thanks. I appreciate all you excellent work.

**Comment by zackhsuan** [comment]
Is anyone here could help?

**Comment by lucasr** [comment]
I thinks this ticket is more about React Native than css-layout itself as this requires some platform-specific bits. Unless I'm missing something?

**Comment by zackhsuan** [comment]
Thanks for your reply. @lucasr but unfortunately, I was redirected by React Native to post the issue here. https://github.com/facebook/react-native/issues/3020 Any idea that I can at least get the right place to post this issue?

**Comment by emilsjolander** [comment]
Baseline support is definitely something which would be great if we could support. We are not actively working on this but I would be happy to work with you or anyone else in the community on a pull request implementing it.

**Comment by mpost** [comment]
`baseline` support sounds like a must have. Currently it is not possible to accurately align a "label" and a "text input" to be optical in line across platforms.

**Comment by emilsjolander** [comment]
@mpost totally agreed. Just not a top priority yet.

**Comment by mpost** [comment]
@emilsjolander thanks for the info. Speaking of top priorities, is there a roadmap to features we could expect?

**Comment by emilsjolander** [comment]
No roadmap just yet. I am thinking about posting something soon.

**Comment by woehrl01** [comment]
@emilsjolander @zackhsuan this can be closed now, can't it?
