### ISSUE TITLE
Typescript and intellisense issues with Yoga npm package version 2.0.0-beta.1

### ISSUE THREAD

**Issue by Omxjep3434** [facebook/yoga#1322]
# Report

I am writing a UI library that uses Yoga and I have been experimenting with using Typescript with Yoga, as well as making Typescript definition files for my classes that use Yoga, and I am running into issues. I believe it is related to the complex structure of the various entrypoints and the fact that there is no index.d.ts file, and no 'types' entry in package.json.

# Visual Studio Code example
This code is correct Javascript, but it produces no intellisense:
```
import { FlexDirection } from 'yoga-layout';
import { Align } from 'yoga-layout/sync';
const val1 = FlexDirection.Row; // No intellisense when I type "FlexDirection."
const val2 = Align.Row; // No intellisense when I type "Align."
```

This code produces correct intellisense, but it will be a runtime error. This import is actually what Visual Studio Code produces when auto-importing the FlexDirection constant:
```
import { FlexDirection } from 'yoga-layout/src/generated/YGEnums';
const val = FlexDirection.Row; // I do get correct intellisense when I type "FlexDirection."
```

# Typescript Definition Example
When writing d.ts Typescript definition files for my classes, I need to import types from a specific entrypoint. I guess this works, but I think it would be more ideal to import directly from 'yoga-layout'. Right now, importing directly from 'yoga-layout' will produce tsc compilation errors and 'yoga-layout' being an unrecognized module.
```
// MyUIControl.d.ts
import { Node, FlexDirection } from "yoga-layout/src/entrypoint/wasm-async";

declare class MyUIControl {
    yogaNode: Node;
    flexDirection: FlexDirection;
}

export default MyUIControl;
```

# Proposal
Correct me if I'm wrong, but I think what's missing is an index.d.ts file and a "types: index.d.ts" field in package.json. I tried this on my local version of the package and it seems to work great and seems to have solved all of the issues mentioned above.
```
// index.d.ts
import type { Yoga } from './src/wrapAssembly';

export * from './src/generated/YGEnums';
export type {
  Config,
  DirtiedFunction,
  MeasureFunction,
  Node,
  Yoga
} from './src/wrapAssembly';

export declare function loadYoga(): Promise<Yoga>;
```

There is one more obstacle. What about types for imports like: `import {Align} from 'yoga-layout/sync';`? This doesn't correspond to a physical folder. I'm not sure what would be the best way for specifying types for specific values in the export map.

Are there any thoughts on this proposal?

**Comment by NickGerleman** [comment]
It seems like your tsconfig is not configured to allow TypeScript to resolve the “package.json” exports field.

This can be set using the “moduleResolution” option in your tsconfig. I would recommend “bundler” if you are using TypeScript 5, otherwise an option like “nodenext” should work.

**Comment by Omxjep3434** [comment]
That does work for Typescript users, but what about Javascript users? They will have no tsconfig file. For example, my Visual Studio Code examples apply to Javascript users. They will essentially have no intellisense. Maybe that should be left for IDEs to implement though.

Do you think adding an index.d.ts file would be incorrect? I've never really dealt with type definitions and export maps in other projects.

**Comment by NickGerleman** [comment]
I had originally had an extra “index.js” and “sync.js” files to try to catch clients which weren’t configured to support the exports field, but it ended up instead seeming like more churn than worth it.

It effectively means that you can transparently get opted out of platform conditions, and makes it very easy to get mismatched types from source.

I think the field will continue to become more common, and new out-of-the-box tsconfig for Node and frameworks do now tend to choose a compatible option. https://github.com/tsconfig/bases/tree/main/bases

As that continues, I would expect that VSCode learns to do ES Module resolution when a configuration file isn’t present, but IDE usage of types in an otherwise untyped project isn’t something I’ve tried to really test.

**Comment by Omxjep3434** [comment]
Cool, sounds good, I'll close the issue.
