### ISSUE TITLE
Typo:React Native Development

### ISSUE THREAD

**Issue by marcellusj** [facebook/yoga#1343]
# Report
There's a typo in Yoga.cpp that causes problems for react native development as it's one of the dependencies. A screenshot can be seen below. The problem is easily solved by changing `|` into `||`.

![image](https://github.com/facebook/yoga/assets/78376105/31edbae2-b788-4b85-8eea-5155a1ea96d2)

Can this typo please be corrected.
# Issues and Steps to Reproduce
***Developing in React Native(react native cli), with Yoga as one of the dependencies. Using CocoaPods on M1 Mac.***

# Expected Behavior
***Successful compile.***

# Actual Behavior
***Syntax Error.***

# Link to Code
**The code snippet with the type is [here](https://github.com/facebook/yoga/blob/ef5784aca647a68343f5409e379519827edb86a9/yoga/Yoga.cpp#L3034)**

**Comment by NickGerleman** [comment]
Please see https://github.com/facebook/react-native/issues/36758. This was updated in React Native more than a year ago, and if you are seeing this, it is likely you are using an unsupported version of React Native with a current version of XCode.
