### ISSUE TITLE
Could not find com.facebook.yoga.android:yoga-layout:2.0.0-beta.1

### ISSUE THREAD

**Issue by zjt123** [facebook/yoga#1346]
# Report

- [ ] I have searched [existing issues](https://github.com/facebook/yoga/issues) and this is not a duplicate

# Issues and Steps to Reproduce
***Replaces this with steps to repro your issue.***

# Expected Behavior
***Describe what you expected would happen.***

# Actual Behavior
***Describe what actually happened.***

# Link to Code
***If you have some code that maintainers can clone/test for themselves, bugs can be resolved much faster. Please paste a link here.***

***When applicable, use this [fiddle](https://jsfiddle.net/emilsjolander/jckmwztt/) to post a web repro.***

**Comment by NickGerleman** [comment]
I am seeing the package available at Maven Central: https://central.sonatype.com/artifact/com.facebook.yoga/yoga-layout/2.0.0

If you are seeing a specific error, please fill out this issue with more details. We are not able to help if information is not provided.
