### ISSUE TITLE
EXC_BAD_ACCESS in `new yoga::Config(getDefaultLogger())` when building for iOS 14 using Xcode 15

### ISSUE THREAD

**Issue by clausjoergensen** [facebook/yoga#1390]
# Report

- [x] I have searched [existing issues](https://github.com/facebook/yoga/issues) and this is not a duplicate

# Issues and Steps to Reproduce

- Build Yoga 2.0 (or 1.19, same issue) in Xcode 15, targeting a iOS 14.5 Simulator
- Run the project

# Expected Behavior

Should not crash

# Actual Behavior

Crashes

![image](https://github.com/facebook/yoga/assets/233721/6afba9de-4c47-4ebb-b672-6c0349753972)

# Stack

```
Thread 1 Queue : com.apple.main-thread (serial)
#0	0x0000000000000000 in 0x00000000 ()
#1	0x0000000108bed2d8 in ::YGConfigNew() at /Users/<redacted>/SourcePackages/checkouts/yoga/yoga/Yoga.cpp:182
```

# Other

- No issues when building with Xcode 14.2, this is a new issue with the Xcode 15 toolchain.

- No issues when building for iOS 15 or higher.

**Comment by clausjoergensen** [comment]
It's quite likely it's this issue:

> Binaries using symbols with a weak definition crash at runtime on iOS 14/macOS 12 or older. This impacts primarily C++ projects due to their extensive use of weak symbols. (114813650) (FB13097713)

From https://developer.apple.com/documentation/xcode-release-notes/xcode-15-release-notes#Linking

**Comment by clausjoergensen** [comment]
@NickGerleman 

I found another issue here. Turns out -ld_classic isn't available in older versions of Xcode, so this isn't safe to ship as part of the Package.swift :(

Instead consumers of Yoga should add this themselves if they use Xcode 15 and support iOS 14 and below.

**Comment by NickGerleman** [comment]
Going to close this out, since it seems like we are not going to action.
