### ISSUE TITLE
Absolute children do not respect padding of parent

### ISSUE THREAD

**Issue by joevilches** [facebook/yoga#1436]
Absolute children should begin layout at the origin of the content box assuming no insets are defined. Yoga lays the child out at the origin of the padding box. This does not appear to be an issue for relative children.

Expo: https://snack.expo.dev/@joevilches/spontaneous-green-turkish-delight 

```jsx
import {SafeAreaView, StyleSheet, View } from 'react-native';

export default function App() {
  return (
    <SafeAreaView>
      <View style={styles.container}>
        <View style={styles.child} >
          <View style={styles.grandchild} />
        </View>
      </View>
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  container: {
    position: 'relative',
    backgroundColor: "red",
    margin: 10,
    width: 200,
    height: 200,
    flexDirection: "row",
  },
  child: {
    backgroundColor: "blue",
    flex: 1,
    height: 200,
    width: 200,
    padding: 50,
  },
  grandchild: {
    backgroundColor: "green",
    height: 50,
    width: 50,
    position: "absolute",
    flex: 1,
  },
});
```

Web
<img width="298" alt="Screenshot 2023-10-25 at 3 50 43 PM" src="https://github.com/facebook/yoga/assets/17124862/fc883c0f-93c5-4de2-9129-5b78e2740726">

Mobile
<img width="297" alt="Screenshot 2023-10-25 at 3 50 26 PM" src="https://github.com/facebook/yoga/assets/17124862/d386a922-e4c4-469e-acf8-9035d052cad4">

**Comment by rfvtgbzxc** [comment]
> Should probably also test for border, which affects the context box in a similar way to padding.

In my test, the border attribute in https://www.yogalayout.dev/playground, children in absolute position respect the border of parent, while the padding attribute do not so. And in package 3.0.4, both border and padding are invalid for children those in absolute position.

**Comment by NickGerleman** [comment]
@joevilches, I can’t remember, did you make this better with absolute positioning work?

**Comment by joevilches** [comment]
Yeah this should be resolved now, for both border and padding. I added #1650 just to make sure, which just mimics the test I had above. @rfvtgbzxc it looks like the playground link you sent is just the default one, can you click the link button in the top right of the code editor so I can see what you are testing?

**Comment by joevilches** [comment]
@rfvtgbzxc Thanks for the link! From my testing it seems that Yoga is working as expected and matching the web: https://jsfiddle.net/joevilches/xLj9rquf/1/. 
<img width="275" alt="Screenshot 2024-05-06 at 13 33 34" src="https://github.com/facebook/yoga/assets/17124862/795eb406-b6ef-430c-be5c-ae82eea7eef7">

Maybe you could be more specific as to what you see is wrong?
1. (blue box in web example) This child is positioned correctly and sized correctly. The positioning is from the content box as expected, the height is defined, and the width is 100% the size of the containing block's padding box.
2. (orange box) This new parent has no width or height defined. Because yoga's default flex direction is column, this means this node will have 0 height and width that will stretch to fill the container. As a result, 100% of the width means that it will be the size of the content box which it is.
3. You notice this because now the padding box is 80 instead of 100, so '100%' means something else. % with absolute nodes always refers the containing block's padding box.

**Comment by NickGerleman** [comment]
@rfvtgbzxc do you want the behavior to be that position stretches all the way to edge of box?

This behavior is inconsistent with web, but you can emulate the behavior of older Yoga by setting “AbsolutePositioningIncorrect” errata.

https://www.yogalayout.dev/docs/getting-started/configuring-yoga#layout-conformance-and-yoga-errata

**Comment by rfvtgbzxc** [comment]
Thanks for your annotation, I misunderstand the inner mechanisim of the flex layout.
