### ISSUE TITLE
[!] An error occurred while processing the post-install hook of the Podfile.

### ISSUE THREAD

**Issue by guohongqi-china** [facebook/yoga#1442]
# Report

- [ ] I have searched [existing issues](https://github.com/facebook/yoga/issues) and this is not a duplicate

# Issues and Steps to Reproduce
***Replaces this with steps to repro your issue.***

# Expected Behavior
***Describe what you expected would happen.***

# Actual Behavior
***Describe what actually happened.***

# Link to Code
***If you have some code that maintainers can clone/test for themselves, bugs can be resolved much faster. Please paste a link here.***

***When applicable, use this [fiddle](https://jsfiddle.net/emilsjolander/jckmwztt/) to post a web repro.***

**Comment by NickGerleman** [comment]
This issue contains no useful information. Please follow the template, and include a reproducible example, or a full error message at a minimum.

The Yoga podspec doesn't have a pos-install hook. I'm guessing this might be when building React Native?
