### ISSUE TITLE
wasm-sync file index error in package.json

### ISSUE THREAD

**Issue by uinz** [facebook/yoga#1444]
# Report

- [x] I have searched [existing issues](https://github.com/facebook/yoga/issues) and this is not a duplicate

# Issues and Steps to Reproduce
`import "yoga-layout/wasm-sync"` jump to wrong file.

# Expected Behavior
`import "yoga-layout/wasm-sync"` jump to ./src/entrypoint/wasm-**sync**-web.js

# Actual Behavior
`import "yoga-layout/wasm-sync"` jump to ./src/entrypoint/wasm-**async**-web.js

# Link to Code
https://github.com/facebook/yoga/commit/5310eb3cf7892ae905c9492355b088dd5269547a#r131421132

 
```json5
"./wasm-sync": {
  "browser": "./src/entrypoint/wasm-sync-web.js",
  "node": "./src/entrypoint/wasm-sync-node.js",
  "default": "./src/entrypoint/wasm-async-web.js"
  //                                ^^^^^ it should be sync
}
```

**Comment by NickGerleman** [comment]
Oof. I can publish a new version with a fix.

Next version of Yoga (planning to do a release at the same time as RN 0.74) is single flavor, but relies on ES module top-level await to do that.

**Comment by NickGerleman** [comment]
Pushed a fix: https://www.npmjs.com/package/yoga-layout/v/2.0.1
