### ISSUE TITLE
Typo in recent module.modulemap change that breaks Swift PM-based builds 

### ISSUE THREAD

**Issue by markbeaton** [facebook/yoga#1468]
# Report

- [x] I have searched [existing issues](https://github.com/facebook/yoga/issues) and this is not a duplicate

# Issues and Steps to Reproduce
Add a Swift package dependency to an iOS project, using Yoga `main` as the source, e.g.
```
dependencies: [
  .package(url: "https://github.com/facebook/yoga.git", branch: "main")
]
```
Try building the app

# Expected Behavior
Packge downloads, app builds

# Actual Behavior
There's now compile error `~/Library/Developer/Xcode/DerivedData/EVC-bydlhmwwpocypdbxfvgyintbwnnk/SourcePackages/checkouts/yoga/yoga/module.modulemap:15:16 Header 'YGNodeStye.h' not found`

Line in `module.modulemap` should be `YGNodeStyle.h`: https://github.com/facebook/yoga/blob/1b1df3a87e829533724405a1ed594181ea11ef3e/yoga/module.modulemap#L15

**Comment by NickGerleman** [comment]
Looks like the Swift Build Automation we have does not include anything for the headers the project generates. Need to add more/better tests here alongside fixing the typo.
