### ISSUE TITLE
Percentage widths support

### ISSUE THREAD

**Issue by koppelaar** [facebook/yoga#147]
This issue has been brought up before (https://github.com/facebook/css-layout/issues/57) and has been closed, which I think should not be the case. 

It's currently not possible to give an element a width of 50% without creating an empty dummy element next to it and assigning appropriate flexbox properties to both of them, which is of course a very weird solution. (http://stackoverflow.com/questions/18744164/flex-box-align-last-row-to-grid)

Also the lack of percentage support, makes it really hard to use proper media queries. Example:
You have 12 elements in a single container. On a small screen with you want to align them in 6 rows of 2 columns. On a bigger screen, you want them to align in 4 rows of 3 columns, using media queries. 

Normally you'd like to give the elements a width of 50% in the first scenarios and 33.33% when the media query kicks in. This is not possible since we can only 'fake' percentage widths when we introduce a 'row container'. So in order to make the app responsive, we'd need to use Javascript to dynamically move the items around between the row containers, which is less than ideal.

**Comment by spicyj** [comment]
I imagine we would be happy to take a pull request for this, but it hasn't been a high priority because it is possible to replicate the behavior in most cases using flexbox even though it's "weird".

**Comment by hayesmaker** [comment]
+1, seems weird to reimplement css without support for % widths (and height)

**Comment by cxfeng1** [comment]
+1

**Comment by appleguy** [comment]
@spicyj curious what the recommended way is to replicate with the other functionality?  AsyncDisplayKit relies on a set of code similar to css-layout (it's ComponentKit's flexbox implementation), but it shares a similar limitation I'd like to resolve.

**Comment by spicyj** [comment]
@appleguy I meant that in most cases, you can build equivalent layouts using flex box (perhaps with spacer views). For example, if you want a width 50% box, make two siblings each with flex 1. If you are trying to support percentages generically in ASDK, it is probably simplest to just change the flexbox implementation you have. I looked at adding percentage support to this one – looked pretty simple; the hardest part might be figuring out what the API should be (since at least the current C API here assumes pixels).

**Comment by appleguy** [comment]
Aha, thanks for the input!  Indeed we have ASRelativeDimension, which can express the idea of a %, absolute, or points - but just don’t have the logic (and also the API, but that would be relatively easy to add by changing our flexGrow / flexShrink from BOOL to a number).  A project for another evening.

**Comment by vitalets** [comment]
+1

**Comment by dubert** [comment]
I get the screenWidth and divide by 2 if I need an element that is 50% and don't want to create a dummy element.

**Comment by vitalets** [comment]
@dubert it works if you only create single orientation app. Otherwise on orientation change your elements will not update.

**Comment by aakashsigdel** [comment]
+1 really tedious to replicate some behavior with flex. Adding spacer views shouldn't be the solution for each and every case.

**Comment by vjeux** [comment]
To repeat what @spicyj said, percentage support is something we want but haven't focused on so far. If you want to have an impact, please do work on implementing it :)

**Comment by pavlelekic** [comment]
+1, this would really solve the problem with ListViews in grid mode, currently there is no good solution and I think grids are important for a lot of apps

**Comment by n1ru4l** [comment]
I did it this way, by using a template string (react):
```jsx
<div className='upload-file__progress' style={{width: `${progress}%`}} />
```

**Comment by pavlelekic** [comment]
@n1ru4l that is react for the web, I was talking about react native. In react for the web you don't need this repo at all

**Comment by emilsjolander** [comment]
Percentage sizes is something we would like to support but have not spent any real time on implementing due to not having a strong need for it. There are certain performance concerns regarding supporting the feature but I would be happy to work with the community to support this. As @vjeux said this is a great opportunity to have big impact by submitting a pull request. We are not currently prioritizing this as we have not seen a big need for it yet our selves.

**Comment by faceyspacey** [comment]
+1 ...obviously you can calculate everything in javascript or hack flexbox, and i've done both many times for simple scenarios, but I've recently run into some situations where the amount of calculation I had to do was way too high compared to how easy it is on web. 

In addition, *React Native Web* supports it, so it would bring parity with RNW which is rapidly increasing in popularity, and something I think will become a big piece of the React "Native" puzzle. So perhaps the RNW factor increases the priority of this item.

**Comment by woehrl01** [comment]
I started to add percentage support to my branch: https://github.com/woehrl01/css-layout/tree/percentage-feature. Can someone have a look if we want to go this direction? @emilsjolander

**Comment by emilsjolander** [comment]
@woehrl01 Cool! Yeah this looks to be going in the correct direction. I'm a bit concerned about perf and there are a lot more tests to be added.

**Comment by woehrl01** [comment]
@emilsjolander for sure there are a lot of things which can be tuned. And the tests aren't totally enough.  Just wanted to make a sneak preview to consider your opinions.

**Comment by emilsjolander** [comment]
@woehrl01 Yeah, thanks! looking good

**Comment by sospedra** [comment]
+1

**Comment by mokafolio** [comment]
@woehrl01 That looks good to me! Did you try running the benchmarks by any chance?

**Comment by woehrl01** [comment]
@mokafolio Have a look at #258 I posted some benchmark from my dev-machine. I was able to make it even slightly faster, by reducing the calls to ```isnan```. As I have currently no other device available I would be glad if someone could approve those values on slower devices (android/ios) and/or compiled with gcc. My values are produced with release + o2 + mvc++.

**Comment by michaelcpuckett** [comment]
+1
