### ISSUE TITLE
React Native iOS build failed

### ISSUE THREAD

**Issue by tabekg** [facebook/yoga#1527]
# Report

- I have searched [existing issues](https://github.com/facebook/yoga/issues) and this is not a duplicate

When I build Application from XCode I got error "Could not build Objective-C module 'YogaKit'"

**Comment by NickGerleman** [comment]
This issue doesn't have any useful information to diagnose.

Please feel free to create an issue on the RN repo, including the full build error. Note that YogaKit hasn't been around for a while, so I suspect this may be an older RN version?
