### ISSUE TITLE
__dirname is not defined in ES module scope

### ISSUE THREAD

**Issue by wojtekmaj** [facebook/yoga#1559]
# Report

- [x] I have searched [existing issues](https://github.com/facebook/yoga/issues) and this is not a duplicate

# Issues and Steps to Reproduce

Import yoga-layout in an ESM project.

# Expected Behavior

Yoga to be correctly imported.

# Actual Behavior

```
__dirname is not defined in ES module scope
```

# Note

It looks like it's the only issue that causes yoga-layout from working seamlessly in ESM environment.

**Comment by wojtekmaj** [comment]
Appears to be related: https://github.com/emscripten-core/emscripten/issues/12184

**Comment by NickGerleman** [comment]
There's an upcoming change for the next major version of Yoga (releasing mid-feb), where we ended up making the JS bindings ES module compatible (and actually, only ES module compatible, for reasons around TLA and the future wasm module integration is going). https://github.com/facebook/yoga/commit/ef1d772447c53266f57263e96420e24536b38d5d is the commit that made that change.

This is not on the npmjs registry yet, and I still need to document that change when we do release notes, but I am fairly certain that would fix this issue (and will also break compat with CommonJS, unfortunately).

**Comment by NickGerleman** [comment]
Going to close this out, since I think it should be fixed by the upcoming release, but let me know otherwise.
