### ISSUE TITLE
The typescript definitions link in the standalone documentation is incorrect

### ISSUE THREAD

**Issue by notchris** [facebook/yoga#1577]
# Report

- [ x] I have searched [existing issues](https://github.com/facebook/yoga/issues) and this is not a duplicate

# Issues and Steps to Reproduce
- Visit: https://yogalayout.dev/getting-started/standalone/
- Click the "TypeScript type definitions" link

# Expected Behavior
It should point to: "https://github.com/facebook/yoga/blob/main/javascript/src/wrapAssembly.ts"

# Actual Behavior
It points to: "https://github.com/facebook/yoga/blob/main/javascript/src/wrapAssembly.d.ts"

**Comment by NickGerleman** [comment]
We are going to be replacing the current copy of the website pretty soon (deleting the one rooted in `/website`), which should (indirectly) fix this.

**Comment by NickGerleman** [comment]
https://github.com/facebook/yoga/pull/1594 also fixed this.
