### ISSUE TITLE
Top Level Await

### ISSUE THREAD

**Issue by bbohlender** [facebook/yoga#1637]
Hey, congrats on launching yoga 3.0 🥳 

I am building [@react-three/uikit](https://github.com/pmndrs/uikit) and I've just upgraded it to yoga 3.0.
Unfortunately, for many bundlers/frameworks top-level-await requires additional configuration (vite requires setting target to esnext in the vite config) or simply doesn't work (nextjs 14 with app router).

I like the idea of having top-level-await for this library but I think the tooling is not there yet. I think an additional entry point without top-level-await would be appropriate while the tooling catches up (I can make a PR for that if reasonable).

**Comment by NickGerleman** [comment]
> I like the idea of having top-level-await for this library but I think the tooling is not there yet. I think an additional entry point without top-level-await would be appropriate while the tooling catches up (I can make a PR for that if reasonable).

I think having a secondary entrypoint without TLA might make sense, as a fallback to those who cannot use it. I tried to consolidate the flavors compared to previous version (where it got a bit out of hand), but TLA is probably going to be the biggest thing preventing 3.0 from working automagically in a lot of setups.

It does Seem like TLA is getting there. 95% browser support, all stable versions of Node, standardized in ES2022 (but, Vite defaults to `es2020`). But as you noted, common toolchains out there still aren't set up to support it by default.

Later down the line is ESModule WASM integration, which has historically explicitly depended on TLA, but that [might have changed](https://github.com/WebAssembly/esm-integration/commit/9f6136d664818e9a6e92caf0d2e2515cc8ae7bcd).

**Comment by bbohlender** [comment]
Fixed with #1638 
@NickGerleman, thanks for merging 🙏 
Is there an expected release timeline for, e.g., 3.0.3, so I can move a few users of uikit to the latest version that uses yoga 3.0 ? :)

**Comment by NickGerleman** [comment]
@bbohlender I will push out a new release in the next couple days

**Comment by NickGerleman** [comment]
Yoga 3.0.3 should be published now

**Comment by bbohlender** [comment]
@NickGerleman thank you very much for pushing this out so fast.
I've just finished moving uikit to `yoga-layout/load`.

Unfortunately, the use of `exports` resulted in discovering what is, in my opinion, a typescript bug. Essentially typescript prefers to resolve `xy.z.js` to `xyz.ts` even if `xyz.js` exists only if using the `exports` field. The following screenshots show that even version `3.0.2` throws an error if I add
```
"exports": {
  ".": "./src/index.js"
}
```
to the package.json. I'll raise the bug in typescript, but for now, it would be great if there could be a pipeline step that removes the `.ts` file before publishing.

with `exports` field:
![Screenshot 2024-04-11 at 09 27 37](https://github.com/facebook/yoga/assets/85560643/6cb9c3df-9e45-4f63-8ac7-6833145bb7f9)

without `exports` field:
![Screenshot 2024-04-11 at 09 25 22](https://github.com/facebook/yoga/assets/85560643/ed70eb2d-788c-4871-aa69-8b8900226c93)

**Comment by NickGerleman** [comment]
@bbohlender I think https://github.com/facebook/yoga/pull/1645 should fix this

**Comment by bbohlender** [comment]
@NickGerleman Yes, definitely, thank you very much 🙏🏼

I assume there are complex reasons why the javascript is transformed and built using the current setup.

Not knowing these reasons and based on my knowledge of the standards for setting up typescript projects, I would simplify the build setup to only use `tsc` for the compilation, setup the `outDir` of the `tsconfig.json` to dist, reference the js files in the package.json, and use `.js` file extensions to `import` other modules. If this was considered and is impossible, just ignore this comment :) if otherwise simplifying the build step in this manner sounds interesting, I'd be happy to try applying this in a PR :)

**Comment by NickGerleman** [comment]
> Not knowing these reasons and based on my knowledge of the standards for setting up typescript projects, I would simplify the build setup to only use tsc for the compilation, setup the outDir of the tsconfig.json to dist, reference the js files in the package.json, and use .js file extensions to import other modules. If this was considered and is impossible, just ignore this comment :) if otherwise simplifying the build step in this manner sounds interesting, I'd be happy to try applying this in a PR :)

We transform code using Babel instead of `tsc` partially for more control, but also because that means that e.g. Jest tests transforms produce the same code as what we ship. So, `tsc` is only used for typechecking, and generating declarations.

Output `.js` code should only ever reference other JS because of import rewriting. We don't do this in dev environment, where we want it pointing to actual source for typechecking purposes (and where nodenext resolution requires extension). Original TS files are included as general good practice, so that anyone who ends up debugging into Yoga has access to working source maps, pointing to original source.

**Comment by bbohlender** [comment]
Thanks for explaining 🙏🏼 makes total sense. If some of these reasons eventually don't apply and my proposal seems reasonable, I'd be happy to offer my help :)

Anyways, thank you very much for implementing #1645 🎉
