### ISSUE TITLE
get/setDirection() bindings missing from Yoga npm version 3.0.4

### ISSUE THREAD

**Issue by Omxjep3434** [facebook/yoga#1664]
# Report

Hello Yoga team, I apologize if I'm missing something obvious, but I don't see the bindings for getDirection() and setDirection() in npm version 3.0.4.

It seems this should be included. If I look at the branch compare: https://github.com/facebook/yoga/compare/v3.0.4...main
I see this commit on March 12th: https://github.com/facebook/yoga/commit/bd3e3edc753a3357dfaea058d75a241afe4ae53b

However, I don't see these changes in the 3.0.4 `src/wrapAssembly.ts` file and Javascript indeed throws an error if I call `node.getDirection()`.

I also noticed that setting a direction per node works in the Yoga Playground.

**Comment by NickGerleman** [comment]
> It seems this should be included. If I look at the branch compare: https://github.com/facebook/yoga/compare/v3.0.4...main

I think this is looking at the changes that happened since 3.0.4 in main?

It looks like adding the binding did not make the branch cut for 3.0. Though I'm likely going to cut a new minor soon, just matching RN branch cut, which should include this.

**Comment by SeanPeplinski** [comment]
Cool, thanks Nick!

**Comment by Omxjep3434** [comment]
Cool, thanks Nick!
