### ISSUE TITLE
Child node size is wrong when layout is measured by parent

### ISSUE THREAD

**Issue by hukpo** [facebook/yoga#1680]
Is this expected? If yes, should I check every child and measure their layout to get the correct size?

![telegram-cloud-photo-size-2-5220047739562351461-y](https://github.com/facebook/yoga/assets/40897161/972619e0-e879-44df-92c1-155e3f34694d)

**Comment by NickGerleman** [comment]
Child has `flexDirection: column` and `align-items: stretch` by default, so I think this is just stretching the cross-axis according to that.

**Comment by hukpo** [comment]
> Child has `flexDirection: column` and `align-items: stretch` by default, so I think this is just stretching the cross-axis according to that.

But there is setMeasureFunc which defines size, shouldn't it respect that? Without setMeasureFunc it's logical to stretch the child, I agree.
