### ISSUE TITLE
SVG Antivirus reporting your website yogalayout.dev as blocked

### ISSUE THREAD

**Issue by tohagan** [facebook/yoga#1684]
# Here's the AVG Antivirus report 

![image](https://github.com/user-attachments/assets/3c77a687-6616-48d1-97ff-5529da5d280e)

**Comment by NickGerleman** [comment]
No idea why this would be, or how to avoid this (curious what the details say). The only guess I could have is that the website uses WebAssembly. The full source is here, in /website, if you are curious.

**Comment by tohagan** [comment]
Given the additional pop up displayed by AVG (see below) I suspect your site is on a black list. 
I've done a quick search on SecureFeed.com and not found it.
- https://securefeed.com/Content/WebLookup?host=yogalayout.dev

I suggest that you contact AVG. 

![image](https://github.com/user-attachments/assets/1f5c8b0a-7496-45e1-afb5-34454f93e01a)

**Comment by tohagan** [comment]
OK I found your domain via this blacklist checker: 

- https://www.zerobounce.net/blacklist-checker/


Looks like this Polish blacklist polspam.pl has your site listed for some unkown reason.
They provide these deslisting instructions:
- https://polspam.pl/dlst.php

**Comment by NickGerleman** [comment]
Thank you for sharing! Interesting to know. 

polspam seems… not particularly reputable. https://www.reddit.com/r/sysadmin/s/u61gtj62SH

So, I’m not going to try to fight them to delist the documentation I tried to put together. I would recommend potentially using a different Antivirus which doesn’t subscribe to such blanket blocklists, unless this was added manually.
