### ISSUE TITLE
[bug] `alignItems` not working

### ISSUE THREAD

**Issue by trusktr** [facebook/yoga#1695]
# Report

- [x] I have searched [existing issues](https://github.com/facebook/yoga/issues) and this is not a duplicate

# Issues and Steps to Reproduce

See [Playground Example](https://www.yogalayout.dev/playground?code=DwGQhgng9grgLgAgMZQHYDMCWBzAvAb3xgGcBTAdVICMARU9MGAGzmIC4E4AnGUgXz4A+AFAIEwAHJQAJqVFiExOBCakC+eQoQB3TNLgALDgCYArAAYANJoUHSOA3BMXrWsQAcw06ZlTYOAIxWNmLYYO4mrm4AViRwmOgQAMJocKSoTggA5OiqAB4AtOnSWVFaYEw4qACSaQC27Nm5pIXFpSEIzXnkXOEcWdq97u1aAiJakjKkisqq6nVgXNi+HKaWCHYOmS46eoar5gIIAPTjCpOyMypqhAtLKwhrG-bYjgfruvpGj4d8J2diC7TJTXeaLZaoVbrTavbZWXZfA5HU42IFXOa3cEPJ4wt4-D57b4WZFnYDHKSyERk8DQeCCIA)

Try changing alignItems to center or flex-end and notice it is not working the same as with CSS.

# Expected Behavior

Expecting it to work like in CSS. Video:

https://github.com/user-attachments/assets/5d4663d1-6b7f-44aa-b8e1-3919abdc45d6

# Actual Behavior

In the yoga example, the items do not shift like in the CSS video

# Link to Code

see above

**Comment by trusktr** [comment]
I tried setting `container.setAlignContent(Align.Center)`, but that breaks it all, makes the computed height of container go to zero.

Is there an order of operations I might need to be aware of for Yoga that we normally don't have to think about with CSS flexbox?

**Comment by trusktr** [comment]
I discovered that if I *do not* set alignItems, and set only alignContent, then alignContent works.

In CSS, both can be set, and it seems that align-content takes precendence over align-items, but in Yoga if I apply both, the computed height of root goes to zero instead of alignContent effectively overriding alignItems.

**Comment by trusktr** [comment]
In yogalayout.dev, I am not able to reproduce the issue that happens by using both alignItems and alignContent together. Paste the following into yoga playground and alignContent does its job:

```jsx
<Layout config={{useWebDefaults: true}}>
  <Node
    style={{
      width: 250,
      height: 250,
      padding: 10,
      gap: 2,
      justifyContent: 'flex-end',
      alignItems: 'flex-end',
      alignContent: 'center',
      flexWrap: 'wrap',
    }}>
    <Node style={{margin: 5, height: 50, width: 50}} />
    <Node style={{margin: 5, height: 50, width: 50}} />
    <Node style={{margin: 5, height: 50, width: 50}} />
    <Node style={{margin: 5, height: 50, width: 50}} />
  </Node>
</Layout>
```

In my case adding `alignContent` just breaks. Seems like there are pecularities in how I'm calling Yoga (order of operations? calculateLayout args?) that are affecting my case.

**Comment by trusktr** [comment]
I deleted all my comments. There are multiple issues, but I fimplified the OP to show only one issue with reproduction.

**Comment by NickGerleman** [comment]
Yoga vs web for reference: https://jsfiddle.net/xkrfp2do/1/

This looks like a bug.

<img width="325" alt="image" src="https://github.com/user-attachments/assets/9cd22c32-9019-4218-a934-6652f3bb981d">
<img width="297" alt="image" src="https://github.com/user-attachments/assets/4ad496b7-6170-446e-88dd-b7acabe2cba8">
