### ISSUE TITLE
Measure block should be told the constraint size after clamping with min/max dimensions

### ISSUE THREAD

**Issue by molon** [facebook/yoga#201]
Thanks for the great library first.

css-layout call the measure block first https://github.com/facebook/css-layout/blob/6e05325f08207f624f5e2ef14c9301f6a6538bf8/src/Layout.c#L672-L709 and processing with `boundAxis` method second.

It lead us to have to clamp the constraint size with min/max dimensions ourself when we create a measure block.

Sorry, poor english lead to unclear expression.
Here is a demo below:
https://github.com/molon/MLLayout/tree/IssueOfCssLayout
The test located in `SimpleViewController.m`
https://github.com/molon/MLLayout/blob/IssueOfCssLayout/Example/MLLayoutDemo/SimpleViewController.m#L113-L133

**Comment by emilsjolander** [comment]
We have fixed a lot of min/max issues since 6 months back. Closing this out now. If you still have issues please re-open.
