### ISSUE TITLE
Add CF_SWIFT_NAME and NS_ENUM macro

### ISSUE THREAD

**Issue by wildthink** [facebook/yoga#235]
Adding the CF_SWIFT_NAME and NS_ENUM macros would provide a clean Swift interface out-of-the-box. Would you add this to the main project if it was available?

`Color ColorCreateWithCMYK(float c, float m, float y, float k)
          CF_SWIFT_NAME(Color.init(c:m:y:k:));`

Refs:
https://developer.apple.com/library/content/documentation/Swift/Conceptual/BuildingCocoaApps/InteractingWithCAPIs.html

**Comment by emilsjolander** [comment]
Yes please! Can you submit a pull request?

**Comment by emilsjolander** [comment]
We are instead adopting a better obj-c wrapper which will work more nicely in swift.
