### ISSUE TITLE
Feature: possibility to hide nodes

### ISSUE THREAD

**Issue by roxlu** [facebook/yoga#241]
I know this is currently by design, but it would be great if we could hide / show nodes. Any roadmap on this? Maybe we can have a chat and I can implement this?

**Comment by roxlu** [comment]
Hey @emilsjolander yes removing would be a solution though probably less convenient that toggling the visiblity. My use case is a GUI that uses CssLayout where you often have things that you want to show/hide: for example selectboxes, menus, popups etc.  Adding/removing a node dynamically (and making sure the order stays the same) means quite some extra bookkeeping compared to having a visibility toggle. Especially because it's quite common in guis to hide/show things. Do you have any concerns with adding this visibility flag?

**Comment by emilsjolander** [comment]
I have concerns about adding things which are not needed as it bloats the API. That said I think you have made a good point regarding keeping ordering and the bookkeeping needed for that. Adding visibility to cssnode would make sense. It would be great if you can implement this as then you can also test that it works for your situation 👍 All that should be required is to skip invisible children when iterating of the list of children. This could be done by `if (child->invisible) continue;` at the top of each child loop. Make sure to add tests for this as well 💯

**Comment by roxlu** [comment]
(Y) awesome, I'll look into this.

**Comment by emilsjolander** [comment]
Thanks!

**Comment by woehrl01** [comment]
Not sure if this is a great feature as in pure css ```visibility: hidden``` still takes the space. The same for ```UIView``` on iOS.

**Comment by roxlu** [comment]
@emilsjolander are you on irc or skype?

**Comment by emilsjolander** [comment]
@roxlu totally missed this sorry. Feel free to hit my up on fb messenger (m.me/sjolander.emil)

**Comment by emilsjolander** [comment]
@woehrl01 I agree, using `visible` could be very confusing

**Comment by roxlu** [comment]
@emilsjolander I did some experimenting and I think it's almost working. There is only one issue that needs to be solved: when you hide a node before calling layout() it will never be shown again. When you hide after calling layout() it works as expected. 

I've pasted some test code using my fork: https://gist.github.com/roxlu/5d489941de7956c808823f85fd71ab49 

It seems that things are cached. @emilsjolander shall we have a call to look into this?

**Comment by emilsjolander** [comment]
@roxlu I would suggest stepping through the code with a debugger and figuring out why your hidden node is not being shown when hiding it before calling layout()

**Comment by roxlu** [comment]
@emilsjolander thanks for your reply, but currently I don't have time to dive into the code. It would take me some time to be able to understand the code in detail. Though ... maybe you have some ideas where to look?

**Comment by emilsjolander** [comment]
@roxlu If it is using cached measurements you can have a look at the `CSSNodeCanUseCachedMeasurement` function. Perhaps make it always return `false` to see if this is the problem.

**Comment by roxlu** [comment]
@emilsjolander I just tested with a `CSSNodeCanUseCacheMeasurement` returning always false and this gives me these results: https://gist.github.com/roxlu/db899e390deda9e06445d2759a482fa1

Interestingly it seems that the version A and B works, but then at step C where I hide the first 5 items (see paste) it is still using the values after that were calculated at step B.

**Comment by emilsjolander** [comment]
Sounds like you may just not be reseting the nodes output in between

**Comment by roxlu** [comment]
I've set gPrintTree / gPrintChanges to true, it that what you mean?

**Comment by roxlu** [comment]
@emilsjolander Do I need to make a parent as dirty when one of it's children changes visibility? Maybe the root not (and so all children) is just skipped when I only mark a child as dirty (?).

**Comment by emilsjolander** [comment]
Yes you do, the dirty marking function does this for you though

**Comment by emilsjolander** [comment]
What I meant by not reseting nodes is that perhaps the nodes are just skipped over in the last pass (as expected) so that their layout outputs (width/height/x/y) are never reset and they just keep the ones from before. I don't have time now to dig down into your code :/

**Comment by roxlu** [comment]
It's okay if the width/height/x/y stay the same as before when hiding a element. It seems that the issue is related to the dirty flag. When I call `CSSNodeHide()` or `CSSNodeShow()`  on a child, the parent is not marked as dirty.  [See here for these functions](https://github.com/roxlu/css-layout/blob/feature-hidden-nodes/CSSLayout/CSSLayout.c#L292).

**Comment by emilsjolander** [comment]
Look at the definition of `_CSSNodeMarkDirty`, it's a recursive function calling up to the parent so I don't this this is your issue.

**Comment by roxlu** [comment]
I agree :) that it seems wrong that it's the dirty flag.  I'm printing out the condition results in `layoutNodeInternal()` that set the `needToVisitNode`, this is what I get: 

````
node->isDirty: n
layout->generationCount != gCurrentGenerationCount: y
layout->lastParentDirection != parentDirection: n
````

And the code I'm using for this: 

````c
  printf("---\n");
  printf("node->isDirty: %c\n", (node->isDirty) ? 'y' : 'n');
  printf("layout->generationCount != gCurrentGenerationCount: %c\n", layout->generationCount != gCurrentGenerationCount ? 'y' : 'n');
  printf("layout->lastParentDirection != parentDirection: %c\n", layout->lastParentDirection != parentDirection ? 'y' : 'n');
 ````

When looking at `gCurrentGenerationCount` it makes me wonder if this could be caused by multiple "root" instances?

**Comment by emilsjolander** [comment]
@roxlu No idea. As I said, step through the code (mainly where you made additions and it does cache / dirty checks) and see what is going on. Try it on the most minimal tree to make it easier.

**Comment by roxlu** [comment]
"step through the code" would be okay if I knew the internals and I had time to learn the codebase which I don't have atm. I'll revisit this issue again when I've got some more time or when it's a bit on your radar too.

**Comment by roxlu** [comment]
@emilsjolander maybe I found what was causing it, but please tell me if this sounds reasonable. I noticed that in `_CSSNodeMarkDirty()` you only traverse upwards when the given node is not dirty. I guess this `isDirty` is set to false somewhere; but this 'somewhere' is not doing that because the node was hidden.  I can fix this by settings `node->isDirty = false` before calling `_CSSNodeMarkDirty(node)` in my `CSSNodeHide()` and `CSSNodeShow()` functions. It seems to work fine now.  

Thanks for your feedback before!

**Comment by woehrl01** [comment]
@roxlu you need to mark the layout as seen (```isDirty = false```), even so you skip the child. 

[here](https://github.com/roxlu/css-layout/blob/38ae7ea4ec31faa9582e452ad32818687a32743e/CSSLayout/CSSLayout.c#L1370) and [here](https://github.com/roxlu/css-layout/blob/38ae7ea4ec31faa9582e452ad32818687a32743e/CSSLayout/CSSLayout.c#L1443).

**Comment by woehrl01** [comment]
@roxlu furthermore, I'd suggest changing boolean ```isVisible``` to an enum ```display```. With ```flex``` and ```none```  as values, where ```flex``` is the default. So that it conforms more with the web. 

e.g. ```CSSNodeStyleSetDisplay(node, CSSDisplayFlex)``` and ```CSSNodeStyleSetDisplay(node, CSSDisplayNone)```

This would simplify test generation.

**Comment by emilsjolander** [comment]
@woehrl01 I like it

**Comment by woehrl01** [comment]
@roxlu for a feature I try to implement externally this would be a handy thing, do you mind if I do a PR ?

**Comment by roxlu** [comment]
Yep of course. Though I would love to see this being integrated here. @emilsjolander shall I do a pull request?

**Comment by emilsjolander** [comment]
Go ahead and create a PR and we can discuss the details further there 👍
