### ISSUE TITLE
How to build and install shared/static libs and headers?

### ISSUE THREAD

**Issue by SirCmpwn** [facebook/yoga#271]
Kind of lost on how to produce libyogacore.{a,so} and install them, along with headers, to a given prefix. Is such a thing possible?

**Comment by SirCmpwn** [comment]
Update: figured out how to build a shared and static library, but not how to install them. Manually?

**Comment by emilsjolander** [comment]
What platform are you trying to build for?

**Comment by SirCmpwn** [comment]
Linux.

**Comment by emilsjolander** [comment]
The headers exist in `yoga/*.h` and to compile a .so/.a file you can run `buck build //:yoga` and find the file in buck-out/ directory.

**Comment by SirCmpwn** [comment]
So yes, they have to be installed manually?

**Comment by emilsjolander** [comment]
Yes if you are not building with buck they have to be installed manually.
