### ISSUE TITLE
Will this work with Xamarin?

### ISSUE THREAD

**Issue by dhaligas** [facebook/yoga#276]
Can this be used with Xamarin iOS / Android?

**Comment by splhack** [comment]
I haven't tested yoga with Xamarin.iOS and Android, but technically, Yes. With Mono on OS X works well, With Unity (Mono 2.x backend) on OS X, Windows and Android works well.

I've created a pull request for that (#277) since Native library should be statically linked for Xamarin.iOS.

**Comment by dhaligas** [comment]
@splhack awesome how about Xamarin.Android?  I would love to see an example as well on both platforms on how to use it.

**Comment by roubachof** [comment]
Nice work for the Xamarin.iOS version 👍 
It would be awesome if we could have a Xamarin.Android version as well.
Cross platform layouting without using Xamarin.Forms: would be a blast :1st_place_medal:

**Comment by emilsjolander** [comment]
@rmarinho @chamons Do any of you know about supporting Xamarin.Android?

**Comment by rmarinho** [comment]
I will work on it..

**Comment by rmarinho** [comment]
@roubachof ahaha

**Comment by emilsjolander** [comment]
@rmarinho Awesome!

**Comment by dhaligas** [comment]
@rmarinho I would also like to see this become a Forms Layout as well
