### ISSUE TITLE
Simple layout string parser

### ISSUE THREAD

**Issue by jimon** [facebook/yoga#279]
More RFC (request-for-comments) than actual issue. Back in the day I was doing a small css parser for older css-layout - https://github.com/jimon/css-micro-parser The main feature was that instead of doing 100500 calls to set node properties you just do something like `SetNodeStyle(node, "right:20; align-self:center;")` and that's it, in some cases it improves readability of code a lot, in some cases not much.

So I'm currently working on moving this small parser to updated version of the library, and was curious if it would be something interesting to get to upstream? Or should it be better as separate thing?

**Comment by emilsjolander** [comment]
I'm interested in more feedback from the community hear! I think it sounds pretty cool, I like the end result of reducing method calls. However I'm also thinking it we might be able to do this in some nice way without string parsing.

**Comment by jimon** [comment]
@emilsjolander awesome! I think would be nice to have both ways, sometimes it's more compact to set the style as a string, and sometimes it's better to have method calls.

I also experimented a bit and came-up that using printf syntax is pretty nice as well, so you write something like `SetNodeStyle(node, "right:%i; align-self:center;", x);`, which in some cases simplify life, but maybe it's a bit of overkill.

**Comment by emilsjolander** [comment]
I would love it if we could find a way to do this nicely using pure C syntax. But I have yet to find a good way to do it. Switching to C++ would give us the ability to do this more nicely.

**Comment by emilsjolander** [comment]
@jimon Maybe something like this?

```c
YGNodeSetStyles(node, {
  YGStyle("height", 100),
  YGStyle("width", 100),
  YGStyle("justify-content", YGJustifyContentCenter),
});
```

**Comment by jimon** [comment]
@emilsjolander sounds good for some cases! Though using already existing css style string notation is shorter and everyone already knows how to use it.

**Comment by emilsjolander** [comment]
I actually think this is better implemented outside of Yoga. I would prefer Yoga to only implement the core library and language bindings and let other libraries / user space code provide these kinds of abstractions.
