### ISSUE TITLE
Use with UIScrollview in iOS

### ISSUE THREAD

**Issue by randomstrings** [facebook/yoga#284]
Just curious how one would go about using Yoga to size a content view larger than the bounds of a UIScrollView in iOS. Adding a content view as a subview to a UIScrollView (both with yg_usesYoga == true) and then calling yg_applyLayout on the UIScrollView seems to size the content view (which needs to be taller) the same height as the UIScrollView. Not really suprising I guess, but just wondering how to get around this with Yoga/flexbox-style layout. Thanks.

**Comment by emilsjolander** [comment]
This should be solved by setting overflow = scroll on the uiscrollview. Seems like this has not been exposed yet in the Obj-c bindings though, Thanks for the heads up! I'll close this issue as I have filed a separate issue to address that problem. https://github.com/facebook/yoga/issues/285

**Comment by happy201993** [comment]
Do you have an example how to use overflow in uiscrollview.
here is my code, uiscrollview cant scroll.
what's wrong with this?
@randomstrings  
@emilsjolander 
```
- (void)testScrollView
{
    UIScrollView *scroll = [UIScrollView new];
    [scroll configureLayoutWithBlock:^(YGLayout * _Nonnull layout) {
        layout.isEnabled = YES;
        layout.width = YGPointValue(375);
        layout.height = YGPointValue(500);
        layout.overflow = YGOverflowScroll;
        layout.alignItems = YGAlignFlexStart;
    }];
    [self.view addSubview:scroll];

    
    UIView *contentView = [UIView new];
    [contentView configureLayoutWithBlock:^(YGLayout * _Nonnull layout) {
        layout.isEnabled = YES;
    }];
    [scroll addSubview:contentView];
    
    
    for (int i = 0; i < 100; i++) {
        UIView *view = [UIView new];
        view.backgroundColor = [UIColor yellowColor];
        CGFloat x = i * 30;
        [view configureLayoutWithBlock:^(YGLayout * _Nonnull layout) {
            layout.isEnabled = YES;
            layout.width = YGPointValue(30);
            layout.height = YGPointValue(30);
            layout.marginLeft = YGPointValue(x);
        }];
        [contentView addSubview:view];
    }
    
    [scroll.yoga  applyLayoutPreservingOrigin:NO];
}
```

**Comment by ZenonHuang** [comment]
@happy201993 

your code is not work for UIScrollView with YogaKit 1.6 .

**Comment by 100mango** [comment]
@happy201993 @randomstrings @emilsjolander same question here. how to auto calculate content size?

**Comment by linqingmo** [comment]
It seems `overflow` dose not support iOS, try this.
```objective-c
[scroll.yoga applyLayoutPreservingOrigin:NO dimensionFlexibility:YGDimensionFlexibilityFlexibleHeight];
scroll.contentSize = scroll.frame.size;
[scroll.yoga  applyLayoutPreservingOrigin:NO];
```
