### ISSUE TITLE
Expose overflow in obj-c API.

### ISSUE THREAD

**Issue by emilsjolander** [facebook/yoga#285]
Need to be able to set overflow to be able to use yoga within a scrolling context. See https://github.com/facebook/yoga/issues/284. This may be able to be solved without explicitly exposing an overflow setting and instead relying on querying the view on wether it is scrollable. @dshahidehpour Can you have a look?

**Comment by dshahidehpour** [comment]
No problem! I'll put up a diff to add it back.

**Comment by randomstrings** [comment]
I wrote some swift bindings for yoga and added a property for overflow which is working now for me. Here's a sample app showing the swift bindings in use (Xcode 8.1, swift 3.0.1). I would be interested to know what you think of this approach to the bindings. Thanks!

sample app:
https://github.com/randomstrings/FitChart

direct link to swift bindings:
https://github.com/randomstrings/FitChart/blob/master/Yoga%2BSwift/Yoga%2BSwift.swift

general usage:
```swift
view.usesYoga = true
view.yogaFlexDirection = .column
view.yogaMarginTop = 5

root.yogaApplyLayout()
```

**Comment by emilsjolander** [comment]
@randomstrings bindings look pretty good. I would move the enums into another file so that they can be generated with `enums.py`

**Comment by randomstrings** [comment]
Ok, I'll take a look at `enums.py`. Do you think these swift bindings are something I should add to Yoga and submit a pull request for? Or would it be better for me to host them as a separate repo? In the case of the former, any advice on how to proceed? Thanks

**Comment by emilsjolander** [comment]
@randomstrings Open an issue or pull request so we can discuss it separately from this issue.

**Comment by randomstrings** [comment]
OK, I opened #287 to discuss.

**Comment by rmarinho** [comment]
This is really needed to make it usable
