### ISSUE TITLE
Integration of swift bindings into repo

### ISSUE THREAD

**Issue by randomstrings** [facebook/yoga#287]
Just wondering how I should approach integrating swift bindings into the repo for the purpose of submitting a pull request. For example, should I create a new swift target in the existing `YogaKitSample.xcodeproj`, so there would be 1 target for obj-c and one for swift? Or should I create a new `YogaKitSwift` directory at the root level alongside the existing `YogaKit` directory? 

Any preferences or guidance would be helpful. I'm new to open source contribution. Thanks

**Comment by emilsjolander** [comment]
Would it be possible to change the obj-c bindings in such a way so the interop better with swift instead? I see a lot of value easily using Yoga from swift but don't see a lot of value writing the bindings in swift if the same could be achieved leveraging existing C or obj-c headers. Maybe making use of https://developer.apple.com/library/content/documentation/Swift/Conceptual/BuildingCocoaApps/InteractingWithCAPIs.html ?

**Comment by emilsjolander** [comment]
@dshahidehpour you might have some valuable input here

**Comment by randomstrings** [comment]
To your question, I'm not sure, but it would be interesting to see.

I was thinking the bindings would be native for each language (e.g. swift for a swift app, objc for an objc app, java for a java app, etc). I think swift developers value native swift bindings (at least I do).

I notice at the root level there are directories for the other languages:

```
csharp
java
YogaKit
```

What if this were made more consistent by changing YogaKit to `objc` and adding `swift`? As in:

```
csharp
java
objc
swift
```

**Comment by randomstrings** [comment]
As an aside, I got the swift enums exporting with `enums.py`:

https://github.com/randomstrings/FitChart/blob/master/Yoga%2BSwift/Yoga%2BSwift%2BEnums.swift

**Comment by emilsjolander** [comment]
@randomstrings If we can get a good API in swift using the C or objc headers then it is less code to maintain which is a clear win. Having the bindings implemented in swift is not a clear win in itself unless it somehow improves the API swift developers interact with.

Changing the top level folder from `YogaKit` -> `objc` should be fine.

**Comment by hartbit** [comment]
Quick input. I'm also very interested by this. I agree with @emilsjolander that it would be better not to have to support two languages for the same platform (iOS). Especially as we can go very far with `CF_SWIFT_NAME` and other compiler hints. The only thing that annoys me about the native enums is that they contain the `count` value that, if I'm not mistaken, is purely an implementation detail that helps enumerating through the values? I would tend to remove it from the bindings.

**Comment by emilsjolander** [comment]
@hartbit yeah count is there because in the C implementation we use the enums for array indexing so we need to count to allocate the array size / loop over the array. I agree it's not great. I'm very open to a better solution.

**Comment by hartbit** [comment]
@randomstrings @emilsjolander If you both don't mind, I'd like to try to improve the Objective-C APIs and make them look good in Swift at the same time. I'll open a Pull Request and you can both comment on it.

**Comment by randomstrings** [comment]
@emilsjolander I take your point, however I'm not sure if I have anything to contribute to this question of the C enums, although I'm happy to help with the swift support in general if I can. Some possible action items:

- providing swift-friendly properties in objc (right now there are setters, but we also need getters and property declarations). This will allow swift code such as `view.yogaHeight = 100`.
- figuring out what to do about the C enums. This is the part I'm not sure of. The swift-friendly NS_ENUM only works at the objc-level, but the enums are declared at the C-level.

**Comment by randomstrings** [comment]
@hartbit That would be great. Let me know if I can help.

**Comment by hartbit** [comment]
@emilsjolander @randomstrings I've opened a pull request #289 and I'd really appreciate some feedback.

**Comment by dshahidehpour** [comment]
We added Swift support with 9982295e
