### ISSUE TITLE
Math.floor operation on MeasureOutput for Java and C#

### ISSUE THREAD

**Issue by rozele** [facebook/yoga#296]
I just wanted to check if this behavior was by-design before I made any PR.  In react-native-windows, we have to do Math.Ceiling on all of our measure function outputs because casting from float/double to int always does a floor operation:

https://github.com/facebook/yoga/blob/master/csharp/Facebook.Yoga/MeasureOutput.cs#L16
https://github.com/facebook/yoga/blob/master/java/com/facebook/yoga/YogaMeasureOutput.java#L18

I imagine this isn't a problem for react-native on Android because they don't encounter fractional pixel dimensions?

**Comment by woehrl01** [comment]
Nice catch! ButI think you should not use any rounding logic as those values are treated as float in the c part.

For Java you should instead use:
```java
  public static long make(float width, float height) {
    return make(Float.floatToIntBits(width), Float.floatToIntBits(height));
  }
```

In C#:
```csharp
        public static long Make(double width, double height)
        {
            int widthInt = BitConverter.ToInt32(BitConverter.GetBytes((float)width), 0);
            int heightInt = BitConverter.ToInt32(BitConverter.GetBytes((float)height), 0);
            return Make((widthInt , heightInt);
        }
```

As this is a little cumbersome on C# maybe its better to use directly a struct with two floats (see [YGSize](https://github.com/facebook/yoga/blob/master/yoga/Yoga.h#L36))

This additionally prevents us from a bug if we calculate a size bigger than 16777216 as this would overflow into the exponent part.

**Comment by woehrl01** [comment]
@emilsjolander Java still needs to be changed/fixed.

**Comment by emilsjolander** [comment]
@woehrl01 putting up a diff now (internally). Thanks for noticing!

**Comment by emilsjolander** [comment]
@woehrl01 putting up an internal diff for java now. thanks!

**Comment by emilsjolander** [comment]
https://github.com/facebook/yoga/commit/352f592767b148747da2d5822f0f4de17eb7b9c2
