### ISSUE TITLE
CLA? And is there some core code not in c I can look at.

### ISSUE THREAD

**Issue by Justinfront** [facebook/yoga#303]
I was wondering why you require the 'CLA' declaration it seems to be against opensource approaches, either it's a BSD3 project or it's not, I wonder does it mean that people will branch to extend but not pull?  Surely it would be better for someone to branch the whole project and then people can contribute directly without corporate ownership rules that probably are not a problem but are no doubt one sided giving only protection to fb. Surely the BSD3 licence is enough to provide suitable protection?

To port code to another language I was wondering if the core functionality is implemented only in c or are the low level parts implemented in a managed typed language as well which might be an easier port - would be greatful if you could point me to the relevant part of the project, I am just curious at the moment.  I have looked at your react stuff and found it a bit bloated no doubt due to the inexpressiveness of javascript as a language and a corporate approach, have a suspicion this is similar, but I like flexbox in javascript it's quite powerful.

**Comment by emilsjolander** [comment]
The core is implemented in C (https://github.com/facebook/yoga/blob/master/yoga/Yoga.c) and other languages are supported through language bindings such as JNI (for java) or P/Invoke (for .NET).
