### ISSUE TITLE
how to generate libyoga.so for android

### ISSUE THREAD

**Issue by Shuijwan** [facebook/yoga#307]
I install buck, and want to build out a libyoga.so and the Java wrapper.
however, It failed to generate the libyoga.so.
1. "buck build //:yoga" will just generate a libyoga.a

2. "buck build //java:jni" will generate a libjni.a

3. "buck build //java:java" will generate java.jar and java-abi.jar, from my understanding, the //java:java build target  depends on jni&yoga, so it should generate both the libyoga.so library and jar file.
Is my understanding correct? should I covert the static library to dynamic library manully?

**Comment by koudle** [comment]
I use " buck build java:jni#default,shared" can generate a libyouga.so,but when I use the so in Android project, it crashed

**Comment by Shuijwan** [comment]
it generate a libyoga.dylib in my mac... do you know how to set the platform?

**Comment by koudle** [comment]
there is a properties "soname" in buck ``soname = 'libyoga.$(ext)'``,maybe you can set ``soname = 'libyoga.so"``
you can see ``https://buckbuild.com/rule/cxx_library.html``,but some properties doesn't work

and I am also very confused

**Comment by Shuijwan** [comment]
Thanks koudle, just set soname to libyoga.so should be wrong,  I saw the LinkMap.txt of libyoga.so, it is still a Mac specific library.
# Object files:
[  0] linker synthesized
[  1] buck-out/gen/java/jni#compile-pic-YGJNI.cpp.o8c77d5e7,default/jni/YGJNI.cpp.o
[  2] buck-out/gen/lib/fb/fbjni#default,shared/liblib_fb_fbjni.dylib
[  3] buck-out/gen/yoga#default,shared/libyogacore.dylib
[  4] /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/lib/libc++.tbd

The so library should be built out through NDK, That's why it crashes.

**Comment by splhack** [comment]
You can use `android-armv7` flavor.

    $ buck build //java:jni#android-armv7,shared
    $ buck targets --show-output //java:jni#android-armv7,shared
    //java:jni#android-armv7,shared buck-out/gen/java/jni#android-armv7,shared/libyoga.so
    $ file buck-out/gen/java/jni#android-armv7,shared/libyoga.so
    buck-out/gen/java/jni#android-armv7,shared/libyoga.so: ELF 32-bit LSB shared object, ARM, EABI5 version 1 (SYSV), dynamically linked, interpreter /system/bin/linker, ..., not stripped

**Comment by Shuijwan** [comment]
@splhack many thanks, it works now.

**Comment by koudle** [comment]
@Shuijwan It works for me,but in my project,the so load failed.How do you solve it?

**Comment by splhack** [comment]
@koudle have you copied all so files?

    buck-out/gen/java/jni#android-armv7,shared/libyoga.so
    buck-out/gen/lib/fb/fbjni#android-armv7,shared/liblib_fb_fbjni.so
    buck-out/gen/yoga#android-armv7,shared/libyogacore.so

**Comment by Shuijwan** [comment]
@koudle also you need copy the libgnustl_shared.so to your jniLibs. it is under /Users/Aaron/Downloads/android-ndk-r13b/sources/cxx-stl/gnu-libstdc++/4.9/libs/armeabi-v7a

**Comment by koudle** [comment]
@splhack I have copied all so files ,and @Shuijwan Shuijwan is right,also need copy the libgnustl_shared.so to  jniLibs,it works now,thanks very much

**Comment by liao123abc** [comment]
@Shuijwan could you share your so files Plz. Currently I'm trying to use it. But, fail to build it(via Windows). Now trying to build it via Linux. But I eager to touch it.
991192001@qq.com
Thx.

**Comment by koudle** [comment]
@liao123abc you can see my github https://github.com/koudle/AndYogaExample,麻烦star一下，thanks

**Comment by mpost** [comment]
Is the libgnustl_shared.so really needed? It is rather large and bloats the final apk when supporting multiple architectures.

**Comment by emilsjolander** [comment]
@mpost not sure.

It is on my todo list to create a sample gradle setup for android and posting it to jcenter / maven central. Just not the highest priority right now.

**Comment by mpost** [comment]
@emilsjolander that would be very handy. Please keep us posted.

**Comment by splhack** [comment]
You can specify C++ runtime in `.buckconfig.local` file. For example,

    [ndk]
      ndk_version = r10e
      app_platform = android-21
      compiler = clang
      cxx_runtime = libcxx

    $ buck build //java:jni#android-armv7,shared
    $ for f in `find buck-out -name "*.so"`; do echo "$f:"; strings $f|grep libc++_shared.so; done
    buck-out/gen/java/jni#android-armv7,shared/libyoga.so:
    libc++_shared.so
    buck-out/gen/lib/fb/fbjni#android-armv7,shared/liblib_fb_fbjni.so:
    libc++_shared.so
    buck-out/gen/yoga#android-armv7,shared/libyogacore.so:
    libc++_shared.so

But unfortunately apparently current buck doesn't have direct support to link C++ runtime statically, like libc++_static

https://github.com/facebook/buck/issues/741

**Comment by Shuijwan** [comment]
Hi @splhack , I check the cxx_binary in https://buckbuild.com/rule/cxx_binary.html, it said use strip-debug or strip-non-global flavors can strip the debug symbols. however when I run it through
buck build //java:jni#android-armv7,strip-debug,shared or
buck build //java:jni#android-armv7,strip-non-global,shared

the generated library is always not stripped.

file buck-out/gen/java/jni#android-armv7\,shared\,strip-non-global/libyoga.so 
buck-out/gen/java/jni#android-armv7,shared,strip-non-global/libyoga.so: ELF 32-bit LSB shared object, ARM, EABI5 version 1 (SYSV), dynamically linked, interpreter /system/bin/linker, BuildID[sha1]=29cf1aa8ddf3258760dfc0eae212427a122f4bb9, not stripped

is this expected result?

**Comment by splhack** [comment]
maybe that feature wasn't implemented yet in buck ndk shared library target. `arm-linux-androideabi-strip -g` instead.

**Comment by Shuijwan** [comment]
@splhack many thanks, it works now.

**Comment by birfincankafein** [comment]
When I try to run 
`buck build //java:jni#android-armv7,shared`
buck says: 

> BUILD FAILED: Unrecognized flavor in target //java:jni#android-armv7,shared while parsing //java/BUCK
> Here are some things you can try to get the following flavors to work::
> android-armv7 : Make sure you have the Android SDK/NDK installed and set up. See https://buckbuild.com/setup/install.html#locate-android-sdk

**Comment by emilsjolander** [comment]
Closing this as we have buck/gradle building these for android in the sample app. jcenter/maven dependencies are being deployed. Expect them early next week.

**Comment by mpost** [comment]
Having it in jcenter will make a lot of people very happy. Thanks for that.

**Comment by fanhongwei** [comment]
@emilsjolander  is jcenter ok ?
