### ISSUE TITLE
Child with MinWidth, Flex and Wrap lays outside of parent boundary

### ISSUE THREAD

**Issue by Jaydee2190** [facebook/yoga#323]
Thanks for an amazing library, I have run into a small issue when using flex wrap and having a single item in a row that has its flex attribute set.  Just before the item wraps there's a point where it's layout is outside the layout container bounds.  I've narrowed it down to layout.computedFlexBasis being 0, and the following line doesn't break...but don't know the inner workings well enough...

    if (sizeConsumedOnCurrentLine + outerFlexBasis > availableInnerMainDim && isNodeFlexWrap &&
            itemsOnLine > 0) {
          break;
        }

The assertion will happen when i (the width) is 119... In which case the item being laid out will have a left of 119 and a width of 20, putting it out of bounds... (It does get worse when the width is 110, the Right will be at 130.  This is because i've set a minimum width).

I hope my test code is enough to demonstrate the problem, and if i'm making some wrong assumption, please correct me!  (If there is no minimum width there isn't an issue, its the minimum width that's pushing it outside the bounds.)

            YGNodeRef container=YGNodeNew();
            YGNodeStyleSetFlexDirection(container,YGFlexDirectionRow);
            YGNodeStyleSetFlexWrap(container, YGWrapWrap);
            
            YGNodeRef itemA=YGNodeNew();
            YGNodeStyleSetWidth(itemA, 100.f);
            YGNodeStyleSetHeight(itemA,25.f);
            YGNodeInsertChild(container, itemA, 0);
            
            YGNodeRef itemB=YGNodeNew();
            YGNodeStyleSetWidth(itemB, 100.f);
            YGNodeStyleSetHeight(itemB,25.f);
            YGNodeStyleSetMinWidth(itemB, 20.f);
            YGNodeStyleSetFlex(itemB, 1.f);
            
            YGNodeInsertChild(container, itemB, 1);
            
            for (int i=200;--i>=50;)
            {
                YGNodeCalculateLayout(container, i, 200.f, YGDirectionLTR);
                printf("Width:%d - (Flex Item B Left:%f Top:%f Width:%f Height:%f)\n",i,YGNodeLayoutGetLeft(itemB),YGNodeLayoutGetTop(itemB),YGNodeLayoutGetWidth(itemB),YGNodeLayoutGetHeight(itemB));
                // will assert from 119-100
                assert(YGNodeLayoutGetLeft(itemB)+YGNodeLayoutGetWidth(itemB) <=i);
                // assert(YGNodeLayoutGetRight(itemB) <=i); // doesn't work GetRight == 0
            }

**Comment by emilsjolander** [comment]
@Jaydee2190 Thanks for reporting this! Could you provide a test fixture (https://github.com/facebook/yoga/tree/master/gentest/fixtures) which demonstrates this bug? We prefer using test fixtures for these bugs as they validate the correct behavior using the browser.

**Comment by woehrl01** [comment]
Looks like #262

**Comment by Jaydee2190** [comment]
@woehrl01 yes, sorry, somehow I missed your issue when I browsed through.  It is the same problem. I'll close this issue.

**Comment by YZhongBin** [comment]
I have  the same problem . how to solve this problem.  My code
<com.facebook.yoga.android.YogaLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    xmlns:yoga="http://schemas.android.com/apk/res-auto"
    android:id="@+id/root"
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    yoga:yg_flexDirection="column"
    yoga:yg_alignContent="center"
    yoga:yg_wrap = "wrap"
    yoga:yg_paddingRight = "1dp"
    yoga:yg_paddingLeft = "1dp"
    yoga:yg_paddingTop = "1dp"
    yoga:yg_paddingBottom = "1dp"
    >
