### ISSUE TITLE
what is the mean of YGEdge 

### ISSUE THREAD

**Issue by rogerjiang** [facebook/yoga#325]
I had some problems that I can not understand;
yoga define the YGEdge
1) what is the meaning of the YGComputedEdgeValue mean.
2) what is the difference between the YGEdgeLeft And YGEdgeStart And YGEdgeHorizontal. the real meaning of  the different param.

**Comment by emilsjolander** [comment]
`YGComputedEdgeValue` is a function which resolves the value of a YGEdge taking aliases such as `YGEdgeHorizontal` into account. `YGEdgeStart` indicates the starting edge of a node. In left-to-right layout mode this is the same as `YGEdgeLeft` but in right-to-left mode it is the same as `YGEdgeRight`.
