### ISSUE TITLE
Content box

### ISSUE THREAD

**Issue by arcanis** [facebook/yoga#326]
Now that percent unit support has been added to the library, I was wondering if you've considered exposing the content box on top of the element box. What do you think? It currently seems hard to know the exact size of the padding inside the box.

**Comment by emilsjolander** [comment]
I would prefer to only support border-box sizing. Can you give an example of what is hard the achieve with the current model?

**Comment by arcanis** [comment]
Oh, sure, I completely agree with using border-box. My point was that because units can now be percents, some values need to be resolved one way or the other to be added or substracted to others. For example, let's say I want to get the content width of an element like this:

```
<div style="width: 500px; padding-left: 5%; padding-right: 10%;" />
```

I currently need to apply the resolve logic myself:

```
let contentWidth = myDiv.getComputedWidth();
contentWidth -= myDiv.getPadding(EDGE_LEFT).value / myDiv.getParent().getComputedWidth() * 100;
contentWidth -= myDiv.getPadding(EDGE_RIGHT).value / myDiv.getParent().getComputedWidth() * 100;
```

Which means that I have to embed some layout logic inside my code (thankfully, most of those relative properties all depends on the parent *width*, otherwise it would have required extra steps to detect whether we should use the parent width or height).

To give you a better idea of what I mean, I've run some experiments by adding the following code in `entry-common.js`, and found it quite useful (it also automatically resolve EDGE_HORIZONTAL into EDGE_LEFT + EDGE_RIGHT, and EDGE_VERTICAL into EDGE_TOP + EDGE_BOTTOM):

```javascript
for (let fnName of [ `Margin`, `Border`, `Padding` ]) {

	let method = lib.Node.prototype[`get${fnName}`];

	if (method == null)
		throw new Error(`Assertion failed; get${fnName} seems meesing`);

	patch(lib.Node.prototype, `getComputed${fnName}`, function getComputed(_, edge) {

		if (edge === constants.EDGE_HORIZONTAL)
			return getComputed.call(this, _, constants.EDGE_LEFT) + getComputed.call(this, _, constants.EDGE_RIGHT);

		if (edge === constants.EDGE_VERTICAL)
			return getComputed.call(this, _, constants.EDGE_TOP) + getComputed.call(this, _, constants.EDGE_BOTTOM);

		let value = method.call(this, edge);

		if (typeof value === `number`)
			return value;

		switch (value.unit) {

			case constants.UNIT_UNDEFINED: {
				return constants.UNDEFINED;
			} break;

			case constants.UNIT_PIXEL: {
				return value.value;
			} break;

			case constants.UNIT_PERCENT: {
				let relativeSize = this.getParent() ? this.getParent().getWidth() : 0;
				return value.value * relativeSize / 100;
			} break;

		}

	});

}
```

**Comment by emilsjolander** [comment]
Ah ok this has recently been added to the C version. Seems like the javascript wrapper is missing just 👍  https://github.com/facebook/yoga/blob/master/yoga/Yoga.h#L200 gets the computed layout padding after calculation.

**Comment by emilsjolander** [comment]
@arcanis does this look like what you need?

**Comment by arcanis** [comment]
Sounds like it! 👍 How would you feel about adding border & margin counterparts, and the EDGE_HORIZONTAL & EDGE_VERTICAL support? Can I open a PR with these changes?

**Comment by emilsjolander** [comment]
I would be fine with border and margin support. I'm not sure about EDGE_HORIZONTAL & EDGE_VERTICAL support as i'm not certain what that would mean? If you get the horizontal padding of a node with 5 in left padding but 10 in right padding then what should it return?

**Comment by arcanis** [comment]
It would return 15, the sum of left + right. So computing the content width would work like this:

```js
let contentWidth = node.getComputedWidth();
contentWidth -= node.getComputedBorder(EDGE_HORIZONTAL);
contentWidth -= node.getComputedPadding(EDGE_HORIZONTAL);
```

Instead of:

```js
let contentWidth = node.getComputedWidth();
contentWidth -= node.getComputedBorder(EDGE_LEFT);
contentWidth -= node.getComputedBorder(EDGE_RIGHT);
contentWidth -= node.getComputedPadding(EDGE_LEFT);
contentWidth -= node.getComputedPadding(EDGE_RIGHT);
```

**Comment by emilsjolander** [comment]
I don't think we should add that as it works differently than setting horizontal padding (setMargin(EDGE_HORIZONTAL, 10) sets 10 on both sides) and it is easy enough to get left and right and add them together 👍 .

**Comment by arcanis** [comment]
Ok :) How do you feel about implementing `YGNodeGetBorder` if we don't support additional edge values? Because the borders are unitless, it would just be an alias to `YGStyleGetBorder`. I think that this alias should be implemented, because even if those functions have the same return value they won't have the same semantic. What do you think?

**Comment by emilsjolander** [comment]
@arcanis I agree. Please split it up in two PRs though.
