### ISSUE TITLE
How to use yago layout in android activity layout?

### ISSUE THREAD

**Issue by coolstateless** [facebook/yoga#330]

**Comment by coolstateless** [comment]
YogaNode root = new YogaNode();
root.setWidth(500);
root.setHeight(300);
root.setAlignItems(CENTER);
root.setJustifyContent(CENTER);
root.setPadding(ALL, 20);
YogaNode text = new YogaNode();
text.setWidth(200);
text.setHeight(25);

YogaNode image = new YogaNode();
image.setWidth(50);
image.setHeight(50);
image.setPositionType(ABSOLUTE);
image.setPosition(END, 20);
image.setPosition(TOP, 20);

root.addChildAt(text, 0);
root.addChildAt(image, 1);

but,how to use root into android activity layout? thanks

**Comment by emilsjolander** [comment]
call `root.calculateLayout()` and the use the `node.getLayout*()` methods to query the nodes positions. These can then be set on android views. There is currently no wrapper integrating android views with Yoga automatically.

**Comment by coolstateless** [comment]
but , i think that yoga is not usefull for android，i use android view‘ attribute set on android view,than this is more easy?

**Comment by coolstateless** [comment]
but , i think that yoga is not usefull for android，i use android view‘ attribute set on android view,than is this  more easy?
