### ISSUE TITLE
Nuget for csharp

### ISSUE THREAD

**Issue by rmarinho** [facebook/yoga#333]
There's already some nuget files for Windows, i wanted to work in same for iOS and Mac. 

There's a issue related with this, we need to build this on Windows and OSX. Can you provide CI to do that? If so can we start discuss a plan for how it will work?! where each build will publish artifacts etc .. And if we have preference in what OS we are going to build the nuget.

**Comment by emilsjolander** [comment]
We have travis set up already. Will that work?

**Comment by emilsjolander** [comment]
@rmarinho what is needed for this? We have recently deployed Yoga to both npm and cocoapods, would love to also add it to NuGet.

**Comment by rmarinho** [comment]
@emilsjolander sorry i m being busy with other subject and didn't got back to Yoga last week. 

Well , i think the idea is one would need to build the solution on a windows machine with visual studio, publish the artifacts of that build, then build the xamarin iOS and android solutions on a mac, then pack the artifacts of windows, iOS and android in 1 nuget. 

So basically everything is in place (windows, android and iOS bits are already in), we just need to start configuring the builds on CI.

**Comment by emilsjolander** [comment]
Ok sounds good. Not sure we want to do this on CI although i'm open to discuss that. We do manual pushes for the other package managers. Doing it all in CI could be nice though.

**Comment by rmarinho** [comment]
@splhack we are missing build of i386 for iOS and Mac .. can you update buck and the fat library to support it?

**Comment by splhack** [comment]
sure. #391

**Comment by aloisdeniel** [comment]
Additionally, is a dedicated Nuget for the YogaKit (iOS) binding planned ?

**Comment by rmarinho** [comment]
@aloisdeniel i started some work (a Xamarin iOS c# port) not really a iOS binding.. but didn't follow up.. i wonder if we should do that here in a different repo.

**Comment by joltmode** [comment]
What is the status of this one?

I see that NuGet has two packages:
- https://www.nuget.org/packages/Facebook.Yoga/ (1.5.0-pre1 being latest)
- https://www.nuget.org/packages/Facebook.Yoga.Native/ (1.0.2-pre being latest)

So both are actually outdated, given that the latest release is 1.18.0 (https://github.com/facebook/yoga/releases/tag/1.18.0).

The 1.5.0 actually happens to be 3 years old. 😮

**Comment by emilsjolander** [comment]
I’m no longer working on Yoga but perhaps @passy can take over this conversation

**Comment by IceReaper** [comment]
To get around this i made https://www.nuget.org/packages/IceReaper.YogaSharp/ with its source under https://github.com/IceReaper/YogaSharp for usage on OpenRA https://github.com/OpenRA/OpenRA/pull/18151 which properly works as seen in this test project https://github.com/IceReaper/YogaTest however a proper official nuget package would be realy nice to see!

**Comment by NickGerleman** [comment]
The C# bindings have not had a dedicated maintainer. We are removing them from the repo as part of cleanup for the next OSS release of Yoga.
