### ISSUE TITLE
Invalid LayoutX/LayoutY for nested flex nodes

### ISSUE THREAD

**Issue by Kasu** [facebook/yoga#342]
The `container` node in the example below flexes correctly to dock into the padding of the `root` node. The `container` node ends up with the valid bounds `x=25, y=25, w=450, h=250`. The problem occurs when i add the next flex node `top` inside `container`. The `top` node seems to lose its `LayoutX` and `LayoutY` values entirely (while `LayoutWidth` and `LayoutHeight` is correct):

![image](https://cloud.githubusercontent.com/assets/805006/22032937/cf9e75fc-dce6-11e6-9b88-2275a4eb2421.png)

Is this a bug or am I doing something wrong?

EDIT: Here's a jsfiddle demonstrating the same structure using web flexbox: https://jsfiddle.net/0qqcjyjm/

**Comment by woehrl01** [comment]
@Kasu LaxoutX and LayoutY is relative to it's parent. As in your example container has no padding. Top has no additional LaxoutX or LayoutY besides the values the container has.

**Comment by Kasu** [comment]
@woehrl01 `container` has no padding, indeed, but it has the bounds `x=25, y=25, w=450, h=250` because it is shrunk by the padding of `root`. Which means that `top` should also be positioned at `x=25, y=25`.

**Comment by woehrl01** [comment]
@Kasu no, as it inherits the position from it's parent. LayoutX and LayoutY are relative values. The values you expect would be the absolute ones. Simply add all the values from each nodes parents.

**Comment by Kasu** [comment]
@woehrl01 Oh, I see. My mistake then! Thanks for clearing that up for me :)
