### ISSUE TITLE
Why isn't it published on npm/yarn registry?

### ISSUE THREAD

**Issue by aniddan** [facebook/yoga#343]
Can't find the yoga-layout package.

**Comment by nwlieb** [comment]
If there is work to be done I'd be glad to help out. Having yoga in the npm registry would simplify our build considerably.

**Comment by abhishiv** [comment]
Does anyone know a workaround in the meantime?

**Comment by nwlieb** [comment]
@abhishiv 
The recommended solution in their [documentation](https://facebook.github.io/yoga/docs/getting-started/) is: 

> For now we recommend including Yoga as a git submodule in your project. Once done, you can either build Yoga using Buck (detailed below) or integrate it into your existing build system by including the C library from the root yoga directory as well as the language bindings (e.g., Java, C#) you wish to use.

**Comment by arcanis** [comment]
I think the easiest workaround in the meantime is to add emscripten inside your PATH, clone the repository somewhere, run `npm run build:all && npm link` from the `javascript` directory, and `npm link yoga-layout` inside your application (possible in the postinstall script).

**Comment by arcanis** [comment]
Another alternative is to use [`@arcanis/npm-git-install`](https://github.com/arcanis/npm-git-install/).

Once added to your package.json dependencies, add the following:

```
{
    "scripts": {
        "install": "npm-git install --verbose"
    },
    "gitDependencies": {
        "yoga-layout": "git@github.com:facebook/yoga?/javascript"
    }
}
```

Still a bit experimental, but a lot more easy.

**Comment by emilsjolander** [comment]
I've now published this https://www.npmjs.com/package/yoga-layout

**Comment by jaladankisuresh** [comment]
I seem to be getting bunch of errors when trying to install this package. I tried it on windows 10 environment

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "--" "run" "build:node"
npm ERR! node v7.0.0
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE
npm ERR! yoga-layout@1.2.0 build:node: `npm -- run copy-sources && npm -- run node-gyp configure build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the yoga-layout@1.2.0 build:node script 'npm -- run copy-sources && npm -- run node-gyp configure build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the yoga-layout package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm -- run copy-sources && npm -- run node-gyp configure build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs yoga-layout
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls yoga-layout
npm ERR! There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! Please include the following file with any support request:
npm ERR!     C:\JVS\Projects\NodeProjects\postcards\node_modules\yoga-layout\npm-debug.log
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN postcards@0.0.1 No repository field.
npm WARN postcards@0.0.1 No license field.
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "yoga-layout"
npm ERR! node v7.0.0
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE

npm ERR! yoga-layout@1.2.0 install: `npm -- run autogypi && npm -- run build:node`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the yoga-layout@1.2.0 install script 'npm -- run autogypi && npm -- run build:node'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the yoga-layout package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm -- run autogypi && npm -- run build:node
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs yoga-layout
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls yoga-layout
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\JVS\Projects\NodeProjects\postcards\npm-debug.log

**Comment by arcanis** [comment]
Yep, there's an open issue at #411
