### ISSUE TITLE
flex initial value not compatible with css standards(chrome/firefox at least)

### ISSUE THREAD

**Issue by dolmens** [facebook/yoga#355]
According to this page, which I understand as css *standard*,

https://www.w3.org/TR/css-flexbox-1/#flex-common

`The initial values of the flex components are equivalent to flex: 0 1 auto.`

It means a lot, but simply, that the content would be shrink-ed if the container is not big enough.

like this sample:
https://jsfiddle.net/dolmens/Lgbo1hba/

but the yoga flex's initial value, I tested, is 0 0 auto, cannot grow or shrink by default.

**Comment by emilsjolander** [comment]
This is a known issue. During the conception of the project initial values were chosen that were different from those in the spec. We would want to change this but given the adoption of Yoga it is very hard to change default values at this point. Most likely we will offer a different constructor which uses the default values from the spec at some point.

**Comment by splhack** [comment]
How about having global option like `YGSetNodeDefaultPolicy(YGNodeDefaultPolicyYoga or YGNodeDefaultPolicyW3Spec)`

**Comment by emilsjolander** [comment]
@splhack I want to move away from having global flags as multiple users of Yoga should be able to configure it differently within the same product.

**Comment by emilsjolander** [comment]
Closing this as it is well documented on https://facebook.github.io/yoga/docs/learn-more/. Later this week i'll publish a list of issues which will include incompatibilities with the spec.

**Comment by fcano-uz** [comment]
I was trying to find a reference in the documentation about all the differences between the Yoga and the CSS standards, but I couldn't find it. The link posted above seems dead. If anyone has a good reference, it will be useful if you want to share 😃  thanks!
