### ISSUE TITLE
Adding Building Steps inside Wiki

### ISSUE THREAD

**Issue by birfincankafein** [facebook/yoga#358]
I still cannot find how to build Yoga for Android. I saw  `buck build //java:jni#android-armv7,shared`
but this is not working, also `buck build java:jni#default,shared  ` this is not working on Android too.

**Comment by maxweber** [comment]
Build instructions would be great. I like to use yoga inside a JVM project, therefore a yoga jar inside the central Maven repo would be awesome. But I'm not sure if the JVM is supported or only Android?

I did the following to receive some jars:

`buck targets` revealed the available build targets

There I found `//java:java` and run:

`buck build //java:java`

In the buck-out folder in the root dir of the yoga project I found the following jars:

```
buck-out/bin/lib/infer-annotations/infer-annotations/infer-annotations-temp-abi.jar
buck-out/bin/lib/jsr-305/jsr-305/jsr-305-temp-abi.jar
buck-out/bin/lib/soloader/__uber_classes_soloader#aar_unzip__/classes.jar
buck-out/bin/lib/soloader/__unpack_soloader#aar_unzip__/classes.jar
buck-out/bin/lib/soloader/soloader/soloader-temp-abi.jar
buck-out/gen/java/com/facebook/proguard/annotations/annotations#abi/annotations-abi.jar
buck-out/gen/java/com/facebook/proguard/annotations/lib__annotations__output/annotations-abi.jar
buck-out/gen/java/com/facebook/proguard/annotations/lib__annotations__output/annotations.jar
buck-out/gen/java/lib__java__output/java-abi.jar
buck-out/gen/java/lib__java__output/java.jar
buck-out/gen/lib/infer-annotations/__infer-annotations-jar__/infer-annotations-1.4.jar
buck-out/gen/lib/infer-annotations/infer-annotations-jar#abi/infer-annotations-jar-abi.jar
buck-out/gen/lib/infer-annotations/infer-annotations-jar-abi.jar
buck-out/gen/lib/infer-annotations/lib__infer-annotations__output/infer-annotations-abi.jar
buck-out/gen/lib/jsr-305/__jsr305-jar__/jsr305.jar
buck-out/gen/lib/jsr-305/jsr305-jar#abi/jsr305-jar-abi.jar
buck-out/gen/lib/jsr-305/jsr305-jar-abi.jar
buck-out/gen/lib/jsr-305/lib__jsr-305__output/jsr-305-abi.jar
buck-out/gen/lib/soloader/__soloader#aar_prebuilt_jar__/classes.jar
buck-out/gen/lib/soloader/lib__soloader__output/soloader-abi.jar
buck-out/gen/lib/soloader/soloader#aar_prebuilt_jar-abi.jar
buck-out/gen/lib/soloader/soloader#abi/soloader-abi.jar
```
But I have no clue how to assemble / use the jars above inside a Java project. Facebook's soloader also seems to be Android specific?

**Comment by birfincankafein** [comment]
Java is okay for me. Im developing Android application with yoga and  I will try to automate my build process for updates. I want to build Yoga, YogaCore and Lib_FB_Yoga for android but everytime it fails. I tried with Buck command and it says there is no flavor like this, however on previous issues related with Android build they all said run this buck command.

**Comment by emilsjolander** [comment]
We are working on getting yoga available via gradle which should improve your situation. https://github.com/facebook/yoga/tree/master/android is where we are working on our android support.

**Comment by birfincankafein** [comment]
Thank you for bringing Android support for Yoga. And also looks like you support gradle build too.
