### ISSUE TITLE
NDK Support Version

### ISSUE THREAD

**Issue by birfincankafein** [facebook/yoga#359]
Is there any minimum ndk limitation on Yoga for java? Because I'm getting this error: 
`java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "_ZTISt16nested_exception" referenced by "/data/app/io.smartface.SmartfaceApp-1/lib/arm/liblib_fb_fbjni.so"...`

**Comment by emilsjolander** [comment]
Not sure. What version are you using?

**Comment by birfincankafein** [comment]
Im using ndk r11b

**Comment by NickGerleman** [comment]
It looks like this issue is stale. Please reopen if you see the same behavior on the latest version of Yoga.
