### ISSUE TITLE
YogaKit not getting recognised in xcode 8.2.1 in a framework project

### ISSUE THREAD

**Issue by AF-Kanishka** [facebook/yoga#363]
Hi,

I have copied all the resources and have added them as compile time dependency in the framework project build phase. But the compiler is not able to recognise yoga when I try view.yoga anywhere in the project. 

I am able to navigate to the yoga class through "Jump to definition" though. 

Please help me.

**Comment by dshahidehpour** [comment]
Hi @AF-Kanishka, we are going to need way more information.

- Did you add YogaKit via Cocoapods?
- Is your code on a branch somewhere that we could clone it and repro?

**Comment by dshahidehpour** [comment]
Please reopen with the issue template filled-out!

**Comment by AF-Kanishka** [comment]
Hi @dshahidehpour ,

I didn't add yoga via cocoapods as I was told that it will increase the framework size. I just copied the files and added the headers in the build phase just like the Demo. Please suggest me a better way if you know any.

You can find the code in this repo https://github.com/AF-Kanishka/yoga-test. Unfortunately, it is not working in the project's view controller either.

**Comment by AF-Kanishka** [comment]
I can't reopen the issue :/
