### ISSUE TITLE
YogaEdge.ALL causes YogaCore crash in Java

### ISSUE THREAD

**Issue by birfincankafein** [facebook/yoga#372]
# Report

I searched issues and this issue didn't reported before. This issue occurred in Java.

# Issues and Steps to Reproduce
***Replaces this with steps to repro your issue.***

# Expected Behavior
When I set border. padding or margin with YogaEdge.ALL, I want to get this value with YogaEdge.ALL. Even if I set any other YogaEdge like YogaEdge.BOTTOM and when I try to get YogaEdge.ALL it must return value like YogaValue.UNDEFINED which is identical. 

# Actual Behavior
When i try to get border. padding or margin with YogaEdge.ALL core crashing with message below. 

#CrashLog
`YG-layout: Cannot get computed value of multi-edge shorthands`

**Comment by emilsjolander** [comment]
This is being fixed. The commit should be landing today. Thanks for the report!

**Comment by birfincankafein** [comment]
Thank you for fixing.
