### ISSUE TITLE
Xamarin.Forms Layout

### ISSUE THREAD

**Issue by dhaligas** [facebook/yoga#373]
I would like to see this implemented as a Xamarin.Forms layout.   Any plans to add this?

@rmarinho @splhack

**Comment by rmarinho** [comment]
I m looking at it.. no luck yet still working on getting CI and Nugets out for OSX and Windows

**Comment by dhaligas** [comment]
@rmarinho could this be a fast layout option?

**Comment by rmarinho** [comment]
That was a easy one to see :) 

https://forums.xamarin.com/discussion/88452/css-styling-and-flexbox
