### ISSUE TITLE
Yoga breaks the Android TextView's TextAlignment

### ISSUE THREAD

**Issue by birfincankafein** [facebook/yoga#374]
# Report

- [x] I have searched [existing issues](https://github.com/facebook/yoga/issues) and this is not a duplicate. I know Yoga nor supporting Android fully but as a developer we should able to use Yoga in Android if we can use it for iOS.

# Issues and Steps to Reproduce
Create a node and set node's data with instance of TextView or some class extends TextView. Give height and width to yoga and give Gravity.CENTER to TextView. 

# Expected Behavior
When I give Gravity.CENTER to TextView which is inside YogaNode, I want to see my text centered both horizontally and vertically.

# Actual Behavior
When I give Gravity.CENTER to TextView which is inside YogaNode, Text centered just horizontally. Vertical alignment not working, YogaNode blocks vertical text aligment (Gravity.CENTER for android)

**Comment by emilsjolander** [comment]
Can you post a code sample? Also we are working on android bindings for yoga which will hopefully solve some of these issues https://github.com/facebook/yoga/tree/master/android

**Comment by birfincankafein** [comment]
I tried with your latest commit. Thank you bringing Android support, I appreciated. 
Here is my test code for Center Text alignment. Actually I have suggestion. Android needs onMeasure for aligning text correctly. In YogaLayout, I didn't see any child measurement. I try to call childViews measure method in onMeasure method, alignment worked but it broke something that I couldn't figure out.

`YogaNode button2ViewNode = new YogaNode();
            Button button2View = new Button(getActivity());
            button2View.setBackgroundColor(Color.MAGENTA);
            button2View.setLayoutParams(new YogaLayout.LayoutParams(-1, 300));
            button2View.setText("TEST");
            button2View.setTextColor(getResources().getColor(R.color.children_text));
            button2ViewNode.setFlex(1);
            button2ViewNode.setMargin(YogaEdge.START, 24);
            button2View.setGravity(Gravity.CENTER);
            inner2Layout.addView(button2View, button2ViewNode);`

**Comment by birfincankafein** [comment]
@emilsjolander did you find the issue?

**Comment by birfincankafein** [comment]
I tested it seem like solved, thanks
