### ISSUE TITLE
 how to make the yoga behavior like Html flexbox？ 

### ISSUE THREAD

**Issue by jackyblf** [facebook/yoga#381]
# Report

- [ ] I have searched [existing issues](https://github.com/facebook/yoga/issues) and this is not a duplicate

# Issues and Steps to Reproduce
![layoutparams](https://cloud.githubusercontent.com/assets/16698988/22724584/1f9afa68-ee02-11e6-8b96-e6136eb9c7e9.jpg)

# Expected Behavior              /  Actual Behavior
![html-yoga-layout-compare](https://cloud.githubusercontent.com/assets/16698988/22724625/4f492f3c-ee02-11e6-8914-f02aa0af7698.jpg)

The expected behavior is left in html with flexbox layout
but the yoga behavior is right 
question : how to make the yoga behavior like Html flexbox？

**Comment by woehrl01** [comment]
I am currently working on a pr #368 which tackels most of the justify-content problems. If you could make me a html layout of your design like described on the Readme of this project. I'll have a look.

**Comment by jackyblf** [comment]
@woehrl01 

here is my html file with css：

[fblayouttest.txt](https://github.com/facebook/yoga/files/760035/fblayouttest.txt)

you can download it and change .txt with .html.

**Comment by woehrl01** [comment]
@jackyblf thanks, I'll have a look.

**Comment by woehrl01** [comment]
@jackyblf @emilsjolander I extracted the following test case:

```html
<div id="justify_content_issue_381" style="display:flex; flex-direction: column; position: relative; margin:0; height:640px; width:740px; overflow:hidden;">
    <div style="display: flex; flex: 1; flex-direction: column; justify-content: space-between;">
        <div style="width: 15px; height : 15px;"></div>
    </div>
    <div style="display: flex; flex: 1; flex-direction: column; justify-content: space-between;">
        <div style="width: 15px; height: 15px;"></div>
        <div style="width: 15px; height: 15px;"></div>
        <div style="width: 15px; height: 15px;"></div>
        <div style="width: 15px; height: 15px;"></div>
        <div style="width: 15px; height: 15px;"></div>
        <div style="width: 15px; height: 15px;"></div>
        <div style="width: 15px; height: 15px;"></div>
        <div style="width: 15px; height: 15px;"></div>
    </div>
</div>
```

in my current PR #368 this is green. ✔️ (if rounding enabled)

**Comment by jackyblf** [comment]
![qq 20170212112814](https://cloud.githubusercontent.com/assets/16698988/22859491/426b85a8-f118-11e6-81d9-e29c3311ca74.gif)

the css flexbox  code above :  fblayouttest.txt
the css version is ok.

but：

![qq 20170212112807](https://cloud.githubusercontent.com/assets/16698988/22859501/a52ea38c-f118-11e6-8b05-a5699e875d66.gif)

the yoga code as follow:
```
/*
//layout as follow:
//rootView        flexDirection = column
//   topView      flexDirection = column flexGrow = 1.0  flexShrink = 1.0 JustifyContent = YGJustifySpaceBetween
//         v1
//   bottomView   flexDirection = column flexGrow = 1.0  flexShrink = 1.0 JustifyContent = YGJustifySpaceBetween
//         v1
//         v2
//         v3
//         v4     width = 15  height = 15 / all v same size
//         v5
//         v6
//         v7
//         v8
*/

UIView2* CreateHtmlViewCopy()
{
	static Color4B color[8] = { Color4B(0,0,0),Color4B(255,0,0),Color4B(0,255,0),Color4B(0,0,255),Color4B(255,255,0),Color4B(255,0,255),Color4B(0,255,255),Color4B(255,255,255) };

	UIView2* pRoot = UICanvas::GetInstance().GetRootUIView2();
	pRoot->yg_setWidth(800);
	pRoot->yg_setHeight(600);

	UIView2* v = NULL;

	//topView
	//    v1
	UIView2* topView = new UIView2("topView", pRoot);
	topView->SetColor(color[3]);
	topView->yg_setFlexGrow(1.0F);
	topView->yg_setFlexShrink(1.0F);
	topView->yg_setJustifyContent(YGJustifySpaceBetween);
	
	UIView2* v = new UIView2("v1", topView);
	v->SetColor(color[0]);
	v->yg_setWidth(15);
	v->yg_setHeight(15);

	//bottomView
	//    with 8 child (size[15,15])
	UIView2* bottomView = new UIView2("bottomView", pRoot);
	bottomView->SetColor(color[1]);
	bottomView->yg_setFlexGrow(1.0F);
	bottomView->yg_setFlexShrink(1.0F);
	bottomView->yg_setJustifyContent(YGJustifySpaceBetween);
	
	for (int i = 0; i < 8; i++)
	{
		v = NULL;
		v = new UIView2("v", bottomView);
		v->SetColor(color[0]);
		v->yg_setWidth(15);
		v->yg_setHeight(15);
	}
	
	pRoot->AttachLayouts();
	pRoot->DebugPrintLayout();
	pRoot->Layout();
	pRoot->PrintInfo();

	return pRoot;
}
```

how to make the yoga behavior like Html flexbox？

**Comment by emilsjolander** [comment]
We are always working on improving the compatibility between yoga's and the various browsers flexbox implementation. I am going to submit individual issues for the currently known problems later this week. Thanks for the report!

**Comment by woehrl01** [comment]
@jackyblf I also think that the problem here is the difference between the default values for the browsers and yoga. As in your example .html those aren't the same. See https://facebook.github.io/yoga/docs/learn-more/#default-values
