### ISSUE TITLE
YogaKit: force recalculate layout on same UIView?

### ISSUE THREAD

**Issue by LeoSchleicher** [facebook/yoga#382]
This is absolutely required when I have i.e. multiline UILabel and want to change its text dynamically. For example, custom UITableViewCell taken from reusable cells pool with flexible height dependent on text.

Now it looks like yoga layout holds previous state and by calling "applyLayout" it uses previously made calculations.

Is it possible to discard these calculations and recalculate all from scratch?

**Comment by woehrl01** [comment]
@LeoSchleicher It only uses the previous values if the nodes aren't marked as dirty. So you need to set the specific elements as dirty and the layout is recalculated. There is still a problem with auto dirtying of nodes, see #350 for reference.

**Comment by LeoSchleicher** [comment]
As fast workaround I found that setting node dirty (on UILabel) after text change helps here. But this method is disabled in code, as usually it cheks if node has custom measure function.

**Comment by LeoSchleicher** [comment]
@woehrl01 You're right. But there must be a way to manually mark node dirty.

**Comment by woehrl01** [comment]
@LeoSchleicher according to the code, it asserts that the node **has** a measure function, so it should work for you. Nodes without a measure function do not need manual dirty flagging.

**Comment by LeoSchleicher** [comment]
@woehrl01 Actually there is no code in YogaKit that sets this measure function. Thus, all nodes are disabled to mark them dirty. I've got this working removing the assertion. It makes node dirty and uses default iOS size calcuation.

For now there is a problem:
1. there is no way to define custom node measure function as YogaKit does not allow it and always uses default iOS size measurement
2. marking node dirty is prohibited by the YogaKit without setting that custom measure function

So, in this case I cannot just use YogaKit as dependency, I do need modify YogaKit code manually and mirror all future changes.

I propose to remove this assertion or open YGNodeMarkDirtyInternal to external use

**Comment by woehrl01** [comment]
@LeoSchleicher Not sure which version of YogaKit you use, but in the current impelementation the custom [measure function is used](https://github.com/facebook/yoga/blob/master/YogaKit/Source/YGLayout.m#L321) to get the size of the iOS controls, this happens automatically for any leaf node the first time you call ```applyLayout```.

**Comment by LeoSchleicher** [comment]
@woehrl01 Hm. Thank you. 

I've just made test project https://github.com/LeoSchleicher/yoga/commit/ad56c23cecfad3a995747ca160d12bc70a42870b slightly modifying YogaKitSample project. It works properly. 

But my another project always stuck with that assertion. I must find what was wrong there.

**Comment by dshahidehpour** [comment]
@LeoSchleicher there is a way to [mark views as dirty](https://github.com/facebook/yoga/blob/master/YogaKit/Source/YGLayout.h#L116). The only constraint is that you can only mark children nodes (UILabel) as dirty.

**Comment by LeoSchleicher** [comment]
@dshahidehpour Many Thanks, but please read above. I stuck with rare problem - I cannot mark view dirty before calling applyLayout() on its hierarchy

**Comment by woehrl01** [comment]
@LeoSchleicher there is no need to mark views dirty before you call ```applyLayout()```.

**Comment by LeoSchleicher** [comment]
Yes, this was an error in my code, but costs me a pair hours :-)

**Comment by dshahidehpour** [comment]
Is there anything left to discuss here? @LeoSchleicher it's an interesting idea to provide a custom measure function to leaf nodes, might be worth adding that functionality if you think it would be helpful!

**Comment by LeoSchleicher** [comment]
@dshahidehpour No, I think my question is already answered. It may be helpful to someone if we add "... or layout was not applied" to assertion message.

**Comment by dshahidehpour** [comment]
@LeoSchleicher sounds good! I'll try and add that info today

**Comment by dangtaikhtn** [comment]
hi @LeoSchleicher , I have a problem, when the height of UICollectionView in UITableViewCell, how can we update the height of UITableViewCell when the height of UICollectionView changed? Can you help me on this?
