### ISSUE TITLE
Buck build broken for c#

### ISSUE THREAD

**Issue by rmarinho** [facebook/yoga#404]
# Report

- [x] I have searched [existing issues](https://github.com/facebook/yoga/issues) and this is not a duplicate

# Issues and Steps to Reproduce
Clone repo and run buck build of csharp targets or build-native.sh

# Expected Behavior
Should run fine

# Actual Behavior
Fails 

# Link to Code
***If you have some code that maintainers can clone/test for themselves, bugs can be resolved much faster. Please paste a link here.***

***When applicable, use this [fiddle](https://jsfiddle.net/emilsjolander/jckmwztt/) to post a web repro.***

**Comment by splhack** [comment]
I'm working on it.

**Comment by rmarinho** [comment]
I had to revert 3 commits that touched .buckconfig and buck file .

**Comment by rmarinho** [comment]
I think is still failing for Android? you need to check the changes of a580712b2f6833070ed4323b54a26805332eb43d

**Comment by splhack** [comment]
which target? `buck build //csharp:yoganet#android-armv7,shared` is fine for me.

**Comment by rmarinho** [comment]
```
iRuiXam-MBP:csharp rmarinho$ buck build //csharp:yoganet#android-x86,shared
Not using buckd because watchman isn't installed.
[-] PROCESSING BUCK FILES...FINISHED 0.0s [100%] 🐳  New buck daemon
[+] DOWNLOADING... (0.00 B/S, TOTAL: 0.00 B, 0 Artifacts)
[+] BUILDING...0.8s
BUILD FAILED: Unrecognized flavor in target //csharp:yoganet#android-x86,shared while parsing //csharp/BUCK
Here are some things you can try to get the following flavors to work::
android-x86 : Make sure you have the Android SDK/NDK installed and set up. See https://buckbuild.com/setup/install.html#locate-android-sdk
```

**Comment by rmarinho** [comment]
if i revert that commit it works.

**Comment by splhack** [comment]
hmm, I can't repro that. Do you have `.buckconfig.local`?

    $ git rev-parse HEAD
    2199a7908d49f4e1e81c32acf4407bbf9e4952ad
    $ git status
    On branch master
    Your branch is up-to-date with 'origin/master'.
    nothing to commit, working directory clean
    
    $ rm -rf buck-out
    $ buck build //csharp:yoganet#android-x86,shared
    [-] PROCESSING BUCK FILES...FINISHED 0.1s [100%]
    [-] DOWNLOADING... (0.00 B/S AVG, TOTAL: 0.00 B, 0 Artifacts)
    [-] BUILDING...FINISHED 5.6s [100%] (10/10 JOBS, 10 UPDATED, 5 [50.0%] CACHE MISS)
