### ISSUE TITLE
"flex: 1" child larger than remaining width in current "flexWrap: wrap" row fails tests

### ISSUE THREAD

**Issue by feichngr** [facebook/yoga#410]
# Report
While fiddling to get some layout to work I build a test fixture with a fixed size `row` direction `wrap`ing container that contains one child that is fixed size and one that has `flex: 1` set and whose content is wider than the remaining width in the row.

# Expected Behavior
Not sure. It's not clear to me how the spec wants this case to be handled.

# Actual Behavior
The generated test fails but weirdly the equivalent html in jsfiddle looks like it matches Yoga's layout.
This _might_ have something to do with the problem stated in #398.

# Link to Code
https://github.com/feichngr/yoga/commit/6335fc65c7a5cdc3f759a31f4cdd0000daaf0c5f
The test `flex_wrap_row_flex_child_exceeds_remaining_width` fails with 
```
====STANDARD OUT====
tests/YGFlexWrapTest.cpp:626: Failure
      Expected: 60
To be equal to: YGNodeLayoutGetHeight(root)
      Which is: 30
```

**Comment by emilsjolander** [comment]
Actually it does behave like chrome. see https://jsfiddle.net/jckmwztt/63/

I'm not sure why the generated test has a different result.

**Comment by emilsjolander** [comment]
This seems to be due to https://github.com/facebook/yoga/issues/427
