### ISSUE TITLE
'System.AccessViolationException' in Facebook.Yoga.dll

### ISSUE THREAD

**Issue by vince-rowe** [facebook/yoga#415]
The app is running fine in simulator by react-native run-windows, but it will not run on a device through Visual Studio 2015 DebugRelease ARM. I have run the packaging command as per the docs.

It seems an issue with Facebook Yoga which is tied in with https://github.com/ReactWindows/react-native-windows, but I think this is the best place to report?

Running facebook.yoga version 1.1.0.18-pre on the ReactNative package (not the app package).

Exception thrown: 'System.AccessViolationException' in Facebook.Yoga.dll
The thread 0x92c has exited with code 0 (0x0).
The thread 0x11d4 has exited with code 0 (0x0).
The thread 0x10cc has exited with code 0 (0x0).
The program '[4644] Name.exe' has exited with code 0 (0x0).

**Edit**
Please note this is trying to run set to ARM for a Windows 10 mobile, not in X64 mode

Any thoughts?
Vince

(I tried to also install via the new npm but I am getting lots of errors:)

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "--" "run" "copy-sources"
npm ERR! node v7.5.0
npm ERR! npm  v4.1.2
npm ERR! code ELIFECYCLE
npm ERR! yoga-layout@1.0.1 copy-sources: `! npm -- run is-monolithic || (rsync -r --checksum --delete ../yoga/ sources/yoga/)`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the yoga-layout@1.0.1 copy-sources script '! npm -- run is-monolithic || (rsync -r --checksum --delete ../yoga/ sources/yoga/)'.
npm ERR! Make sure you have the latest version of node.js and npm installed.

**Comment by rozele** [comment]
:+1: This is a huge blocker for react-native-windows.  I've narrowed down the issue to trying to use YGValue as return value from the P/Invoke API.  E.g., https://github.com/facebook/yoga/blob/37c48257ae300ffbf0f2644a058270224b347f34/csharp/Facebook.Yoga/Native.cs#L364.

**Comment by rmarinho** [comment]
I m not a expert on this, i have requested some help, but someone that can help.. 

Like @rozele said tracked down to the return of the YogaValue struct . 

Any tips are welcome..

**Comment by rmarinho** [comment]
Ok i have a package to test the fix @vince-rowe 

https://www.myget.org/feed/yoga/package/nuget/Facebook.Yoga/1.2.0-pre.3

**Comment by woehrl01** [comment]
Fixed via #459
