### ISSUE TITLE
Getting styles for flex* props should return whatever was passed to the corresponding setter

### ISSUE THREAD

**Issue by emilsjolander** [facebook/yoga#421]
`YGNodeStyleGetFlexShrink()` for example does not always return what was set in `YGNodeStyleSetFlexShrink()`. This is due to these being computed based on the shorthand `flex` property. This should however be more of an implementation detail and a style getter should always return what was passed to the setter.

**Comment by woehrl01** [comment]
I'll give this a go 🔨
