### ISSUE TITLE
Update docs to include cocoapods instructions

### ISSUE THREAD

**Issue by emilsjolander** [facebook/yoga#426]
The docs for iOS bindings have not been updated since cocoapods support was added. Using Yoga via cocoapods is the preferred way so we should ensure to have clear instructions for this.

**Comment by michaeleisel** [comment]
+1

**Comment by michaeleisel** [comment]
The docs imply that cocoapods isn't even supported, and that only Buck is

**Comment by NickGerleman** [comment]
We are deprecating YogaKit as part of the Yoga 2.0 release. We are still going to release a new revision based on the current state of the repo, but won't be accepting new contributions, since we are going to be removing it from the repo after.
