### ISSUE TITLE
Android - YogaLayout not working inside ScrollView

### ISSUE THREAD

**Issue by birfincankafein** [facebook/yoga#435]
# Report

- [x] I have searched [existing issues](https://github.com/facebook/yoga/issues) and this is not a duplicate

# Expected Behavior
YogaLayout inside ScrollView should be visible event I set width.

# Actual Behavior
When you set width to ScrollView node, the content becomes invisible. I checked with Hierarchy Viewer the content has 0 height and 0 width. 

# Link to Code
```
YogaLayout innerLayout = new YogaLayout(getActivity());
innerLayout.setLayoutParams(new YogaLayout.LayoutParams(-1,-1));
innerLayout.setBackgroundColor(Color.RED);

YogaNode scrollViewNode = new YogaNode();
ScrollView scrollView = new ScrollView(getActivity());
scrollView.setBackgroundColor(Color.GREEN);

scrollViewNode.setHeight(250);
scrollViewNode.setWidth(250);
// when you set maxWidth instead of setWidth its working. 

YogaLayout inner1Layout = new YogaLayout(getActivity());
YogaNode inner1LayoutNode = inner1Layout.getYogaNode();
inner1Layout.setBackgroundColor(Color.BLUE);
inner1LayoutNode.setWidth(100);
inner1LayoutNode.setHeight(1000);
scrollView.addView(inner1Layout);
innerLayout.addView(scrollView, scrollViewNode);
innerLayoutNode.calculateLayout(innerLayoutNode.getWidth().value, innerLayoutNode.getHeight().value);

```

**Comment by emilsjolander** [comment]
Thanks for the report! Most likely need to set overflow:scroll on the scrollview node. Possibly a bug in the bindings. Maybe the bindings could even do this on behalf of the user by detecting if it is a scroll container.

**Comment by birfincankafein** [comment]
When you use native container inside YogaLayout, you will face this issue probably. For example I tried SearchView too. It has LinearLayout inside. The content inside LinearLayout not calculated and has 0 height width. I checked them with Hierarchy Viewer.

**Comment by rspencer01** [comment]
This might also be a (lack of) invalidation error.  That is, the root node is measured at size 0,0 and never remeasured.  Are you ever calling `invalidateView`?

**Comment by uziasferreirazup** [comment]
Does someone resolve this problem?

**Comment by NickGerleman** [comment]
We're deprecating the `com.facebook.yoga.android.YogaLayout` ViewGroup in the next major release of Yoga. We intend to still push out a new version aligned to the core Yoga 2.0. I have bulk closed ViewGroup issues to reflect that we are not planning to invest time into functional changes of the ViewGroup. and eventually intend to remove it from the repo.
