### ISSUE TITLE
Calculate smallest possible container size

### ISSUE THREAD

**Issue by fhucho** [facebook/yoga#438]
Is it possible to calculate the smallest possible container size? Basically, something like "wrap content size" or "intrinsic size".

The use case is that I'm trying to create a table view cell in iOS with dynamic height. I'm thinking of overriding `instrinsicContentSize` and returning the smallest possible height there.

**Comment by emilsjolander** [comment]
https://github.com/facebook/yoga/blob/master/YogaKit/Source/YGLayout.h#L102
