### ISSUE TITLE
Move travis builds onto linux machines

### ISSUE THREAD

**Issue by emilsjolander** [facebook/yoga#439]
We can't move all travis builds to linux (js and ios have a strict osx dependency) but the others should be able to be moved and will hopefully significantly speed up Travis run times for pull requests.

**Comment by NickGerleman** [comment]
CI moved from Travis to GitHub Actions and looks to currently be running on ubuntu-latest. https://github.com/facebook/yoga/blob/main/.github/workflows/ci.yml
