### ISSUE TITLE
Add bool config to YGConfig to configure using web defaults

### ISSUE THREAD

**Issue by emilsjolander** [facebook/yoga#445]
Historically Yoga has used other defaults then the web. Changing this now is not really an option as it would break all users of Yoga. However new products and frameworks using Yoga should not be effected by this if they would like to use the web defaults.

I suggest adding a `bool useWebDefaults` field to YGConfig.

**Comment by zcbenz** [comment]
@emilsjolander Is there any discussion on why `useWebDefaults` should be used?

**Comment by woehrl01** [comment]
@zcbenz `useWebDefaults` can be used if you need to port an existing html flexbox layout to Yoga. Without the need to watchout for places where the defaults differ from the web. You can even now (un)set `useWebDefaults` at a subtree level.
