### ISSUE TITLE
Yoga on ARMv6 

### ISSUE THREAD

**Issue by galvesribeiro** [facebook/yoga#460]
Hello guys,

I've beed looking at Yoga and damn, great work!

I saw that it can be used on ARMv7 devices... However, most of IoT devices nowadays use ARMv6 processors and I wonder if there is a way to build Yoga to it as well. Is it possible? Does Yoga uses v7 specific instructions or requires FPU?

Thank you!
Keep the awesome work!

Best regards,

**Comment by splhack** [comment]
It is possible. The Yoga core library is pure C implementation, No assemblers.
It means no v7 specific instructions by the C source code.
And the Yoga core library uses a ton of floating point calculation. So ideally, nice to have hardware FPU but it's not required. We can use soft-float without FPU.

**Comment by galvesribeiro** [comment]
That is a great news! Thanks for quickly reply @splhack 

Is there any instructions to make the Yoga build tools to use our ARMv6l toolchain to build?

We have payment terminals (that machines you swipe your card into it) and they run applications in C# using Mono. Would love to revamp our UI stuff and use Yoga.

Thanks

**Comment by splhack** [comment]
Welcome! It is exciting to hear about a new adventure for Yoga!

We're using buck https://buckbuild.com/ to build a bunch of stuff. But it's not required. You just need to compile these source code for Mono, soft-float ARMv6 ABI using ARMv6l toolchain. (I'm not sure, maybe a shared library for Mono?) We don't have special C compiler macros. The file extension of YGInterop.cpp is `cpp`, but it's just pure C source code.

- The Core library
  - yoga/Yoga.c
  - yoga/YGNodeList.c

- C# interop library
  - csharp/Yoga/YGInterop.cpp

**Comment by galvesribeiro** [comment]
Hummm interesting...

Actually, what we need is to get the `.so` from the build output and we install in the device where `LD_LIBRARY_PATH` is set. All the managed code which does `PInvoke`, should work as is without change. We have other libraries working that way, like for example Skia from Google, which we plan to work together with Yoga. 

Is there any dependencies on Yoga that I also should previously build?

Thanks

**Comment by splhack** [comment]
C# interop library uses vsnprintf, so it depends on libc, just ordinary one.
The Core library depends on, eh, maybe libc, or just C99 compiler. Actually you can override `malloc/calloc/realloc/free` with `YGSetMemoryFuncs`.

**Comment by galvesribeiro** [comment]
OK... I'll have a look at it and report back here what we found. Thank you for the directions @splhack

**Comment by emilsjolander** [comment]
It takes some work tog get buck to compile armv6 but it's fully possible. Otherwise setting up a make file to do it yourself should be pretty easy, not many files for the pure C version.
