### ISSUE TITLE
java.lang.UnsatisfiedLinkError: couldn't find DSO to load: libyoga.so

### ISSUE THREAD

**Issue by jachenry** [facebook/yoga#462]
# Report

- [x] I have searched [existing issues](https://github.com/facebook/yoga/issues) and this is not a duplicate

# Issues and Steps to Reproduce

- `git clone git@github.com:facebook/yoga.git`
- cd yoga
- `buck build //android/sample:sample`
- `buck install --run //android/sample:sample`
- App crashes immediately with error below:

```
java.lang.UnsatisfiedLinkError: couldn't find DSO to load: libyoga.so
```

# Expected Behavior
Sample app to run without a crash

# Actual Behavior
Sample app crashes because it can't find yoga native library

**Comment by rspencer01** [comment]
What architecture are you running on?

**Comment by jachenry** [comment]
I tried running it on my Nexus 5x which runs on Snapdragon 808, 64-bit cpu.

**Comment by rspencer01** [comment]
Is the correct ABI in the .buckconfig under `[ndk]`.  Also, try pulling latest, as we added some recently.  You may also have to update buck as there was a bug with 64bit compilers there.

**Comment by jachenry** [comment]
@rspencer01 the abi was missing from the config but still failed after pulling the latest. I just realized theres now a maven repo I can point to so I'll close this ticket in hopes of not distracting from higher priorities. Thanks for the project and your willingness to explore potential solutions with me. Take care.
