### ISSUE TITLE
[YogaKit][iOS] How can I make the subview lay out in the center of container view?

### ISSUE THREAD

**Issue by frankxzx** [facebook/yoga#465]
I want to make the blue view in the middle of view controller, and what's wrong with my code? 

```
import UIKit
import YogaKit

final class BasicViewController: UIViewController {
    override func viewDidLoad() {
       super.viewDidLoad()
        let containerSize = self.view.bounds.size

        let root = self.view!
        root.backgroundColor = .white
        root.yoga.isEnabled = true
        root.yoga.width = containerSize.width
        root.yoga.height = containerSize.height
        root.yoga.alignItems = .center
        root.yoga.justifyContent = .center

        let child1 = UIView()
        child1.backgroundColor = .blue
        child1.yoga.isEnabled = true
        child1.yoga.width = 50
        child1.yoga.height = 50
        root.addSubview(child1)

        root.yoga.applyLayout(preservingOrigin: true)
    }
}
```
![](http://oha8d9wex.bkt.clouddn.com/1488952534.png )

**Comment by dshahidehpour** [comment]
Hi @frankxzx, I'm not really sure your screenshot reflects your code. Since you set the height and width of the child to 50, there is no way it could look like that, even if it was partially clipped. Here's a video of me copy/pasting your code snippet into the sample project and running it.

![](https://media.giphy.com/media/3og0IOI3ll23tKIIYE/giphy.gif)

**Comment by frankxzx** [comment]
@dshahidehpour sorry for my mistake, and actually the blue view in the snapshot is not in the vertical center, that's confuse me

**Comment by dshahidehpour** [comment]
@frankxzx It's not in the center because your VC needs to do more configuration to tell that view that it can't exist underneath the nav bar. Once you update that code, the view will be centered.

**Comment by frankxzx** [comment]
thanks @dshahidehpour
