### ISSUE TITLE
Don't transfer layout outputs to java if they didn't change

### ISSUE THREAD

**Issue by emilsjolander** [facebook/yoga#483]
When setting layout outputs on a node also set a flag indicating if the layout changed. Read this flag before transferring outputs to java. JNI calls are very expensive so the less of them we need to do the better. Possibly re-use the hasNewLayout flag.

**Comment by ptomasroos** [comment]
Is this the issue for the reverted commit of https://github.com/facebook/yoga/commit/b283572453c588df8a4b0ced5ebe5a50a1bc067f @emilsjolander ? Just trying to track progress waiting for an update in order to be able to ship a release.

**Comment by emilsjolander** [comment]
Not exactly. But it is part of it. Reverted commit will reland this week.

**Comment by ptomasroos** [comment]
Thanks for the info @emilsjolander ! Tracking commits into master as well then :)
