### ISSUE TITLE
Justifying Flex-Growing Item with given Aspect Ratio is not correct

### ISSUE THREAD

**Issue by LeoSchleicher** [facebook/yoga#489]
Hi.

Here is my Problem:

https://gist.github.com/LeoSchleicher/d972ca621c54decfba38a161b642984d

I want to center a box both horizontally and vertically within other box, filling all available space, bit preserving aspect ratio (ie zoom photo centered on full screen). It works as expected as I fix box size. But when I set it to flexGrow, it calculates size of box correctly, but looses vertical centering.

I made it with flexDirection=column on parent element, alignItems=center and justifyContent=center.

**Comment by kkirby** [comment]
I see this issue too.
