### ISSUE TITLE
Need a public API to measure the layout

### ISSUE THREAD

**Issue by zcbenz** [facebook/yoga#494]
In GUI frameworks an important concept is called preferred size, which is the best size that an GUI element can fit all its content. However it is quite tricky to implement when using Yoga as layout engine, since it lacks a way to merely measure the layout without actually change the layout.

This is what I have been doing for now:

```c++
float Container::GetPreferredHeightForWidth(float width) const {
  float float_max = std::numeric_limits<float>::max();
  YGLayoutNodeInternal(node(), width, float_max, YGDirectionLTR,
                       YGMeasureModeExactly, YGMeasureModeAtMost, float_max,
                       float_max, false, "GetPreferredHeightForWidth");
  return node()->layout.measuredDimensions[YGDimensionHeight];
}
```

Is it possible to make `YGLayoutNodeInternal` a public API, and provide APIs to read `layout.measuredDimensions`? Or is there a better way to do this?

Thanks.

**Comment by woehrl01** [comment]
What I use for this is decoupling the calculation from the applying of the layout. I use something like:

```c

float width = preferedWidth > 0 ? preferedWidth : NaN;
float height = preferedHeight > 0 ? preferedHeight: NaN;

YGNodeCalculateLayout(YGNodeRef node, 
                           width, 
                           height, 
                           YGDirectionLTR);

return Size {
 .height = YGNodeLayoutGetHeight(node),
 .width = YGNodeLayoutGetWidth(node)
};
```

And if you really want to apply this to your ui, I recursivly go done any node and put those values actually on the ui elements. 
Besides some (negligible) unnessesary work inside the libary, this works quite well in my projects.

What would be your concerns doing it this way?

**Comment by woehrl01** [comment]
One main benefit of doing it this way is that only if you perform a layout all the dirty nodes are marked as non dirty. Which means you can mostly avoid unnessesary recalculations of elements inside your tree which aren't affected by your size constraints.

**Comment by zcbenz** [comment]
I didn't know I can pass `NaN` to `YGLayoutNodeInternal`, thanks for helping out!
