### ISSUE TITLE
Web Inconsistency: Node has wrong height and text is clipped

### ISSUE THREAD

**Issue by rigdern** [facebook/yoga#504]
Bug expressed using React Native components:

```
<View style={{"position":"absolute","left":0,"right":0,"alignItems":"flex-start","height":375,"marginTop":20}}>
  <View style={{"overflow":"hidden","justifyContent":"flex-end","height":99}}>
    <View>
      <View style={{"flexGrow":1,"flexShrink":1,"flexDirection":"row","backgroundColor":"steelblue"}}>
        <View>
          <Text>Line One</Text>
          <Text style={{"flexGrow":1,"flexShrink":1}}>Line Two</Text>
        </View>
      </View>
    </View>
    <View style={{"height":22,"width":22,"backgroundColor":"orange"}} />
  </View>
</View>
```

### Expected result

Both lines are visible and the blue box is just tall enough to fit the text (JSFiddle: https://jsfiddle.net/w71q2oc6/1/). This is how it lays out on web and in the version of Yoga that shipped with React Native 0.34.0-rc.0.

![image](https://cloud.githubusercontent.com/assets/199935/24937774/d3aa85a8-1ee7-11e7-95a4-ae3a9b3d6b37.png)

### Actual result

First line is clipped and the blue box is too tall.

![image](https://cloud.githubusercontent.com/assets/199935/24937712/609bfd6c-1ee7-11e7-8839-31ff2e890845.png)

**Comment by luc-dion** [comment]
@rigdern does this PR (https://github.com/facebook/yoga/pull/506) fixed your problem?

**Comment by woehrl01** [comment]
Refixed in #635. If not, please reopen.
