### ISSUE TITLE
yogakit how to make a dynamic tableviewcell?

### ISSUE THREAD

**Issue by hydyy** [facebook/yoga#521]
I do not know how to do it, cell height is always the default 44

**Comment by dshahidehpour** [comment]
Please reopen a issue with some code snippets, or some more information.

**Comment by FarajiMehrdad** [comment]
@dshahidehpour 

I create this custom cell class, but there is an issue with the cell frame height 

actually, the contentView height is correct, but the frame height size does not update and always is 51.



`





     class SingleLabelCollectionCell: UITableViewCell {
    let label: UILabel = UILabel()
    let label2: UILabel = UILabel()
    let label3: UILabel = UILabel()


    required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
        initViews()
    }

    override init(style: UITableViewCellStyle, reuseIdentifier: String?) {
        super.init(style: style, reuseIdentifier: reuseIdentifier)
        initViews()
    }

    func initViews() {



        contentView.configureLayout { (layout) in
            layout.isEnabled = true
            layout.flexDirection = .column
            layout.justifyContent = .center
            layout.alignItems = .center

        }

        contentView.backgroundColor = .cyan


        label.backgroundColor = .red
        label.text = "first"
        label.textAlignment = .center
        label.numberOfLines = 1

        label.configureLayout{layout in
            layout.isEnabled = true
        }


        contentView.addSubview(label)


        label2.backgroundColor = .yellow
        label2.text = "second"
        label2.textAlignment = .center
        label2.numberOfLines = 1

        label2.configureLayout{layout in
            layout.isEnabled = true
            layout.margin = 10
            layout.padding = 10
        }
        contentView.addSubview(label2)



        label3.backgroundColor = .brown
        label3.text = "third"
        label3.textAlignment = .center
        label3.numberOfLines = 1

        label3.configureLayout{layout in
            layout.isEnabled = true
            layout.margin = 10
            layout.padding = 10
        }
        contentView.addSubview(label3)

        let border = UIView(frame: .zero)
        border.backgroundColor = .lightGray
        border.configureLayout { (layout) in
            layout.isEnabled = true
            layout.height = 0.5
            layout.marginHorizontal = 25
        }
        contentView.addSubview(border)



    }


    override func layoutSubviews() {
        super.layoutSubviews()
        contentView.yoga.width = YGValue(self.bounds.width)
        contentView.yoga.applyLayout(preservingOrigin: true, dimensionFlexibility: .flexibleHeigth)

        print("contentView height size is \(self.contentView.frame.height)")
        print("frame  height size is \(self.frame.height) ")

    }
}








`
