### ISSUE TITLE
Remove Rounding from experimental flags

### ISSUE THREAD

**Issue by emilsjolander** [facebook/yoga#526]
Rounding has been used in many products now and I think it is time to turn it on by default and remove the experimental option for it. Now that we have scale factor support I see no reason to not rely on rounding within Yoga.

Speak up if you disagree. We can always make this on by default but introduce a config to turn it off. It should however not be considered experimental.

**Comment by woehrl01** [comment]
There is already an option to turn it of, you simply need to set `scaleFactor = 0`.

**Comment by emilsjolander** [comment]
@woehrl01 oh cool! I didn't think of that 👍

**Comment by woehrl01** [comment]
@emilsjolander Maybe we should discuss if we include #508 from @arcanis, too, before making this a default for everybody?

**Comment by emilsjolander** [comment]
Yup! as long as it all happens within this release it should be fine 👍  I'll spend some time tomorrow merging PRs

**Comment by emilsjolander** [comment]
I'm working on this now 👍
