### ISSUE TITLE
Add `tag` field to facilitate debugging

### ISSUE THREAD

**Issue by rigdern** [facebook/yoga#527]
### Problem

Suppose you are running a large React Native app and one of Yoga's asserts fires. How do you go about diagnosing this? It can be especially challenging if the app code has done something wrong (e.g. [called dirty on a node without a measure function](https://github.com/facebook/react-native/blob/master/ReactAndroid/src/main/java/com/facebook/react/uimanager/BaseViewManager.java) because it's hard to map from a Yoga node back to the app code responsible for creating it.

### Solution

React Native assigns a unique numeric identifier to every view called a "react tag". It would be helpful if Yoga supported a tag field. This would enable React Native to copy the "react tag" into the Yoga "tag" field which would make assertion messages printed by Yoga more meaningful.

With this Yoga feature and [a small feature in the react-devtools](https://github.com/facebook/react-devtools/issues/439), you could trivially determine which JavaScript React component was responsible for generating a problematic Yoga node.

**Comment by emilsjolander** [comment]
Could this be achieved with the context we already have on nodes? We already use this in the measure callback to identify the corresponding RN node.

**Comment by rigdern** [comment]
@emilsjolander Maybe. Do you have any thoughts on how that could be incorporated into the output of the assertions?

**Comment by emilsjolander** [comment]
Yeah we have been toying with the idea of custom assert functions like we have custom logger functions. If we had that then the node could be passed to the assert function and you can access the context from there.

**Comment by rigdern** [comment]
@emilsjolander In order for that to work, one of the arguments to the assert function would have to be a node (Which could be null if the assert is not about a node in particular. Or we could have multiple assert functions depending on whether or not the assert is about a particular node.). Does that sound reasonable to you?

Is there an issue tracking adding custom assert functions? I could close this issue in favor of that one.

**Comment by emilsjolander** [comment]
No issue currently tracking that. Just something we talked about internally recently. I think in most (all?) cases we should have a node we can pass so having one assert function which takes a node (which could be null) seems fine.

**Comment by rigdern** [comment]
Closing in favor of support for custom assert functions (#530).
