### ISSUE TITLE
Add hook for custom assert function implementations

### ISSUE THREAD

**Issue by rigdern** [facebook/yoga#530]
Yoga should support custom assert functions similar to how it supports custom logger functions. This would enable Yoga consumers to do custom work when an assert fires. It's important that the assert function receives the Yoga node as one of its arguments (or null if the assert is not associated with a particular Yoga node).

One use case would be so a consumer could include additional information in an assert message. For example, React Native might want to include the react tag of the problematic view in the Yoga assert message. This would enable developers to map from the problematic Yoga node to the JavaScript React Component that created it.

**Comment by emilsjolander** [comment]
Could potentially be implemented on top of YGLog adding a YGLogLevelFatal. We would need to add a node parameter to the logger function though.

**Comment by woehrl01** [comment]
Implemented. See #531
