### ISSUE TITLE
Implicit declaration of function 'YGConfigSetPointScaleFactor' in YogaKit

### ISSUE THREAD

**Issue by yang152412** [facebook/yoga#540]
# Report

- [ ] I have searched [existing issues](https://github.com/facebook/yoga/issues) and this is not a duplicate

# Issues and Steps to Reproduce
There is a compiling error "Implicit declaration of function 'YGConfigSetPointScaleFactor'" When I execute 'pod install' in 'YogaKit/YogaSample'. So I searched in the workspace,but there is no "YGConfigSetPointScaleFactor"was found .
But i noticed that "pod install" installed the version "1.3.0".but there is  already a "1.4.1"  tag in git tags.
Then i find the problem, it's still dependency version "1.3.0" in YogaKit.podspec file.

spec.platform = :ios
  spec.ios.deployment_target = '7.0'
  spec.ios.frameworks = 'UIKit'

  spec.dependency 'Yoga', '~> 1.3'
  spec.source_files = 'YogaKit/Source/*.{h,m,swift}'

# Expected Behavior
Change " spec.dependency 'Yoga', '~> 1.3' " to "  spec.dependency 'Yoga', '~> 1.4' " in YogaKit.podspec file.

# Actual Behavior
***Describe what actually happened.***

# Link to Code
+ (void)initialize
{
  globalConfig = YGConfigNew();
  YGConfigSetExperimentalFeatureEnabled(globalConfig, YGExperimentalFeatureWebFlexBasis, true);
  YGConfigSetPointScaleFactor(globalConfig, [UIScreen mainScreen].scale);
}

***When applicable, use this [fiddle](https://jsfiddle.net/emilsjolander/jckmwztt/) to post a web repro.***

**Comment by emilsjolander** [comment]
Thanks for reporting. We are releasing 1.5 soon (any day now) and will fix this at the same time.
