### ISSUE TITLE
[Question] [YogaKit] Should applyLayout be called in init or in layoutSubviews?

### ISSUE THREAD

**Issue by grundmanise** [facebook/yoga#541]
In a `UIView` subclass should one call `applyLayout` in `init` or in `layoutSubviews`?
What is the best practice from a performance point of view?

**Comment by luc-dion** [comment]
Hi @grundmanise, a little bit late, but you should definitively call it from layoutSubviews. Yoga is so optimized it won't render flexbox that don't requires it.
