### ISSUE TITLE
AspectRatio overrides fixed Width + Height

### ISSUE THREAD

**Issue by woehrl01** [facebook/yoga#549]
# Issues and Steps to Reproduce

If you have a node with `AspectRatio` set and additionally has both `Width`/`Height`, it uses the `AspectRatio` which could lead to confusion. I think that `Width`/`Height` should have a higher priority. 

Same should be true for `max`- constraints, haven't tested this though, yet.

# Expected Behavior
It should use the provided `Width`/`Height`.

# Actual Behavior
It layouts with the `AspectRatio` constraints.

**Comment by emilsjolander** [comment]
When implementing aspect ratio we made the decision that it should always be respected. The same way you say it is odd that a width / height isn't respected it is the same for aspect ratio.
