### ISSUE TITLE
[YogaKit] IOS Screen rotation doesn't invalidate the layout ok

### ISSUE THREAD

**Issue by Daij-Djan** [facebook/yoga#557]
# Report
IOS Screen rotation doesn't invalidate the layout. The layout is wrong after rotation.
I tested this with the sample app and added an additional applyLayout call in didLayoutSubviews of the VC (see code below)

## to summarize the two issues:
1. layout that gets created in viewDidLoad is different from layoutSubviews
2. layout after rotation to an orientation is different than the layout if vc was opened with the orientation
 
- [x] I have searched [existing issues](https://github.com/facebook/yoga/issues) and this is not a duplicate AFAICS

difference is ~ 1px :)

**Comment by Daij-Djan** [comment]
I forgot to change the container size upon calling applyLayout.
so the view's bounds were ok but the containerSize was still 'old'

		override func viewDidLayoutSubviews() {
			let root = self.view!
			let layout = root.yoga
			
			let newContainerSize = self.view.bounds.size
			let oldContainerSize = CGSize(width: CGFloat(layout.width.value), height: CGFloat(layout.height.value))
			
			if newContainerSize.width != oldContainerSize.width || newContainerSize.height != oldContainerSize.width {
				layout.width = YGValue(newContainerSize.width)
				layout.height = YGValue(newContainerSize.height)
				layout.applyLayout(preservingOrigin: true)
			}
		}

I added this to the sample BUT this results in a different layout then before though....

**Comment by Daij-Djan** [comment]
screenshots to show results

![1_landscape_nore-layout](https://cloud.githubusercontent.com/assets/156799/26278446/066b75c0-3d9b-11e7-8e6a-d79ff372b512.png)
![1_portrait_nore-layout](https://cloud.githubusercontent.com/assets/156799/26278448/0693b27e-3d9b-11e7-88c9-c4d5357b7cdd.png)
![2_landscape_withre-layout](https://cloud.githubusercontent.com/assets/156799/26278447/06918f76-3d9b-11e7-86e6-42b12ab4dce5.png)
![2_portrait_withre-layout](https://cloud.githubusercontent.com/assets/156799/26278449/0696bb2c-3d9b-11e7-840c-38c54d5dc4b3.png)

**Comment by Daij-Djan** [comment]
to summarize the issue:

1. layout that gets created in viewDidLoad is different from layoutSubviews
2. layout after rotation to an orientation is different than the layout if vc was opened with the orientation

**Comment by faimin** [comment]
+1 , I have the same question

**Comment by NickGerleman** [comment]
We are deprecating YogaKit as part of the Yoga 2.0 release. We are still going to release a new revision based on the current state of the repo, but won't be accepting new contributions, since we are going to be removing it from the repo after.
