### ISSUE TITLE
YogaLayout brokes aspect ratio on VideoView Android

### ISSUE THREAD

**Issue by birfincankafein** [facebook/yoga#560]
# Report

- [x] I have searched [existing issues](https://github.com/facebook/yoga/issues) and this is not a duplicate

# Issues and Steps to Reproduce
Add 16:9 video to VideoView inside the YogaLayout.

# Expected Behavior
The content of the videoview should be shown in 16:9 aspect ratio, not stretching.

# Actual Behavior
The content of the videoview stretching to with/height.

As I see the main cause is the EXACT measuring child views. I tried UNSPECIFIED as measure spec, VideoView not stretched. 
And also I think measuring child views inside onLayout method seems like not appropriate for Android.

**Comment by woehrl01** [comment]
That your videoview gets streched, looks like you are either missing `aspectRatio: 1.78` or using `align-self: flex-start`.

Yoga doesn't know that your videoview has a specific aspect ratio set, so you must set it in Yoga itself or disable stretching for the view itself (as the default is `align-items: stretch`).
