### ISSUE TITLE
YogaKit for non-swift iOS projects

### ISSUE THREAD

**Issue by atkit** [facebook/yoga#565]
Currently when YogaKit is installed it brings some swift into project (and for some projects it might be a problem, bundle size for example). 

I propose to bring YogaKit swift extensions as separate podspec or subspec, to give a choice: 
- for pure Obj-C projects use YogaKit Obj-C only
- for mixed or pure Swift Projects to have everything in place
 
```
Installing YogaKit (1.5.0)
[!] Pods written in Swift can only be integrated as frameworks; add `use_frameworks!` to your Podfile or target to opt into using it. The Swift Pod being used is: YogaKit
```

**Comment by NickGerleman** [comment]
It looks like this was resolved by the linked commit.
