### ISSUE TITLE
[React Native] flexWrap has definite issues

### ISSUE THREAD

**Issue by idibidiart** [facebook/yoga#575]
Not sure if this is Yoga related, so feel free to close if it's not, but the wrapping behavior with flexWrap has what seems to be a very strange behavior that cannot be explained away by referring to flexbox spec:

https://github.com/facebook/react-native/issues/8960#issuecomment-307138295

I'll add more examples later, but FYI in case this is am issue with the underlying Yoga layout algorithm

**Comment by idibidiart** [comment]
Here is a separate issue with a Snack (Expo running on web) that reproduces it:

https://github.com/facebook/react-native/issues/14429

I suspect this is a layout framework issue.

**Comment by woehrl01** [comment]
Even so I can reproduce that behaviour in Expo (https://snack.expo.io/S1tFa_Vmb). The layout is calculated correctly with Yoga on the master with the same layout:

```html
<div id="wrap_nodes_test" style="flex-direction: row; flex-wrap: wrap; width: 350px;">
  <div style="margin: 15px; width: 10px;"></div>
  <div style="margin: 15px; width: 10px;"></div>
  <div style="margin: 15px; width: 300px;"></div>
  <div style="margin: 15px; width: 20px; height: 20px;"></div>
</div>
```

As Expo uses RN 0.43 and your issue states that you also use this version, I'd suggest using a more up to date version of RN+Yoga, or even compile one with the latest Yoga version on your own. I would be happy if you could verify if you experience the same problem with the latest yoga revision. As I don't use RN on my own, I can't help you with that.

**Comment by woehrl01** [comment]
@idibidiart I'd like to give a a heads up. I tried this in react native 16 and the layout works as expected there 👍 .
