### ISSUE TITLE
`make` failed with exit code: 2 when build:browser

### ISSUE THREAD

**Issue by csonlai** [facebook/yoga#578]
xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

  CC(target) Release/obj.target/nbind/sources/yoga/YGNodeList.o
/Users/cson/Documents/yoga/flexTest/node_modules/nbind/bin/emcc: line 21: emcc: command not found
make: *** [Release/obj.target/nbind/sources/yoga/YGNodeList.o] Error 127
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Darwin 15.2.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "build" "--asmjs=1"

**Comment by arcanis** [comment]
You need to install emscripten to manually build the asmjs build.

**Comment by NickGerleman** [comment]
Please reopen this issue if you still encounter it on a more recent version of Yoga
