### ISSUE TITLE
Android buttons are displaying above the Absolute YogaLayout

### ISSUE THREAD

**Issue by birfincankafein** [facebook/yoga#581]
# Report

- [x] I have searched [existing issues](https://github.com/facebook/yoga/issues) and this is not a duplicate

# Issues and Steps to Reproduce
Add Button with height with to the yoga layout and give background red for identity. After adding button add absolute position type top, right, bottom, left 0 YogaLayout to the same layout and give background green for identity. 

# Expected Behavior
You expect that absolute layout in front of the button and you shouldn't see button because absolute yoga layout added after the button and its stretching too all layout.

# Actual Behavior
Button visible and absolute yoga layout goes background. The issue exists only for the button. I tested with TextView and seekBar etc. 

# Link to Code
https://pastebin.com/7Tq68hz4

***When applicable, use this [fiddle](https://jsfiddle.net/emilsjolander/jckmwztt/) to post a web repro.***

# Environment
Yoga: 1.3.0
Android: API 25, 24, 23
Devices: Huawei Nexus 6P,  Samsung GT-I9500, Emulator API 23

**Comment by NickGerleman** [comment]
It looks like this issue is stale. Please reopen if you see the same behavior on the latest version of Yoga.
