### ISSUE TITLE
Negative transform value does not work on Huawei phones

### ISSUE THREAD

**Issue by ptomasroos** [facebook/yoga#582]
Since of recently react-native's FlatList view support inverted mode.
See commit https://github.com/facebook/react-native/commit/1d30f833a66c1825c37f41207d702e63afa3d0a5

# Issues and Steps to Reproduce

Using
```
 transform: [{scaleY: -1}]
```

to accomplish inverted effect of a list in this case.

The rendering does not work on Huawei 5c, 8 and probably more for some reason. It renders nothing.

# Expected Behavior
I expect something with transform scaleY to actually get rendered

# Actual Behavior
Empty

**Comment by emilsjolander** [comment]
Yoga does not handle transforms. Please open a React Native issue.

**Comment by ptomasroos** [comment]
My bad thanks @emilsjolander
