### ISSUE TITLE
How to render from C native code ?

### ISSUE THREAD

**Issue by luciancaetano** [facebook/yoga#584]
I'm trying to draw using yoga on android but I can not draw on the screen from the C code I have not found any example that teaches drawing on the screen from native code.

**Comment by woehrl01** [comment]
Yoga is not about rendering it's about calculating a layout which you afterwards can use to draw. You can draw with C on android with NDK and openGL, but this is out of scope of this library.

**Comment by woehrl01** [comment]
You can have a look at this gist from @mochja https://gist.github.com/mochja/c4788a4801885b58c1e38d7fb4c091a9 how you can combine yoga with opengl.

**Comment by luciancaetano** [comment]
Thank you for clarifying
