### ISSUE TITLE
Not centering correct while browser does, runnable code in both

### ISSUE THREAD

**Issue by fxfactorial** [facebook/yoga#586]
This is via ReactNative. 

Goal is to make a top bar with two child elements where first child hugs the left and second child sits in the middle. in HTML it is implemented here and works as intended, 

https://jsfiddle.net/y3fjzae7/7/

However reimplementing this on RN for:

```
react-native --version                                                                   ⏎
react-native-cli: 2.0.1
react-native: 0.45.1
```

With:

```jsx
  <View style={{flexDirection:'row'}}>
    <View style={{flex:1}}><Text>first</Text></View>
    <View style={{flex:1, alignSelf:'flex-start'}}>
      <Text>Second</Text>
    </View>
  </View>
```

Yields this: 
<img width="378" alt="screen shot 2017-06-28 at 1 00 07 pm" src="https://user-images.githubusercontent.com/3036816/27657390-5ec57d9a-5c01-11e7-9434-13382b72090b.png">

Which is clearly not centered

**Comment by woehrl01** [comment]
I'm not sure what you mean, as on chrome 59 it looks pretty much like your RN layout:

![image](https://user-images.githubusercontent.com/2535856/27702263-ca0aef56-5d03-11e7-907a-dfba71c7c89d.png)

Whats your expected layout?

**Comment by fxfactorial** [comment]
Okay you're right: 

https://jsfiddle.net/y3fjzae7/8/

Hmm, sorry for noise. 

I wanted the initial layout desired using only flex.
