### ISSUE TITLE
[JavaScript] Different widths on identical grandchild nodes

### ISSUE THREAD

**Issue by khellste** [facebook/yoga#592]
# Report
See the example code below.  My guess is that this is a rounding error, since the discrepancy doesn't occur when the root node is given a slightly different fixed width or when the root node is not given `justify-content: space-around`.

- [x] I have searched [existing issues](https://github.com/facebook/yoga/issues) and this is not a duplicate

# Issues and Steps to Reproduce
Run the following code in a browser:
```javascript
import * as yoga from "yoga-layout";

const root = yoga.Node.create();
root.setJustifyContent(yoga.JUSTIFY_SPACE_AROUND);
root.setFlexDirection(yoga.FLEX_DIRECTION_ROW);
root.setAlignItems(yoga.ALIGN_FLEX_START);
root.setWidth(200);
root.insertChild(makeChildNode(), 0);
root.insertChild(makeChildNode(), 1);
root.insertChild(makeChildNode(), 2);

function makeChildNode() {
    const node = yoga.Node.create();
    node.setAlignItems(yoga.ALIGN_FLEX_START);
    node.setWidth(50);
    const child = yoga.Node.create();
    child.setMeasureFunc(() => new yoga.Size(1, 1));
    node.insertChild(child, 0);
    return node;
};

root.calculateLayout(yoga.UNDEFINED, yoga.UNDEFINED, yoga.DIRECTION_LTR);
(function printRecursive(node, indent) {
    const {left, top, width, height} = node.getComputedLayout();
    const info = `left:${left} top:${top} width:${width} height:${height}`;
    console.log(indent + info);
    for (let i = 0; i < node.getChildCount(); i++) {
        printRecursive(node.getChild(i), indent + "    ");
    }
})(root, "");
```

# Expected Behavior
All of the leaf nodes have the same dimensions (`1px` by `1px`).
```
left:0 top:0 width:200 height:1
    left:8 top:0 width:50 height:1
        left:0 top:0 width:1 height:1
    left:75 top:0 width:50 height:1
        left:0 top:0 width:1 height:1
    left:142 top:0 width:50 height:1
        left:0 top:0 width:1 height:1
```
# Actual Behavior
Leaf nodes have different dimensions (one is `1px` by `1px`, and two are `2px` by `1px`).
```
left:0 top:0 width:200 height:1
    left:8 top:0 width:50 height:1
        left:0 top:0 width:2 height:1
    left:75 top:0 width:50 height:1
        left:0 top:0 width:1 height:1
    left:142 top:0 width:50 height:1
        left:0 top:0 width:2 height:1
```

# Link to Code
This [fiddle](https://jsfiddle.net/5ubbqhp1/1/) demonstrates the correct behavior in a browser.  To reproduce the bug in Yoga, replace the leaf nodes with custom-measured nodes like in the sample code above.

**Comment by woehrl01** [comment]
This looks like #567 and #580. Do you use the latest master version or npm release? If npm please compile it yourself to asm and try if this issue is resolved on the master head.

**Comment by khellste** [comment]
Thanks for the quick response. I'm using the pre-built asm.js release from
npm. I'll give latest master a try tomorrow and see if the issue is fixed.

**Comment by khellste** [comment]
Hey, just a quick update---I'm having some trouble building master.  Buck seems to make some assumptions about the length of file paths that causes it to not work on Windows.  I'll try again from Linux and see if I can get it working.

**Comment by khellste** [comment]
I figured out how to do the ASM.js build, and the problem is indeed fixed in master.  Thanks.
