### ISSUE TITLE
[OC-yoga]How to set the height of yoga when init view?

### ISSUE THREAD

**Issue by nannanIT** [facebook/yoga#594]
YogaView *yogaView = [[YogaView alloc] initWithFrame:CGRectMake(0, 0, width, YogaHeight)];
so if I set YogaHeight = 0, I will not get the correct result, but I don't  know the exact value of YogaHeight. So what should I do?

**Comment by dshahidehpour** [comment]
You need to explicitly set the height on the `YGLayout` object.
