### ISSUE TITLE
[YogaKit] Views originaly excluded from layout and later added are not correctly displayed

### ISSUE THREAD

**Issue by lucdion** [facebook/yoga#603]
# Report
Using YogaKit, if a view is originally excluded from layout and later added, the layout is not correctly computed. I've modified the YogaKitSample app to demonstrate this issue: https://github.com/luc-dion/yoga/pull/1

- [X] I have searched [existing issues](https://github.com/facebook/yoga/issues) and this is not a duplicate

# Issues and Steps to Reproduce
***Replaces this with steps to repro your issue.***
Before the initial applyLayout(), if a view is first excluded from the layout, and then later included, the computed layout is not correctly updated. The newly included view is not displayed.

# Expected Behavior
***Describe what you expected would happen.***
The new included view should be visible, as in this screenshot
![simulator screen shot jul 17 2017 9 01 52 am](https://user-images.githubusercontent.com/14981341/28269070-af2c2d84-6ace-11e7-8804-4e058b3b5420.png)

# Actual Behavior
***Describe what actually happened.***
The new included view should be visible. Instead this is the obtained result:
![simulator screen shot jul 17 2017 9 01 11 am](https://user-images.githubusercontent.com/14981341/28269078-b5ac538c-6ace-11e7-8651-480336ea4a0a.png)

# Link to Code
https://github.com/luc-dion/yoga/pull/1

**Comment by LeoSchleicher** [comment]
Hello,
I've found similar problem. My view (YogaKit) is included in layout. Later I wish to remove it and recalculate all items. I do isIncludedInLayout=false, then applyLayout to root element, but this causes no layout changes, excluded view doesn't disappear

What method is right if I want to recalculate layouts excluding some of items?

**Comment by woehrl01** [comment]
Setting `isIncludedInLayout=false` isn't invalidating the internals of the yoganode (could be a bug). But what you should be able to use the have a similar behavior is `display: none`.

**Comment by LeoSchleicher** [comment]
You are right! There is display property and it works good. Thank you!

**Comment by luc-dion** [comment]
@LeoSchleicher you're problem is different. In the case of this issue, if the view is initially displayed and later hidden, it works perfectly, but if the view is initially hidden and later shown, the view is not layouted.

**Comment by LeoSchleicher** [comment]
I think it layouted, but invisible, since in first pass red block becomes full width and keeps it by second pass. I've seen already something alike, as I tried to build tabs layout

**Comment by luc-dion** [comment]
@dshahidehpour why did you close this issue, this issue is still relevant? The case of @LeoSchleicher was not related to this issue.

**Comment by dshahidehpour** [comment]
Since it's not related to this issue, I'd rather we reopen a new issue that has a repro.

**Comment by luc-dion** [comment]
@dshahidehpour but the issue report is still relevant, only comments from LeoSchleicher are not related.
The repro are available, they are on the specified branch https://github.com/luc-dion/yoga/pull/1
So why should we close this one and create another identical issue?
Thanks

**Comment by dshahidehpour** [comment]
Ah, thanks for clarifying, @luc-dion!
