### ISSUE TITLE
Android: force recalculate layout

### ISSUE THREAD

**Issue by LeoSchleicher** [facebook/yoga#625]
I have a complex layout built with many YogaLayouts. This is a kind of Graph widget and I will set some layout params dynamically. Firstly layout is rendered automatically, but when I change apropriate YogaNode parameters there is no changes on the screen. So, I muss somehow force to recalculate layouts.

How this can be done with Yoga?

**Comment by uziasferreirazup** [comment]
@LeoSchleicher do you resolve your problem?

**Comment by LeoSchleicher** [comment]
Yes, maybe non-standard way. I use yoga both iOS und Android already many years.

**Comment by uziasferreirazup** [comment]
can you share your solution to resolve this problem in android @LeoSchleicher ?

**Comment by LeoSchleicher** [comment]
My final solution was to use only layout calculations from Yoga. I ended with my own intermediate Library. I've subclassed YogaNodeJNIFinalizer and made a property, that holds a reference to a View. Plus many other properties and methods, inclusive these that do desired layouts recalculations (then apply the dimensions to connected views). 

So, normally I create all my views programmatically, bind them to Activity and create some hooks to recalculate layout positions/dimensions. If you're interested, I can publish this library, but it can take some time, while I must separate it from other stuff.

**Comment by uziasferreirazup** [comment]
if you can share the code will be very helpful, actually I have a problem when I use scroll view with yoga, because they lost the dimensions :(

**Comment by LeoSchleicher** [comment]
They did not lost, they must be recalculated each time when Table Cell is appeared again from "recycled" state, if I understand your Problem correctly.

**Comment by uziasferreirazup** [comment]
Exactly.

**Comment by LeoSchleicher** [comment]
So, I've created an empty repo https://github.com/LeoSchleicher/YLayout 
you can watch it and sometimes I put the classes into it

BTW what minSdkVersion do you use? I switched recently to 21. Earlier versions required some workarounds, exactly by cell view calculations.

**Comment by uziasferreirazup** [comment]
Actually, I using the SDK 19

**Comment by uziasferreirazup** [comment]
@LeoSchleicher  how do you recalculate layout? What function do you call? I try using the function 
`mYogaNode.calculateLayout(YogaConstants.UNDEFINED, YogaConstants.UNDEFINED);`
after changing something but the app crashes x.x

**Comment by LeoSchleicher** [comment]
I've pushed in my repo my library and basic usage example. I hope I push soon an example with TableView, Virtual Yoga Layout and so on. If you wish, you can make an issue in this library.
