### ISSUE TITLE
[Ruby] add bindings for Ruby programming language

### ISSUE THREAD

**Issue by justjake** [facebook/yoga#629]
# Report

I would like to use Yoga in a Ruby project, but there are no existing bindings. Would the Yoga maintainers be interested in a PR that adds such bindings in the form of a Ruby gem in a ./ruby folder?

My approach:

- use a stub Ruby extension (a C program that uses the Ruby C API) to build and load Yoga into memory. There will be 0 lines of custom C code in this extension. 

- implement low-level 1:1 bindings for the functions and types in Yoga.h, using the ffi gem.

- generate as much low-level ffi code as possible using the enums.py script, and by parsing the property definition macros in Yoga.h in a rake (“ruby make”) task. This generated code will all be Ruby. 

- build out a high-level, object-oriented Ruby API on top of the ffi bindings, similar in API to the C# library. 

- Add standard ruby shenanigans like `bundle install` and `bundle exec rspec` into .travis.yml for building and testing the gem

- [x] I have searched [existing issues](https://github.com/facebook/yoga/issues) and this is not a duplicate

# Link to Code

I have some early work on my branch here: https://github.com/justjake/yoga/tree/jake--ruby

**Comment by NickGerleman** [comment]
Community built bindings for Yoga are appreciated, but these would be better owned/maintained by the folks building them.
