### ISSUE TITLE
Compile Yoga to WebAssembly

### ISSUE THREAD

**Issue by abdulhannanali** [facebook/yoga#637]
There's a native NodeJS module and a compilation in ASM.js. I am wondering if it can also be compiled to WASM in order to be used in modern browsers which support WebAssembly. 

Opening this issue since there is no prior discussion on this topic.

**Comment by twop** [comment]
I'm implementing a custom renderer for React and wanted to use yoga (js) to reuse react-native layout/styling system. 

It seems that WebAssembly would be a better fit than asm.js

**Comment by viankakrisna** [comment]
might be interested in https://github.com/vincentriemer/yoga-dom

**Comment by rickbutton** [comment]
Bumping this to ask if the maintainers would be interested in a PR that moves from `nbind` to `embind`, trading a native node extension for a `WebAssembly` module. Would love to submit one if accepted.

I've done so here for the latest version of Yoga, https://github.com/rickbutton/yoga-wasm

**Comment by NickGerleman** [comment]
This is implemented in the repo, should be usable in yoga-wasm-web along with Yoga 2.0 npm release.
