### ISSUE TITLE
Missing defaults in gYGNodeDefaults

### ISSUE THREAD

**Issue by ke5fx** [facebook/yoga#646]
Looks like there's no default entry for style.alignSelf, style.positionType, and possibly other members.  No specific problems since 0=auto (at least for now), just a heads-up in case this wasn't your intent.

**Comment by woehrl01** [comment]
Thank you @ke5fx I'm sure this isn't by intent. At least those default values are covered by the "default tests"

**Comment by woehrl01** [comment]
They are now set, to there default values.
