### ISSUE TITLE
what is the differences between YogaEdge.LEFT&START ,and YogaEdge.RIGHT&END

### ISSUE THREAD

**Issue by Lizz0y** [facebook/yoga#652]
# Report

I'm curious what is the differences between YogaEdge.LEFT&START ,and YogaEdge.RIGHT&END
thx~

**Comment by woehrl01** [comment]
If you have a LTR layout it is the same, but if you have a RTL layout they are swapped. This allows you to define a layout which correctly aligns the elements according to LTR/RTL.

**Comment by Lizz0y** [comment]
one more question , i read the code : 
```
 child->layout.position[leading[mainAxis]] =
      node->layout.measuredDimensions[dim[mainAxis]] -
      child->layout.measuredDimensions[dim[mainAxis]] - YGNodeTrailingBorder(node, mainAxis) -
      YGNodeTrailingMargin(child, mainAxis, width) -
      YGNodeTrailingPosition(child, mainAxis, isMainAxisRow ? width : height);
```

i think the margin and position is same ,since they both mean the dim to the start or to the tail,so what's the difference？

**Comment by woehrl01** [comment]
I think this SO answers your question perfectly: https://stackoverflow.com/q/5256211 no need to repeat :D

**Comment by Lizz0y** [comment]
thx for your answer~!
