### ISSUE TITLE
justify-content: space-evenly

### ISSUE THREAD

**Issue by aj0strow** [facebook/yoga#657]
# Report

- [x] I have searched [existing issues](https://github.com/facebook/yoga/issues) and this is not a duplicate

In the [css flexbox guide](https://css-tricks.com/snippets/css/a-guide-to-flexbox/) it mentions `space-evenly` as an option for pretty grids. 

```
justify-content: space-evenly;
```

It would be really cool to see this in yoga / react native. 

# Issues and Steps to Reproduce

Screen capture:

<img width="723" alt="proof" src="https://user-images.githubusercontent.com/1374327/31510371-894f852a-af52-11e7-9610-07e91087e271.png">

# Expected Behavior

N/A

# Actual Behavior

N/A

# Link to Code

N/A

**Comment by woehrl01** [comment]
Didn't knew this was a thing 😄 . See #658 . Thanks for the hint @aj0strow

**Comment by aj0strow** [comment]
@woehrl01 thank you! my goodness that was fast
