### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by holazollil** [facebook/yoga#667]
# Report

# Issues and Steps to Reproduce
Add   `  compile 'com.facebook.yoga:yoga:1.5.0'` to build.gradle file and sync.

# Expected Behaviour
YogaLayout will be resolved.

# Actual Behavior
The sync is finished succesfully. But I cannot use YogaLayout.
`YogaLayout rootLayout = (YogaLayout) inflater.inflate(
                R.layout.benchmark_fragment,
                container,
                false);`

**Comment by NickGerleman** [comment]
It looks like this issue is stale. Please reopen if you see the same behavior on the latest version of Yoga.
