### ISSUE TITLE
cmake fails

### ISSUE THREAD

**Issue by stuta** [facebook/yoga#675]
# Report

- [x] I have searched [existing issues](https://github.com/facebook/yoga/issues) and this is not a duplicate

# Issues and Steps to Reproduce

in new osx installation:
mkdir build
cd build
cmake ..
->
You have called ADD_LIBRARY for library yogacore without any source files. This typically indicates a problem with your CMakeLists.txt file
-- Configuring done
CMake Error: Cannot determine link language for target "yogacore".
CMake Error: CMake can not determine linker language for target: yogacore

# Expected Behavior

Create working makefiles

# Actual Behavior

make
make[2]: *** No rule to make target `CMakeFiles/yogacore.dir/build'.  Stop.
make[1]: *** [CMakeFiles/yogacore.dir/all] Error 2
make: *** [all] Error 2

# Link to Code

I guess this may have someting to do with changing Yoga.c to Yoga.cpp (why the change?).

**Comment by woehrl01** [comment]
Fixed via #676. Please reopen if you have further issues.
