### ISSUE TITLE
pod install probolem

### ISSUE THREAD

**Issue by yang152412** [facebook/yoga#678]
# Report

- [ ] I have searched [existing issues](https://github.com/facebook/yoga/issues) and this is not a duplicate

# Issues and Steps to Reproduce
I got an error below when i run `pod install` in 'YogaKit/YogaKitExample'

```
Analyzing dependencies
Fetching podspec for `YogaKit` from `../../YogaKit.podspec`
[!] CocoaPods could not find compatible versions for pod "Yoga":
  In snapshot (Podfile.lock):
    Yoga (= 1.7.0)

  In Podfile:
    YogaKit (from `../../YogaKit.podspec`) was resolved to 1.7.0, which depends on
      Yoga (~> 1.7)

None of your spec sources contain a spec satisfying the dependencies: `Yoga (= 1.7.0), Yoga (~> 1.7)`.

You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

Note: as of CocoaPods 1.0, `pod repo update` does not happen on `pod install` by default.

[!] Automatically assigning platform `ios` with version `10.1` on target `YogaKitSample` because no platform was specified. Please specify a platform for this target in your Podfile. See `https://guides.cocoapods.org/syntax/podfile.html#platform`.
```

First I doubt my pod repo was not newest,but `pod search` always return '1.6.0' even I `pod update` or  reinstall the cocoapods. 

So how can I run the new example?

**Comment by iOSleep** [comment]
meet same proble

**Comment by lucdion** [comment]
The Yoga version 1.7.0 hasn't been published to Cocoapods yet. 
Why?

**Comment by ACChe** [comment]
Will add to support SPM?

**Comment by olilarkin** [comment]
same here

**Comment by rimiti** [comment]
Have you tried to remove `Podfile.lock` before `pod install` ?
It's working for me.

**Comment by olilarkin** [comment]
still doesn't work for me i don't have a Podfile.lock. exact same error as OP

**Comment by liaojinxing** [comment]
same here

**Comment by MaheshNandam** [comment]
Thanks @rimiti, Removing podfile.lock works for me.

**Comment by jpcarts23** [comment]
pod update yoga

**Comment by NickGerleman** [comment]
It looks like this issue is stale. Please reopen if you see the same behavior on the latest version of Yoga.
