### ISSUE TITLE
YogaKit spelling error

### ISSUE THREAD

**Issue by djs66256** [facebook/yoga#685]
https://github.com/facebook/yoga/blob/2a103373442a5855d18b6edf75679dad3b54c237/YogaKit/Source/YGLayout.h#L26

`Height` I guess.

**Comment by priteshrnandgaonkar** [comment]
Thanks for the issue, its fixed here https://github.com/facebook/yoga/commit/c7a5e1e2909f30f8c73bf23af9e1a9662b20a459
