### ISSUE TITLE
aspectRatio includes margin

### ISSUE THREAD

**Issue by scisci** [facebook/yoga#686]
Currently the aspectRatio creates margins to satisfy the ratio.

If an element has the following style:
```
{
  aspectRatio: 1,
  marginLeft: 10,
  height: '100%'
}
```

Lets say the height of its container is 100 pts. 

Then the item is rendered with 10 pts left margin, 90 pts width, 90 pts height (and an added 10 pts bottom margin)

One would expect it to render 10pts left margin 100pts width and 100pts height.

**Comment by saarora** [comment]
I am facing the same issue as well.

**Comment by scisci** [comment]
Looks, like this should have been fixed in this commit:

https://github.com/facebook/yoga/commit/7fa4adb0d94f6c4c0e5763fbd03966e101d1535d#diff-11a176ed82523f8dabad8a751ce893ae

But still seeing the error in react native, so maybe RN is not using the latest. Will check.

**Comment by anql** [comment]
I found before the tag v1.7.0, It works fine. The bug reappears on last code.

**Comment by NickGerleman** [comment]
It looks like this issue is stale. Please reopen if you are encountering the same issue.
