### ISSUE TITLE
An exception have been made named : Terminating app due to uncaught exception 'CALayerInvalidGeometry', reason: 'CALayer position contains NaN: [nan nan]'

### ISSUE THREAD

**Issue by ghost** [facebook/yoga#687]
# Report

- [ ] I have searched [existing issues](https://github.com/facebook/yoga/issues) and this is not a duplicate

# Issues and Steps to Reproduce
***Replaces this with steps to repro your issue.***

# Expected Behavior
***Describe what you expected would happen.***

# Actual Behavior
***Describe what actually happened.***

# Link to Code
***If you have some code that maintainers can clone/test for themselves, bugs can be resolved much faster. Please paste a link here.***
The code to result in an exception is here:

       let containerSize = self.view.bounds.size

        let root = self.view!
        root.backgroundColor = .white
        root.configureLayout { (layout) in
            layout.isEnabled = true
            layout.width = YGValue(Float(containerSize.width))
            layout.height = YGValue(Float(containerSize.height - 64))
            layout.alignItems = .center
            layout.justifyContent = .center
        }

        let child1 = UIView()
        child1.backgroundColor = .blue
        child1.configureLayout { (layout) in
            layout.isEnabled = true
            layout.width = YGValue(Float(100))
            layout.height = YGValue(Float(10))
            layout.marginBottom = YGValue(Float(25))
        }
        root.addSubview(child1)

        root.yoga.applyLayout(preservingOrigin: true)
***When applicable, use this [fiddle](https://jsfiddle.net/emilsjolander/jckmwztt/) to post a web repro.***

**Comment by bajtyngier** [comment]
Also experiencing this crash when calling `applyLayoutPreservingOrigin`

**Comment by bajtyngier** [comment]
Downgrading to v1.6 fixes the problem for me.

**Comment by weibel** [comment]
This crash looks a bit like this one in this comment https://github.com/facebook/yoga/issues/290#issuecomment-267966085

**Comment by jasorod** [comment]
I have isolated the breaking change to #609 which was fixed with commit c20f2864abaf5a81dee23139c80801054b73089b #

**Comment by karosLi** [comment]
@bajtyngier Thanks, it fix my issue
