### ISSUE TITLE
pod install YogaKit 1.7 fail

### ISSUE THREAD

**Issue by ZenonHuang** [facebook/yoga#689]
# Issues and Steps to Reproduce
In my Podfile, input code : 
```
  pod 'YogaKit', '~> 1.7'
```
then ,terminal show : 
```
Analyzing dependencies
[!] CocoaPods could not find compatible versions for pod "YogaKit":
  In Podfile:
    YogaKit (~> 1.7)

None of your spec sources contain a spec satisfying the dependency: `YogaKit (~> 1.7)`.
```
# Expected Behavior
I can use version 1.7 of YogaKit

# Link to Code
I try to cocoapods.org search Yoga's version,find Yoga 's version is 1.6 .
[YogaKit](https://cocoapods.org/?q=yoga)

**Comment by faimin** [comment]
the latest version is `1.6`

**Comment by cntrump** [comment]
v1.7 already released on 16 Nov 2017.

**Comment by ZenonHuang** [comment]
Really ? I find [YogaKit](https://cocoapods.org/pods/YogaKit) is v1.6 ...

**Comment by paopaosa** [comment]
v1.6 on cocoapods.org

**Comment by SirensOfTitan** [comment]
Could we please get this fixed?  1.7 has been out for months but we can't seem to get an update for CocoaPods 4 months later.

**Comment by Satchitananda** [comment]
You can set repo and tag in your Podfile, and CocoaPods will use right podspec and will install 1.7 version.

```
  pod 'Yoga', :git => 'https://github.com/facebook/yoga', :tag => '1.7.0'
  pod 'YogaKit', :git => 'https://github.com/facebook/yoga', :tag => '1.7.0'
```

**Comment by NickGerleman** [comment]
A newer pod should now be available
