### ISSUE TITLE
Examples from main page don't work in JavaScript

### ISSUE THREAD

**Issue by lesnitsky** [facebook/yoga#690]
None of examples demonstrated on [yoga main page](https://facebook.github.io/yoga/) work when implemented in javascript.

That's how layout looks in several cases (I've adopted C, Obj C, Java, C# examples to javascript):
C:
<img width="519" alt="screen shot 2017-12-21 at 6 47 32 pm" src="https://user-images.githubusercontent.com/6261302/34263113-752e09b8-e67f-11e7-9712-f073df5ba77d.png">

Obj C:
<img width="522" alt="screen shot 2017-12-21 at 6 48 25 pm" src="https://user-images.githubusercontent.com/6261302/34263146-9309afdc-e67f-11e7-8afb-7fa392f2ca4e.png">

Java:
<img width="518" alt="screen shot 2017-12-21 at 6 48 55 pm" src="https://user-images.githubusercontent.com/6261302/34263187-b192121e-e67f-11e7-9010-26c7fe67bdac.png">

C#:
<img width="573" alt="screen shot 2017-12-21 at 6 49 51 pm" src="https://user-images.githubusercontent.com/6261302/34263217-c72db722-e67f-11e7-906f-e7bc160709f6.png">

Reference repo: https://github.com/R1ZZU/yoga-playground

Is it a bug for real, or am I missing smth from docs?

**Comment by R1ZZU** [comment]
cc @woehrl01 @emilsjolander

**Comment by deioo** [comment]
Seemed related, but none of the examples on the website are working
![yoga-examples](https://user-images.githubusercontent.com/1321353/55467211-b812c900-55f8-11e9-924e-480ac2c36cdb.gif)

**Comment by emilsjolander** [comment]
@danielbuechele

**Comment by danielbuechele** [comment]
The URLs for the playground changed. I'll push an update for that.

**Comment by danielbuechele** [comment]
Links to playgrounds should be fixed now

On Apr 3, 2019, at 10:48 AM, Emil Sjölander <notifications@github.com>
wrote:

@danielbuechele <https://github.com/danielbuechele>

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/facebook/yoga/issues/690#issuecomment-479419383>, or mute
the thread
