### ISSUE TITLE
Why?

### ISSUE THREAD

**Issue by RiverYYH** [facebook/yoga#693]
# Report

- [ ] I have searched [existing issues](https://github.com/facebook/yoga/issues) and this is not a duplicate

# Issues and Steps to Reproduce
***Replaces this with steps to repro your issue.***

# Expected Behavior
***Describe what you expected would happen.***

# Actual Behavior
***Describe what actually happened.***

# Link to Code
***If you have some code that maintainers can clone/test for themselves, bugs can be resolved much faster. Please paste a link here.***

***When applicable, use this [fiddle](https://jsfiddle.net/emilsjolander/jckmwztt/) to post a web repro.***
![7c80c263-aaa7-4b79-9c46-758f57aaa6ad](https://user-images.githubusercontent.com/7495013/34352376-21269b6e-ea5d-11e7-94f1-76a4b6b4d552.png)
![7c80c263-aaa7-4b79-9c46-758f57aaa6ad](https://user-images.githubusercontent.com/7495013/34352386-364b9846-ea5d-11e7-9686-f12908240b11.png)

**Comment by orta** [comment]
you have `=` in the same line twice, I don't think you can do that.
