### ISSUE TITLE
'string' file not found (since RN 0.52)

### ISSUE THREAD

**Issue by Jpunt** [facebook/yoga#697]
# Report

- [x] I have searched [existing issues](https://github.com/facebook/yoga/issues) and this is not a duplicate

# Issues and Steps to Reproduce
We've got this in our PodFile:

```rb
pod 'React', :path => 'node_modules/react-native', :subspecs => [
  'Core',
  'CxxBridge',
  'DevSupport',
  'RCTText',
  'RCTNetwork',
  'RCTWebSocket',
  'RCTImage',
  'RCTAnimation',
]
pod 'yoga', :path => 'node_modules/react-native/ReactCommon/yoga'
```

Prior to ReactNative 0.52 this worked like a charm. After upgrading to the latest it doesn't.

# Expected Behavior
A successful build

# Actual Behavior
This error:

![screen shot 2018-01-10 at 13 24 05](https://user-images.githubusercontent.com/190501/34772774-91405676-f609-11e7-97f8-c0ae025bc895.png)

**Comment by ldshangfeng** [comment]
I think the reason is the OC file include yoga cpp has .m suffix,but it needs .mm.It builds success in only OC project,but failed in swift project.

**Comment by Aster0id** [comment]
I have the same problem.

**Comment by linjson** [comment]
me too

**Comment by glinjy** [comment]
Has Resolved it! thank you.

**Comment by corridorelf** [comment]
I have the same problem. anybody solve this problem?

**Comment by tsuijten** [comment]
I also have this issue, unable to upgrade to 0.52 because of this... 😢

**Comment by ldshangfeng** [comment]
I think we have been cast aside by facebook...Could you inspire we how to resolve this problem? @priteshrnandgaonkar

**Comment by fedegl** [comment]
Any updates?

**Comment by justjavac** [comment]
me too.

**Comment by AE-Chao** [comment]
me too.

**Comment by ldshangfeng** [comment]
the temp solution can see https://github.com/facebook/react-native/issues/17556
thanks @esam091

**Comment by MarkMolina** [comment]
Doesn't work for me. The proposed workaround deletes the imports Yoga-internal and YGNodePrint. Then I end up with errors:

`Umbrella header for module 'yoga' does ot include header 'Yoga-internal.h'`

Same for YGNodePrint.h.

**Comment by NickGerleman** [comment]
It looks like this issue relates to building Yoga via an older version of react-native. Please reopen an issue on the react-native repo if you encounter problems with a more recent RN template.
