### ISSUE TITLE
Using yoga-layout and yarn could break CI #43 

### ISSUE THREAD

**Issue by jsdario** [facebook/yoga#698]
I am using both bitrise and travis-ci, and it's breaking all my non-iOS images. I am programming on a Mac, so my yarn.lock using native dependencies is probably going to look different from a Windows or Linux build.

However on Bitrise I am compiling correctly for Android, so I assume there is a dependency that we could circumvent. If this is the case and I could help out, let me know. I'll keep researching in the meantime. `fsevents` is my first candidate, given that its installation is being skipped on linux images.

Stacktrace on Bitrise Linux for building Android image:
```
make: Entering directory '/bitrise/src/node_modules/yoga-layout/build'
  COPY Release/obj.target/nbind/geni/symbols.txt
  CXX(target) Release/obj.target/nbind/sources/yoga/Yoga.o
../sources/yoga/Yoga.cpp: In function ‘bool YGFloatIsUndefined(float)’:
../sources/yoga/Yoga.cpp:136:21: error: ‘isnan’ was not declared in this scope
   return isnan(value);
                     ^
../sources/yoga/Yoga.cpp:136:21: note: suggested alternative:
In file included from /usr/include/c++/5/random:38:0,
                 from /usr/include/c++/5/bits/stl_algo.h:66,
                 from /usr/include/c++/5/algorithm:62,
                 from ../sources/yoga/Yoga.cpp:12:
/usr/include/c++/5/cmath:641:5: note:   ‘std::isnan’
     isnan(_Tp __x)
     ^
nbind.target.mk:133: recipe for target 'Release/obj.target/nbind/sources/yoga/Yoga.o' failed
make: Leaving directory '/bitrise/src/node_modules/yoga-layout/build'
make: *** [Release/obj.target/nbind/sources/yoga/Yoga.o] Error 1
```

Stacktrace on Travis CI Linux build for node apps
```
make: Entering directory `/home/travis/build/jsdario/yeti/node_modules/yoga-layout/build'
  COPY Release/obj.target/nbind/geni/symbols.txt
  CXX(target) Release/obj.target/nbind/sources/yoga/Yoga.o
g++: error: unrecognized command line option ‘-std=c++14’
make: *** [Release/obj.target/nbind/sources/yoga/Yoga.o] Error 1
make: Leaving directory `/home/travis/build/jsdario/yeti/node_modules/yoga-layout/build'
```

I initially opened the issue on the package that makes me require yoga-layout https://github.com/jest-community/jest-snapshots-svg/issues/43.

In case this is a mistake for misusing yoga, I created the corresponding StackOverflow question https://stackoverflow.com/questions/48208503/using-yoga-layout-and-yarn-breaking-ci. So far I tried with different configurations, but seems it's just not compiling in Linux and can't find any further info.

It would be really nice to have a `yoga-layout-prebuilt` package, like [canvas-prebuilt](https://www.npmjs.com/package/canvas-prebuilt).

**Comment by orta** [comment]
FWIW, for others, I got a working travis setup for compiling yoga: https://github.com/jest-community/jest-snapshots-svg/pull/46

**Comment by DuncanMacWeb** [comment]
@jsdario [yoga-layout-prebuilt](https://github.com/vadimdemedes/yoga-layout-prebuilt) 😄
