### ISSUE TITLE
 Excessive memory consumption on browser 128MB

### ISSUE THREAD

**Issue by wiltonlazary** [facebook/yoga#699]
import * as layout from 'yoga-layout/sources/entry-browser'

**Comment by arcanis** [comment]
Unfortunately, this is a side effect of asm.js requiring us to allocate all the memory upfront (it doesn't support growing memory).

**Comment by wiltonlazary** [comment]
Wow sorry for that, soon we will need a computer with infinite memory and processor power ;).

So I can only lie down and cry ;(
