### ISSUE TITLE
How to use YogaNode?

### ISSUE THREAD

**Issue by PTrain666** [facebook/yoga#703]
i'm newer in yoga  
i can write layout by xml  
such as: 
```xml
<com.facebook.yoga.android.YogaLayout>
    <ImageView />
    <ImageView />
</com.facebook.yoga.android.YogaLayout>
```

but how to write layout by java  
i try to use YogaNode and addChildAt，but it doesnt work  
can someone give me a demo?  
Thanks!

**Comment by zhaozheyu** [comment]
YogaNode just calculate the layoutX and layoutY , how to add view to its parent
now i write like this 
```
layout.addView(view);
node =  ((YogaLayout)layout).getYogaNode().getChildAt(layout.indexOfChild(view));
node.setFlexDirection();
```

but VirtualYogaLayout doesnt work,when add virtualyogalayout it clears its children

**Comment by NickGerleman** [comment]
Please take a look at the documentation, or samples inside the repo.
