### ISSUE TITLE
alignItems not working correctly in a specific case.

### ISSUE THREAD

**Issue by hovox** [facebook/yoga#707]
# Report

- [x] I have searched [existing issues](https://github.com/facebook/yoga/issues) and this is not a duplicate

# Issues and Steps to Reproduce
Run example code , expected to draw view with green background.

And [here](https://github.com/facebook/react-native/issues/17813) is the issue link in RN project, i thought this may be more related to yoga.
# Expected Behavior
Should draw inner view with green background.

# Actual Behavior
Inner view with green background is not shown

# Link to Code
```
import React, { Component } from 'react';
import { View, StyleSheet } from 'react-native';


export default class App extends Component {
  render() {
    return (
      <View style={styles.container}>
       <View style={{flex: 1, backgroundColor:'green'}}>
       </View>
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center'
  }
});

```

**Comment by NickGerleman** [comment]
flex-direction in react-native defaults to column, so in this example, the green view has a zero width.
