### ISSUE TITLE
yogakit how to make a dynamic tableviewcell?

### ISSUE THREAD

**Issue by bawangflower** [facebook/yoga#709]
I have an ios app use yogakit to layout,there is a tableview has many tableview cell,but how to make a dynamic tableviewcell. I donot want to set cell an absolute height.

environment : xcode9,ios11.2

**Comment by FarajiMehrdad** [comment]
`class SingleLabelCollectionCell: UITableViewCell {
    let label: UILabel = UILabel()
    let label2: UILabel = UILabel()
    let label3: UILabel = UILabel()


    required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
        initViews()
    }

    override init(style: UITableViewCellStyle, reuseIdentifier: String?) {
        super.init(style: style, reuseIdentifier: reuseIdentifier)
        initViews()
    }

    func initViews() {



        contentView.configureLayout { (layout) in
            layout.isEnabled = true
            layout.flexDirection = .column
            layout.justifyContent = .center
            layout.alignItems = .center

        }

        contentView.backgroundColor = .cyan


        label.backgroundColor = .red
        label.text = "first"
        label.textAlignment = .center
        label.numberOfLines = 1

        label.configureLayout{layout in
            layout.isEnabled = true
        }


        contentView.addSubview(label)


        label2.backgroundColor = .yellow
        label2.text = "second"
        label2.textAlignment = .center
        label2.numberOfLines = 1

        label2.configureLayout{layout in
            layout.isEnabled = true
            layout.margin = 10
            layout.padding = 10
        }
        contentView.addSubview(label2)



        label3.backgroundColor = .brown
        label3.text = "third"
        label3.textAlignment = .center
        label3.numberOfLines = 1

        label3.configureLayout{layout in
            layout.isEnabled = true
            layout.margin = 10
            layout.padding = 10
        }
        contentView.addSubview(label3)

        let border = UIView(frame: .zero)
        border.backgroundColor = .lightGray
        border.configureLayout { (layout) in
            layout.isEnabled = true
            layout.height = 0.5
            layout.marginHorizontal = 25
        }
        contentView.addSubview(border)



    }


    override func layoutSubviews() {
        super.layoutSubviews()
        contentView.yoga.width = YGValue(self.bounds.width)
        contentView.yoga.applyLayout(preservingOrigin: true, dimensionFlexibility: .flexibleHeigth)

        print("contentView height size is \(self.contentView.frame.height)")
        print("frame  height size is \(self.frame.height) ")

    }
}`

**Comment by bawangflower** [comment]
Finally,I have no idea of this problem. Now, use another frame called Texture ,you can find it at Github.Which use Yoga too,and supports dynamic UITableviewCell.

**Comment by lucdion** [comment]
Hi, I have created a Swift wrapper for Yoga called FlexLayout (https://github.com/layoutBox/FlexLayout/). There is an example of UITableView with variable size cells here: https://github.com/layoutBox/FlexLayout/blob/master/docs_markdown/examples.md#uitableview-with-variable-size-cells

**Comment by sflahave** [comment]
I've been struggling quite a bit with getting consistent behavior from YogaKit with respect to dynamically-sized tableView cells also. I put together a sample application that has a table view with 3 rows, each of the same type of cell named CustomCell. CustomCell has a left label and a right label. The right label may be arbitrarily long and should word-wrap. It works pretty well, but there are some unacceptable differences between devices and iOS versions.
https://github.com/sflahave/YogaTables

**Comment by fuhailong** [comment]
cell ：
- (CGSize)systemLayoutSizeFittingSize:(CGSize)targetSize
        withHorizontalFittingPriority:(UILayoutPriority)horizontalFittingPriority
              verticalFittingPriority:(UILayoutPriority)verticalFittingPriority {
    return [self.contentView.yoga calculateLayoutWithSize:CGSizeMake(targetSize.width, MAXFLOAT)];
}

- (void)layoutSubviews {
    [super layoutSubviews];
    [self.contentView.yoga applyLayoutPreservingOrigin:NO];
}

heightForRow :
CGSize size = [cell systemLayoutSizeFittingSize:CGSizeZero];
return size.height
👍

**Comment by himanthGit** [comment]
@fuhailong How can you even access a cell in `heightForRow`?

**Comment by mzF414** [comment]
`
    override func systemLayoutSizeFitting(_ targetSize: CGSize) -> CGSize {
        contentView.yoga.applyLayout(preservingOrigin: false, dimensionFlexibility: YGDimensionFlexibility.flexibleHeight)

        return contentView.frame.size
    }
    
    override func systemLayoutSizeFitting(_ targetSize: CGSize, withHorizontalFittingPriority horizontalFittingPriority: UILayoutPriority, verticalFittingPriority: UILayoutPriority) -> CGSize {
        contentView.yoga.applyLayout(preservingOrigin: false, dimensionFlexibility: YGDimensionFlexibility.flexibleHeight)

        return contentView.frame.size
    }
`
this work both in UITableViewCell and UICollectionViewCell, but contentView should make specify width
`
        contentView.configureLayout { (layout: YGLayout) in
            layout.isEnabled = true
            layout.width = YGValue(UIScreen.main.bounds.size.width)
        }
`
