### ISSUE TITLE
Designated initializer syntax not supported by MSVC

### ISSUE THREAD

**Issue by paulrosania** [facebook/yoga#717]
Yoga defines `gYGNodeStyleDefaults` and `gYGNodeLayoutDefaults` using nonstandard initializer syntax supported by clang (and proposed for C++20). MSVC does not implement a supporting extension. (I'm incorporating Yoga into a 2D game that needs to build on Windows under MSVC, which is why I encountered this.)

I'm happy to submit a patch! I can envision at least three paths forward, so I figured I would check before submitting something:

1. Do nothing. Anyone with my use case will need to maintain a fork. Simplest but least ideal for Windows projects.
2. Remove the `.property = ` prefixes in the definitions. This is the simplest change that will get MSVC working, but carries some risk of bugs if the struct definitions are modified without precise modification of the initializers.
3. Use macros for each property initializer. Macros would use designated initializer syntax except on MSVC, where they would just use the property value. Preserves safety on non-Windows platforms, but risks bugs under MSVC if properties are added to the struct definitions without matching declarations.
4. Use x-macros for struct definition and initialization of the static constants. This would theoretically guarantee that the structs and static constants match, across all platforms, but is the most substantial modification to the code, and may harm legibility somewhat.

How should I proceed? Thanks!

**Comment by woehrl01** [comment]
Thanks @paulrosania for giving this a try. As already discussed in #700 and #714 (@rozele) there are multiple ways to have this fixed. After considering multiple alternatives I personally would prefere that we go for the solution @priteshrnandgaonkar mentioned: Using the C++ constructor.

`gYGNodeStyleDefaults` and `gYGNodeLayoutDefaults` have been initially introduced to allow a `memcpy` in the `YG*New` methods, which are already refactored. I think if we move the assignments of the defaults to a constructor of `YGNodeStyle` and `YGNodeLayout` we gain the best experience, as we still can use the property names.

We need to have `gYGConfigDefaults` refactored, too.

**Comment by paulrosania** [comment]
Sorry for the duplicate! I did a fair amount of searching and somehow missed those issues. It looks like @priteshrnandgaonkar is working on a patch so I'll close this.
