### ISSUE TITLE
How use YogaKit with Xamarin/F#?

### ISSUE THREAD

**Issue by mamcx** [facebook/yoga#719]
I try to import Yoga:

```
    <Reference Include="Facebook.Yoga">
      <HintPath>..\..\packages\Facebook.Yoga.1.5.0-pre1\lib\Xamarin.iOS10\Facebook.Yoga.dll</HintPath>
    </Reference>
```

And then to use it:

```
open Foundation
open UIKit
open Facebook.Yoga

let render (window:UI.Window) =
    let win = new BaseViewController()
    let root = win.View

    root.Yoga().IsEnabled <- true
 ```

However "Yoga()" not exist. Also, is not found on nuget "YogaKit" (is this necessary?).

**Comment by rmarinho** [comment]
yeah we will need to update the pcakges and work on it again.. i started some work but then moved to use other Project. But i m glad to help anyone that want's to mantain it.

**Comment by NickGerleman** [comment]
The C# bindings have not had a dedicated maintainer. We are removing them from the repo as part of cleanup for the next OSS release of Yoga.
