### ISSUE TITLE
C API Documentation

### ISSUE THREAD

**Issue by Robert-M-Muench** [facebook/yoga#721]
Maybe I'm overlooking something, but I'm missing the C API documentation. In the past it was available but the now docs don't have any of it. 

Will this be changed again in future?

**Comment by finnoleary** [comment]
For the people who need C documentation, until this issue is solved, the last commit with C documentation is: https://github.com/facebook/yoga/commit/bdc37b07971b64 (This is the commit in which is was removed).

Thus the 'latest' C documentation can be found at this link: https://github.com/facebook/yoga/blob/48d82224ee34fd60ad21ab90a2c38dd4cfb1fdb4/docs/_docs/api/c.md

I hope this helps

**Comment by Robert-M-Muench** [comment]
Thanks.

I'm wondering why it was removed at all. IMO using yoga for C apps is a very important use case.

**Comment by finnoleary** [comment]
Yes. I would have thought that in any reasonable system, documentation would be written first for the language that the product is written in, _then_ written for secondary languages.

**Comment by carmel4a** [comment]
Sorry for spam/bump, but it's still interesting why C/C++ docs are not maintained. I'm using Yoga in native C++ project. O/c docs sent by @finnoleary are sufficient to work, but it will be prettier to have it in "normal" place. :+1: for good lib, cheers!

**Comment by Robert-M-Muench** [comment]
Any feedback from FB guys on this? Still, I think yoga is mostly a C lib and than bindings to other languages exist.

**Comment by cancerberoSgx** [comment]
This also happens in JavaScript, although the API seems straight forward and the types descriptions are there, some basic method descriptions would be awesome. I see some pull-requests or branches with this kind of documentation had been removed / closed, so I wonder what't the status on this matter. Thanks

**Comment by NickGerleman** [comment]
We now document C API usage (see e.g. https://www.yogalayout.dev/docs/getting-started/laying-out-a-tree)
