### ISSUE TITLE
How use yogakit directly for both iOS/Android?

### ISSUE THREAD

**Issue by mamcx** [facebook/yoga#723]
I see in the main page about Litho and ComponentKit, but both are divergent libraries that are specific for each target.

But how use Yoga with my own UI abstraction? (I wanna something similar to https://www.elm-tutorial.org/en/02-elm-arch/01-introduction.html). 

The documentation I see and the samples are not standalone.

**Comment by NickGerleman** [comment]
I think you are looking for a UI framework, like react-native.
