### ISSUE TITLE
Document not found: https://www.w3.org/TR/YG3-flexbox/

### ISSUE THREAD

**Issue by bang590** [facebook/yoga#724]
https://github.com/facebook/yoga/blob/a874992e7c702d9782aa972afd511261085c1518/yoga/Yoga.cpp#L2256

**Comment by woehrl01** [comment]
The correct doc is https://www.w3.org/TR/CSS3-flexbox/ I think this url was a vicitim of the `CSS` to `YG` rename.

**Comment by NickGerleman** [comment]
It looks like this has been fixed
