### ISSUE TITLE
Link to Android Documentation is broken

### ISSUE THREAD

**Issue by rorlig** [facebook/yoga#729]
# Report

- [ ] I have searched [existing issues](https://github.com/facebook/yoga/issues) and this is not a duplicate

# Issues and Steps to Reproduce
Click on the android documentation link in the android folder. https://facebook.github.io/yoga/docs/api/android/

# Expected Behavior
See the android documentation.

# Actual Behavior
Redirects to error page. 

# Link to Code
***If you have some code that maintainers can clone/test for themselves, bugs can be resolved much faster. Please paste a link here.***

***When applicable, use this [fiddle](https://jsfiddle.net/emilsjolander/jckmwztt/) to post a web repro.***

**Comment by alexamster** [comment]
So can we please fix this, it makes it very hard to use yoga on android...

**Comment by iain-merrick-fanduel** [comment]
Any plans to address this? I just encountered it myself.

**Comment by NickGerleman** [comment]
No longer relevant for new documentation at https://www.yogalayout.dev/
