### ISSUE TITLE
UILabel size is wrong

### ISSUE THREAD

**Issue by Zyj163** [facebook/yoga#731]
# Report

- [ ] I have searched [existing issues](https://github.com/facebook/yoga/issues) and this is not a duplicate

# Issues and Steps to Reproduce
***Replaces this with steps to repro your issue.***

# Expected Behavior
UILabel's size is wrong，the label's text is break...

# Actual Behavior
***Describe what actually happened.***

# Link to Code
titleLabel.textAlignment = .center
        titleLabel.font = scheme.boldFont(18)
        titleLabel.textColor = scheme.globalTextColor
        titleLabel.text = "热门商品"
        
        let titleView = UIView()
        let leftImageView = UIImageView(image: UIImage(named: "section_header_l"))
        let rightImageView =  UIImageView(image: UIImage(named: "section_header_r"))
        
        addSubview(titleView)
        
        titleView.addSubview(leftImageView)
        let centerView = UIView()
        titleView.addSubview(centerView)
        centerView.addSubview(titleLabel)
        let centerLine = UIView()
        centerLine.backgroundColor = scheme.globalTextColor
        centerView.addSubview(centerLine)
        titleView.addSubview(rightImageView)

configureLayout { (layout) in
            layout.isEnabled = true
            layout.alignItems = .center
        }
        titleView.configureLayout { (layout) in
            layout.isEnabled = true
            layout.flexDirection = .row
            layout.justifyContent = .flexStart
            layout.paddingTop = 17.5
        }
        centerView.configureLayout { (layout) in
            layout.isEnabled = true
            layout.marginTop = 2.5
        }
        titleLabel.configureLayout { (layout) in
            layout.isEnabled = true
            layout.paddingHorizontal = 12
        }
        centerLine.configureLayout { (layout) in
            layout.isEnabled = true
            layout.marginTop = 6
            layout.height = 0.5
            layout.marginHorizontal = 11
            layout.alignSelf = .stretch
        }

***When applicable, use this [fiddle](https://jsfiddle.net/emilsjolander/jckmwztt/) to post a web repro.***

**Comment by NickGerleman** [comment]
It looks like this issue is stale. Please create a new one if you are still seeing the behavior.
