### ISSUE TITLE
[Playground] flexDirection is missing in the generated code for ReactNative

### ISSUE THREAD

**Issue by rhazegh** [facebook/yoga#732]
# Report

- [x] I have searched [existing issues](https://github.com/facebook/yoga/issues) and this is not a duplicate

# Issues and Steps to Reproduce
- Go to https://goo.gl/2VvJQy
- Get code > React Native

# Expected Behavior
Elements that have `Flex Direction: row` must have `flexDirection: 'row'` in the generated code for react native.

# Actual Behavior
`flexDirection: 'row'` is missing for all elements that have this property set (e.g. element 3)

**Comment by galtenberg** [comment]
Confirmed this is an issue. Generated code does not match Playground when used in real projects.

**Comment by NickGerleman** [comment]
Duplicate of #807
