### ISSUE TITLE
Stretch is not working as expected in JS build and Playground.

### ISSUE THREAD

**Issue by andrewliebchen** [facebook/yoga#735]
# Report

`align-items` when set to `stretch` is not working as expected in JS build and Playground.

✅ I have searched [existing issues](https://github.com/facebook/yoga/issues) and this is not a duplicate

# Issues and Steps to Reproduce
* Visit the Yoga layout playground
* Configure a root element taller than child nodes
* Set `align-items` to `stretch`

# Expected Behavior
The height of the child nodes would change to fill the height of the parent container.

# Actual Behavior
The height of the child nodes remains the same.

# Link to Code
I'm working on an implementation of Yoga to drive layout for prototypes in FramerJS. I'm using a JS build.

Code doesn't work, nor does it work in the playground:
<img width="1112" alt="screenshot 2018-03-18 18 54 48" src="https://user-images.githubusercontent.com/1839748/37574459-34dd5f50-2ade-11e8-98d4-6855d97bf164.png">

Thanks!

**Comment by flynorc** [comment]
Coming here after having experiencing the same issue, 3 years later. Did you happen to find a fix/workaround for this by chance? I've tried with align-self on the children, that also does not work. The only thing that did work was setting up the height of the elements to a fixed px value, but that only works if the height of the parent is known ahead of time so not good for some use cases.

**Comment by NickGerleman** [comment]
Old playground might be giving children definite height. Does not repro currently: https://www.yogalayout.dev/playground?code=DwGQhgng9grgLgAgMZQHYDMCWBzAvAb3xgGcBTAdVICMARU9MGAGzmIC4E4AnGUgXz4A+AFAIEwAHJQAJqVFiExOBCakC+eQoQB3TNLgALDgCYADKYA0mhQdI4DcEwFZL1sQAcw06ZlTYOAIyuWmJgTDioAJJwpAC27AgA5EpcpHBIBolWWgIiWpIyciGKyqrqbgqxYFzYvhxO2cU6eob1wSEC1gD0eQoFsiUqaoRVNXUIDQi29o4Tls36RnMCCD3ywF1SsiIb4NDwgkA
