### ISSUE TITLE
Yoga not working with UIScrollView

### ISSUE THREAD

**Issue by 100mango** [facebook/yoga#737]
# Report

- [x] I have searched [existing issues](https://github.com/facebook/yoga/issues) and this is not a duplicate

# Issues and Steps to Reproduce

1. setup a scrollview
2. add subview to scrollview
3. apply layout

# Expected Behavior

scrollview can scroll with right contentsize

# Actual Behavior

can't scroll as well as right subview size.

x7f95e107d400; frame = (0 0; 414 736); clipsToBounds = YES; gestureRecognizers = <NSArray: 0x6000002510a0>; layer = <CALayer: 0x6000000318c0>; contentOffset: {0, -64}; contentSize: {0, 0}; adjustedContentInset: {64, 0, 0, 0}>

# Link to Code

~~~swift
    override func viewDidLoad() {
        super.viewDidLoad()
        view.backgroundColor = UIColor.white
        
        let root = self.view!
        root.backgroundColor = .white
        root.yoga.isEnabled = true
        
        let scrollview = UIScrollView()
        scrollview.backgroundColor = .red
        scrollview.yoga.isEnabled = true
        scrollview.yoga.overflow = .scroll
        scrollview.yoga.paddingVertical = 10
        scrollview.yoga.flexDirection = .column
        scrollview.yoga.alignItems = .center
        
        root.addSubview(scrollview)
        
        for _ in 0...20 {
            let view = UIView()
            view.backgroundColor = .yellow
            view.yoga.isEnabled = true
            view.yoga.width = 80
            view.yoga.height  = 80
            scrollview.addSubview(view)
        }
 
        self.view.yoga.applyLayout()
    }
~~~

![image](https://user-images.githubusercontent.com/5073511/37647695-d355456e-2c67-11e8-872a-4979726b12f7.png)

**Comment by LeoSchleicher** [comment]
Better after applyLayout() set contentSize property of UIScrollview to Scrollable size.

**Comment by koenpunt** [comment]
> Better after applyLayout() set contentSize property of UIScrollview to Scrollable size.

That's obviously a workaround. But [according to the tests](https://github.com/facebook/yoga/blob/46c96ee2cbc6260a1ef9398dd750973e427b9984/csharp/iOS/Facebook.YogaKit.iOS.Tests/YogaKitNativeTest.cs) it should work, but maybe the tests do not cover all cases..

**Comment by 100mango** [comment]
@xrom888 Would you mind giving more detail about the layout process in yoga, What is code in yoga imply " UIScrollView will layout innerView it will set it's YogaNode height from auto to exact value, so the innerView will layout second time with exact height and all it's children will be placed inside rect with that height."

**Comment by mzF414** [comment]
@koenpunt I found it was a C# test case , didn't work on swift
