### ISSUE TITLE
UILabel in Row layout - text shrinking problem

### ISSUE THREAD

**Issue by LeoSchleicher** [facebook/yoga#738]
# Report

- [ ] I have searched [existing issues](https://github.com/facebook/yoga/issues) and this is not a duplicate

# Issues and Steps to Reproduce
I have some UILabels with fixed texts in row layout, I do justifyContent = .center, overall width of all labels is smaller than width of container

# Expected Behavior
I just want to put all labels in row

# Actual Behavior
sometimes one or more labels got ellipsize text shrinking after applyLayout.
I've done some research and found, that intrinsicContentSize of shrinked label is  (193.333333333333, 17.6666666666667), but after applyLayout it rounds UILabel width to 193.0 - that causes text shrinking.

# Link to Code
Code example is hard to provide as it depends on Device, Font parameters, Text and so on.

**Comment by NickGerleman** [comment]
Closing in favor of #749 which has had more discussion/context
