### ISSUE TITLE
Windows 10 Yarn add Issue

### ISSUE THREAD

**Issue by rexkenley** [facebook/yoga#739]
I tried installing yoga-layout on a windows 10 machine and I am getting this error. What can I do to fix this?

[4/4] Building fresh packages...
[-/8] ⠄ waiting...
[7/8] ⠄ yoga-layout: ERR! errno 23
[-/8] ⠄ waiting...
[-/8] ⠄ waiting...
error An unexpected error occurred: "C:\\Code\\kenleyr\\Projects\\JavaScript\\DaveyJS3\
ode_modules\\yoga-layout: Command failed.
Exit code: 23
Command: C:\\WINDOWS\\system32\\cmd.exe
Arguments: /d /s /c npm run build:node
Directory: C:\\Code\\kenleyr\\Projects\\JavaScript\\DaveyJS3\
ode_modules\\yoga-layout
Output:
> yoga-layout@1.9.3 build:node C:\\Code\\kenleyr\\Projects\\JavaScript\\DaveyJS3\
ode_modules\\yoga-layout
> npm run copy-sources && autogypi && node-gyp configure build
> yoga-layout@1.9.3 copy-sources C:\\Code\\kenleyr\\Projects\\JavaScript\\DaveyJS3\
ode_modules\\yoga-layout
> ! npm -s run is-monolithic || (rsync -r --checksum --delete ../yoga/ sources/yoga/)

'!' is not recognized as an internal or external command,
operable program or batch file.
rsync: change_dir \"/cygdrive/c/Code/kenleyr/Projects/JavaScript/DaveyJS3/node_modules/yoga-layout//../yoga\" failed: No such file or directory (2)
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1178) [sender=3.1.2]
npm ERR! code ELIFECYCLE
npm ERR! errno 23
npm ERR! yoga-layout@1.9.3 copy-sources: `! npm -s run is-monolithic || (rsync -r --checksum --delete ../yoga/ sources/yoga/)`
npm ERR! Exit status 23
npm ERR!
npm ERR! Failed at the yoga-layout@1.9.3 copy-sources script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\\Users\\kenleyr\\AppData\\Roaming\
pm-cache\\_logs\\2018-03-23T15_15_07_057Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 23
npm ERR! yoga-layout@1.9.3 build:node: `npm run copy-sources && autogypi && node-gyp configure build`
npm ERR! Exit status 23

**Comment by chandresh87** [comment]
I am also getting the same issue. Are you able to solve this problem?

**Comment by rexkenley** [comment]
Nope.

**Comment by matthewww** [comment]
On windows, if I skip copy-sources, and symbolically link _javascript/yoga_ to _sources/yoga_ instead, I get lots of CPP/CC compilation errors. I feel like I'm missing some nmap config. Or perhaps this PR would help: https://github.com/facebook/yoga/pull/700

 node.cc fails on the following:
`..\sources\Node.cc(388): error C3861: 'YGNodeGetParent': identifier not found [D:\workspace\yoga\javascript\bu
ild\nbind.vcxproj]`

... and yoga.cpp on many syntax errors such as these, which look like C90 language standards such as designated initialisers:
'..\sources\yoga\Yoga.cpp(45): error C2059: syntax error: '.' [D:\workspace\yoga\javascript\build\nbind.vcxproj ]
..\sources\yoga\Yoga.cpp(46): error C2143: syntax error: missing ';' before '{' [D:\workspace\yoga\javascript\
build\nbind.vcxproj]
..\sources\yoga\Yoga.cpp(46): error C2447: '{': missing function header (old-style formal list?) [D:\workspace
\yoga\javascript\build\nbind.vcxproj]'

**Comment by Dogyunjeong** [comment]
I have same issue.

**Comment by another-guy** [comment]
This breaks downstream dependencies. E.g. other user and I are unable to install `@react-pdf/core` which depends on `yoga-layout@1.9.3`

https://github.com/diegomura/react-pdf/issues/251

**Comment by AirborneEagle** [comment]
I am blocked by this issue.
Has there been any update? 
I am on Windows 10. 
running `npm install yoga-layout`  in the terminal of intellij.

**Comment by ealhomsi** [comment]
is this still open?

**Comment by another-guy** [comment]
@ealhomsi as you can see, it is... https://github.com/facebook/yoga/pull/755#issuecomment-469326353 Hopefully, gets resolved soon.

**Comment by Losses** [comment]
> @ealhomsi as you can see, it is... [#755 (comment)](https://github.com/facebook/yoga/pull/755#issuecomment-469326353) Hopefully, gets resolved soon.

But the pr is closed...

**Comment by Lotes** [comment]
For me, setting bash in Npm/Yarn brought me further:
`npm config set script-shell "C:\\to_whereever\\git\\bin\\bash.exe"`

**Comment by NickGerleman** [comment]
1813748eaa60e6129c1e1c00c08322b5687b1702 changes how the package is built, and we also test building on Windows now as part of GitHub Actions.
