### ISSUE TITLE
 The platform of the target `MyApplication` (iOS 10.0) is not compatible with `Yoga (1.8.0)`, which does not support `ios`.

### ISSUE THREAD

**Issue by yashwanth777** [facebook/yoga#740]
I am adding Yoga as a dependency in my podspec file. But it is showing up with the above error. Did they remove support for ios platform??

My Podspec 
s.dependency "React"
s.dependency "Yoga"
s.dependency "DoubleConversion"
s.dependency "Folly"
s.dependency "glog"

I am trying to add React Native code to a swift framework and distribute that framework via cocoapods.

**Comment by keyjacky** [comment]
the same issue
anyone can help ?

**Comment by faimin** [comment]
same error to me when install `YogaKit` with `CocoaPods` 1.4

**Comment by keyjacky** [comment]
seems 1.7.0 is work
this error only appear at 1.8.0

**Comment by yashwanth777** [comment]
I think the podspec in 1.8.0 doesn't support ios

**Comment by awaylyr** [comment]
the same error ,but yoga 1.6 not match react 0.54

**Comment by faimin** [comment]
because the `yoga.podspec` only set the `deployment_target` to `osx`, not set another plateform.

![](http://olmn3rwny.bkt.clouddn.com/20180404110213_IQaRuI_QQ20180404-105906@2x.jpeg)

**Comment by biubiublue** [comment]
the same issue
anyone can help ?

**Comment by Satchitananda** [comment]
@biubiublue 
I have forcibly used 1.7 version:

```
  pod 'Yoga', :git => 'https://github.com/facebook/yoga', :tag => '1.7.0'
  pod 'YogaKit', :git => 'https://github.com/facebook/yoga', :tag => '1.7.0'
```

**Comment by WPDreamMelody** [comment]
[!] The platform of the target `yogaDemo` (iOS 9.0) is not compatible with `Yoga (1.8.0)`, which does not support `ios`.

**Comment by WPDreamMelody** [comment]
➜  yogaDemo pod install 
Analyzing dependencies
[!] Unable to satisfy the following requirements:

- `YogaKit (= 1.8.0)` required by `Podfile`

None of your spec sources contain a spec satisfying the dependency: `YogaKit (= 1.8.0)`.

You have either:
 * out-of-date source repos which you can update with `pod repo update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

Note: as of CocoaPods 1.0, `pod repo update` does not happen on `pod install` by default.

**Comment by WPDreamMelody** [comment]
yogakit 1.6.0 & 1.8.0 can not use

**Comment by WPDreamMelody** [comment]
solution：
`
pod 'Yoga', '1.6.0'
pod 'YogaKit', '1.6.0'
`

**Comment by leewaycn** [comment]
[!] The platform of the target `TestYogaFlexLayout` (iOS 8.0) is not compatible with `Yoga (1.8.0)`, which does not support `ios`.

**Comment by HermitCarb** [comment]
Same issue. 20180605

```
  pod 'Yoga'
  pod 'YogaKit'
```
Release 1.8.0 will be tried to install. ❌

```
  pod 'Yoga', :git => 'https://github.com/facebook/yoga', :tag => '1.7.0'
  pod 'YogaKit', :git => 'https://github.com/facebook/yoga', :tag => '1.7.0'
```
Release 1.7.0 will be installed. ✅

```
  # notice: release 1.8.0 is different from tag v1.8.0, not at same commit.
  pod 'Yoga', :git => 'https://github.com/facebook/yoga', :tag => 'v1.8.0'
  pod 'YogaKit', :git => 'https://github.com/facebook/yoga', :tag => 'v1.8.0'
```
Tag v1.8.0 will be tried to install. ❌

```
  pod 'Yoga', :git => 'https://github.com/facebook/yoga'
  pod 'YogaKit', :git => 'https://github.com/facebook/yoga'
```
Release 1.8.1 will be installed though this release not visible on tag list. ✅

**Comment by NickGerleman** [comment]
Please reopen if this issue affects the current version of Yoga.
