### ISSUE TITLE
SoLoader license incompatible, yet is statically instantiated

### ISSUE THREAD

**Issue by vinc3m1** [facebook/yoga#743]
Since SoLoader is still on BSD+Patents, using Yoga in an environment where the BSD+Patents license is not approved is still impossible because Yoga statically uses SoLoader in YogaNode and YogaConfig:

https://github.com/facebook/yoga/blob/3dfb68887db34a8a77e894c66a50e747d831b0b9/java/com/facebook/yoga/YogaConfig.java#L18-L24

https://github.com/facebook/yoga/blob/3dfb68887db34a8a77e894c66a50e747d831b0b9/java/com/facebook/yoga/YogaNode.java#L19-L25

Can we make this loading optional or configurable? Or even better would be to just to convert SoLoader to MIT...

**Comment by NickGerleman** [comment]
SoLoader has been moved to the more permisive Apache license. https://github.com/facebook/SoLoader/commit/fa4d02f679ba123302e70cdd6c00cb8ef6143c50
