### ISSUE TITLE
how to use yogalayout in java code

### ISSUE THREAD

**Issue by loveAndroid** [facebook/yoga#753]
i want write it in Java code ，but ，some it have some problem 

how can i use addview with a exit yoganode ？  

my code like this  

YogaLayout root = new YogaLayout(this);
        root.getYogaNode().setFlexDirection(YogaFlexDirection.ROW);

        TextView tv1 = new TextView(this);
        tv1.setText("text 11111 ");
        tv1.setBackgroundColor(Color.RED);

        YogaNode node1  =  DyUtils.styleToYogaNode(style,this);

        TextView tv2 = new TextView(this);
        tv2.setText("text 22222  ");
        tv2.setBackgroundColor(Color.BLUE);
        YogaNode node2  =  DyUtils.styleToYogaNode(style,this);
        node2.setData(tv2);
        node1.setData(tv1);

        root.addView(tv1,node1);
        root.addView(tv2,node2);
        root.invalidate();
       

    but ， the tv1 and tv2  all this height is 0 ， please help ？

**Comment by helele90** [comment]
use this. https://github.com/google/flexbox-layout

**Comment by YZhongBin** [comment]
Have you solved this problem?  I have the same problem

**Comment by NickGerleman** [comment]
Closing as stale
