### ISSUE TITLE
Installing Yoga through NPM on Ubuntu 16.04

### ISSUE THREAD

**Issue by audiolion** [facebook/yoga#754]
# Report

- [x] I have searched [existing issues](https://github.com/facebook/yoga/issues) and this is not a duplicate

# Issues and Steps to Reproduce
***Replaces this with steps to repro your issue.***

On ubuntu 16.04, `yarn add yoga`

# Expected Behavior
***Describe what you expected would happen.***

Installs

# Actual Behavior
***Describe what actually happened.***

Fails to install

# Link to Code
***If you have some code that maintainers can clone/test for themselves, bugs can be resolved much faster. Please paste a link here.***

```
error An unexpected error occurred: "/node_modules/yoga-layout: Command failed.
Exit code: 1
Command: sh
Arguments: -c npm run build:node
Directory: /node_modules/yoga-layout
Output:
> yoga-layout@1.9.3 build:node /node_modules/yoga-layout
> npm run copy-sources && autogypi && node-gyp configure build


> yoga-layout@1.9.3 copy-sources /node_modules/yoga-layout
> ! npm -s run is-monolithic || (rsync -r --checksum --delete ../yoga/ sources/yoga/)

make: Entering directory '/node_modules/yoga-layout/build'
  COPY Release/obj.target/nbind/geni/symbols.txt
  CXX(target) Release/obj.target/nbind/sources/yoga/Utils.o
  CXX(target) Release/obj.target/nbind/sources/yoga/YGEnums.o
  CXX(target) Release/obj.target/nbind/sources/yoga/YGNode.o
  CXX(target) Release/obj.target/nbind/sources/yoga/YGNodePrint.o
  CXX(target) Release/obj.target/nbind/sources/yoga/Yoga.o
  CXX(target) Release/obj.target/nbind/sources/Config.o
  CXX(target) Release/obj.target/nbind/sources/Node.o
  CXX(target) Release/obj.target/nbind/sources/global.o
  CXX(target) Release/obj.target/nbind/sources/nbind.o
g++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-5/README.Bugs> for instructions.
make: *** [Release/obj.target/nbind/sources/nbind.o] Error 4
nbind.target.mk:138: recipe for target 'Release/obj.target/nbind/sources/nbind.o' failed
make: Leaving directory '/node_modules/yoga-layout/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at ChildProcess.emit (events.js:180:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:12)
gyp ERR! System Linux 4.4.0-112-generic
gyp ERR! command \"/usr/local/bin/node\" \"/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js\" \"configure\" \"build\"
gyp ERR! cwd /node_modules/yoga-layout
gyp ERR! node -v v9.11.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! yoga-layout@1.9.3 build:node: `npm run copy-sources && autogypi && node-gyp configure build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the yoga-layout@1.9.3 build:node script.
```

I have searched and found a few other people with similar issues, I have tried building with `gcc 4.9` and `gcc 5.5`, I have tried adding `node-gyp` globally before installing, and I have tried with node versions `8.11.1, 9.11.1`. No luck so far. Really not sure why it is failing and what I can do to get the build to work, any ideas?

**Comment by simast** [comment]
Looks like a memory issue? Quick google suggests gcc has not enough memory to compile yoga and no swap available?

**Comment by audiolion** [comment]
Yes that is it. Out of curiosity, how could you tell it was a memory issue/what did you google? I tried a number of things but I guess I was searching for a compatibility issue.

**Comment by simast** [comment]
I just googled for the main error in the logs - which was `g++: internal compiler error: Killed` - and the first result pointed to out of memory problems. The logs did not indicate that there was something wrong while actual yoga compilation - but an issue with the compiler itself as a tool. Anyway, I am glad your issue has been solved, have fun using yoga :)

**Comment by Qu4dratus** [comment]
Hey guys, i followed all steps in all issues related to this and i'm still with this problem, i really want to install yoga to use react-pdf, could anyone help? :disappointed:

**Comment by wellermiranda** [comment]
I have the same problem.

**Comment by atherdon** [comment]
> ubuntu:16.04

@wellermiranda i'm experienced that issue when i run Travis CI - maybe you can advice how i can update my configuration - in order to fix it?
