### ISSUE TITLE
[YogaKit][iOS] padding and border is not working.

### ISSUE THREAD

**Issue by harryzjm** [facebook/yoga#757]
I used `YogaKit` 1.7.0.  

    override func viewDidLoad() {
        super.viewDidLoad()

        view.configureLayout { (layout) in
            layout.isEnabled = true
            layout.flexDirection = .column
            layout.justifyContent = .center
            layout.alignItems = .center
        }

        let lb = UILabel()
        lb.backgroundColor = .red
        lb.numberOfLines = 0
        lb.text = "ajkdsbfklahsjklfhajklsanhjks"
        lb.configureLayout { (layout) in
            layout.isEnabled = true
            layout.maxWidth = 200
            layout.paddingLeft = 10
            layout.paddingTop = 20
            layout.paddingRight = 40
            layout.paddingBottom = 80
    //            layout.borderWidth = 10
        }
        view.addSubview(lb)
        view.yoga.applyLayout(preservingOrigin: true)
    }
![img_e895d7b14a35-1](https://user-images.githubusercontent.com/6056572/39223253-87094dd6-4873-11e8-8258-7e5a57d05259.jpeg)

**Comment by linqingmo** [comment]
Padding and border only works for subviews. In this case label doesn't have a subview, so padding or border will not work.

**Comment by harryzjm** [comment]
@linqingmo Thank you for your help. I got it
