### ISSUE TITLE
tvOS Support

### ISSUE THREAD

**Issue by glenwong** [facebook/yoga#764]
It would be great if yoga could add tvOS as a supported platform.

**Comment by cntrump** [comment]
supported in my PR: https://github.com/facebook/yoga/pull/913

**Comment by NickGerleman** [comment]
We are deprecating YogaKit as part of the Yoga 2.0 release. We are still going to release a new revision based on the current state of the repo, but won't be accepting new contributions, since we are going to be removing it from the repo after.
