### ISSUE TITLE
About Translation in korean this document(website)

### ISSUE THREAD

**Issue by Lutece** [facebook/yoga#765]
Hello!

I am a front-end developer living in Korea.

Recently me and some other developers studied about ‘Flex layout’ with Yoga Documentation and we were able to understand it well since it was a very well written one.

And it made me wanna share it with other front-end developers in Korea.

I made a team for translating.

I want to ask if it’s okay to translate the document and share it.

We will look forward to your reply!

**Comment by NickGerleman** [comment]
Please feel free to translate the original documentation!
