### ISSUE TITLE
setFlexBasisAuto is not a function

### ISSUE THREAD

**Issue by samwalshnz** [facebook/yoga#766]
# Issues and Steps to Reproduce
1. `npm install yoga-layout`
2. Attempt to call `node.setFlexBasisAuto()` - where `node` is a `Node` instance

# Expected Behavior
Should set the flex basis to auto

# Actual Behavior
Error: `node.setFlexBasisAuto is not a function`

Note that the [setFlexBasisAuto function is missing from entry-common.js](https://github.com/facebook/yoga/blob/master/javascript/sources/entry-common.js#L181)

**Comment by samwalshnz** [comment]
Note: For now, until `setFlexBasisAuto` is added like the other functions, I've discovered the following alternative:
```
import yoga, {Node} from 'yoga-layout';

const node = Node.create();
node.setFlexBasis(yoga.UNIT_AUTO)
```

**Comment by kevinresol** [comment]
So adding a function declaration to flow type will make the function available in the Node object? I wonder how this magic works...
Anyway, I would like to see a fix for `setFlexBasisAuto` anyway

**Comment by zythum** [comment]
For now, set `NaN` instead. it worked for me.
```
if (flexBasisValue ===  'auto') {
  node.setFlexBasis(NaN)
}
```
