### ISSUE TITLE
iOS - YogaKit - Safe Area Layout Guides

### ISSUE THREAD

**Issue by sflahave** [facebook/yoga#774]
Is there a way to use safe-area layout guides in YogaKit? For example, I needed to position a button so that it was always just above the tab bar (but I could not assume that a tab bar would always be present). It seemed that there was no good way to do this with YogaKit, so I resorted to using AutoLayout for that.

**Comment by sflahave** [comment]
@Damoness - thanks that seems to do the trick.

**Comment by andrewalfb** [comment]
> you can set the UIViewController's edgesForExtendedLayout to UIRectEdgeNone, and add " [self.view.yoga applyLayoutPreservingOrigin:YES];" in viewWillLayoutSubviews.

Does not work for me. I did so:
1) in viewDidLoad - self.edgesForExtendedLayout = []
2) ```
override func viewDidLayoutSubviews() {
        super.viewDidLayoutSubviews()
        view.yoga.applyLayout(preservingOrigin: true)
}
```
