### ISSUE TITLE
Setting percentage margin causes view's height change

### ISSUE THREAD

**Issue by Norcy** [facebook/yoga#780]
Setting margin property with percentage value will change view's height in iOS(YogaKit).

# Issues and Steps to Reproduce
The html's pseudocode following can reproduce this bug
```html
<div width="100%" height="100%" background-color="gray" flex-direction="row" justify-content="center">
    <label width="100px" height="100px" background-color="#0000FFFF" margin-top="0px">1</label>
    <label width="100px" height="100px" background-color="#FF00FFFF" margin-top="100px">2</label>
    <label width="100px" height="100px" background-color="#FF0000FF" margin-top="10%">3</label>
    <label width="100px" height="100px" background-color="#00FF00FF" margin-top="20%">4</label>
</div>
```

# Expected Behavior
The expected behaviour is as follows:

![image](https://user-images.githubusercontent.com/8423011/40964176-fe4020a8-68dc-11e8-93cd-dcd2a16aaa2b.png)

# Actual Behavior
Pay attention to the child node's height instead of root node or color.
The third child node and fourth child node both have a wrong height.
![image](https://user-images.githubusercontent.com/8423011/40965502-754b186c-68e0-11e8-804a-30cc106f82e5.png)

According to the [Yoga's playground's effect](https://yogalayout.com/playground/#eyJ3aWR0aCI6NTAwLCJoZWlnaHQiOjUwMCwibWluV2lkdGgiOm51bGwsIm1pbkhlaWdodCI6bnVsbCwibWF4V2lkdGgiOm51bGwsIm1heEhlaWdodCI6bnVsbCwianVzdGlmeUNvbnRlbnQiOjEsInBvc2l0aW9uIjp7InRvcCI6bnVsbCwicmlnaHQiOm51bGwsImJvdHRvbSI6bnVsbCwibGVmdCI6bnVsbH0sImNoaWxkcmVuIjpbeyJ3aWR0aCI6MTAwLCJoZWlnaHQiOjEwMCwibWluV2lkdGgiOm51bGwsIm1pbkhlaWdodCI6bnVsbCwibWF4V2lkdGgiOm51bGwsIm1heEhlaWdodCI6bnVsbCwicG9zaXRpb24iOnsidG9wIjpudWxsLCJyaWdodCI6bnVsbCwiYm90dG9tIjpudWxsLCJsZWZ0IjpudWxsfX0seyJ3aWR0aCI6MTAwLCJoZWlnaHQiOjEwMCwibWluV2lkdGgiOm51bGwsIm1pbkhlaWdodCI6bnVsbCwibWF4V2lkdGgiOm51bGwsIm1heEhlaWdodCI6bnVsbCwibWFyZ2luIjp7InRvcCI6IjEwMCJ9LCJwb3NpdGlvbiI6eyJ0b3AiOm51bGwsInJpZ2h0IjpudWxsLCJib3R0b20iOm51bGwsImxlZnQiOm51bGx9fSx7IndpZHRoIjoxMDAsImhlaWdodCI6MTAwLCJtaW5XaWR0aCI6bnVsbCwibWluSGVpZ2h0IjpudWxsLCJtYXhXaWR0aCI6bnVsbCwibWF4SGVpZ2h0IjpudWxsLCJtYXJnaW4iOnsidG9wIjoiMTAlIn0sInBvc2l0aW9uIjp7InRvcCI6bnVsbCwicmlnaHQiOm51bGwsImJvdHRvbSI6bnVsbCwibGVmdCI6bnVsbH19LHsid2lkdGgiOjEwMCwiaGVpZ2h0IjoxMDAsIm1pbldpZHRoIjpudWxsLCJtaW5IZWlnaHQiOm51bGwsIm1heFdpZHRoIjpudWxsLCJtYXhIZWlnaHQiOm51bGwsIm1hcmdpbiI6eyJ0b3AiOiIyMCUifSwicG9zaXRpb24iOnsidG9wIjpudWxsLCJyaWdodCI6bnVsbCwiYm90dG9tIjpudWxsLCJsZWZ0IjpudWxsfX1dfQ==), the behaviour in iOS should be a bug I think.

# Link to Code
After reading the source code, I've found the possible reason of this bug.
![image](https://user-images.githubusercontent.com/8423011/40964973-0ad6bd3e-68df-11e8-83a2-75f86d1bae2f.png)

Well, replacing `availableWidth` with `parentWidth` can fix it. 

If a margin property is a percentage value, it should be relative to it's parent node's size instead of it self.

Additionally, since the mistake is maked in `Yoga.c`, this bug will occurs not only in iOS but also other system platforms.

**Comment by nickolas-pohilets** [comment]
Looks like this was fixed in https://github.com/facebook/yoga/commit/b88cf7ff67317559ae378a19138a0ea7ffdf5df6, but the latest stable release (1.18.0) still does not have this fix

**Comment by NickGerleman** [comment]
1.19.0 should be released
