### ISSUE TITLE
Way to get absolute position in nested layout?

### ISSUE THREAD

**Issue by Robert-M-Muench** [facebook/yoga#787]
YGNodeLayoutGetLeft() and YGNodeLayoutGetTop() return values relative to the parent.

Is there a way to get the absolute values in a nested layout that adds up all the parent positions?

**Comment by KitsuneAlex** [comment]
I know this is a bit late but did you get this sorted out? The C++ documentation is kinda sparse and i've been struggeling with the exact same problem for a while now. Thanks in advance :)

**Comment by Robert-M-Muench** [comment]
There is no function you can use.

I solve this by tracking the absolute positions `ax` and  `ay` manually and updated them while traversing the layout tree on any layout changes. Works and doesn't add too much run-time overhead.

**Comment by KitsuneAlex** [comment]
Yeah i figured a way out myself, i just retrieve the X and Y position of my component in question, then check if it has a parent and if so, add it's X and Y to the component's X and Y, then return the result. Works pretty nicely :D
