### ISSUE TITLE
User Payload for YGNode

### ISSUE THREAD

**Issue by Robert-M-Muench** [facebook/yoga#788]
Because Yoga only handles the layout, which is great, it somehow needs to be integrated into a broader application context. Within a scene drawing function, it's enough to traverse the Yoga tree. 

However, sometimes it's necessary to get from a YGNode(Ref) to the application context, let's say a struct. Here it would help a lot if I could store a user-pointer with a YGNode, which I can use to access application specific things from a YGNode.

**Comment by woehrl01** [comment]
@Robert-M-Muench depending on the language binding you use, you have a possibility store youre context. In the native C API, you can use `getContext` and `setContext` to access and store an arbitrary data pointer.
