### ISSUE TITLE
Top percent applied to an item in a vertical container give undesired results (c++)

### ISSUE THREAD

**Issue by sanjayQ** [facebook/yoga#792]
# Issues and Steps to Reproduce
1. Create a flex node
2. Add another flex node inside the first.
3. Make the parent flex container as "vertical" direction.
4. apply top % to the inside flex item.

# Expected Behavior
![toppercentyogaexpected](https://user-images.githubusercontent.com/40636203/42367927-4a6ff77e-8123-11e8-85b5-aff379342272.PNG)

# Actual Behavior
![toppercentyogaissue](https://user-images.githubusercontent.com/40636203/42367850-16804bf8-8123-11e8-9467-21094e503e6e.PNG)

**Comment by woehrl01** [comment]
Hi @sanjayQ,

I know it's a long time ago you posted that issue. Unfortunately I'm not able to reproduce that with the latest version, with your described steps.

I have the following layout, does that match your issue? (Default values compared to the web apply, see: https://jsfiddle.net/emilsjolander/jckmwztt/) 


```html
<div id="percent_top_with_flex_direction_column" style="width: 500px; height: 250px; flex-direction: column;">
  <div style="top: 20%; height: 20px"> 
  </div>
</div>
```
