### ISSUE TITLE
YogaKit Xcode 9.4 won't build, giving "Include of non-modular header inside of framework module" errors

### ISSUE THREAD

**Issue by fenghuang** [facebook/yoga#794]
I have a project that adds YogaKit through Cocoapods, and in Xcode 9.2 it compiles just fine. However, in Xcode 9.4 it fails to build, citing three "Include of non-modular header inside framework module" errors in YGLayout.h. The errors are on the import statements for yoga/YGEnums.h, yoga/Yoga.h, and yoga/YGMacros.h.

I've tried a whole host of common solutions to no avail, including setting Allow Non-modular Includes In Framework Modules to Yes in both my target Build Settings and the Build Settings for Yoga and YogaKit through the Podfile. There's an open PR that changes the offending import statements to a single `@import yoga;` statement, but Xcode doesn't really want you doing this and it resets every time pod install is run so it's not a practical solution.

**Comment by hahtml** [comment]
Bump

**Comment by NickGerleman** [comment]
Please reopen if this happens on a more recent version of Yoga and XCode
