### ISSUE TITLE
How to work with Rollup

### ISSUE THREAD

**Issue by RockyF** [facebook/yoga#798]
I just import yoga-layout with Rollup, 
`npm config set yoga-layout:platform browser`
and here is warnings:

> test3@1.0.0 build /Users/rockyl/WorkSpaces/flex/test3
> rollup -c
> src/main.js → dist/bundle.js...
> (!) Unresolved dependencies
> https://github.com/rollup/rollup/wiki/Troubleshooting#treating-module-as-external-dependency
> path (imported by node_modules/nbind/dist/nbind.js, commonjs-external:path)
> created dist/bundle.js in 164ms

I guess it's NPM that points to the entrance to node, So I manually modified the package.json
`"main": "./dist/entry-node",` ==> `"main": "./dist/entry-browser",`
and build successed.
But running the times in a browser is wrong:

> nbind.js:1146 Uncaught ReferenceError: _a is not defined
>     at nbind.js:1146
>     at nbind.js:1590
>     at entry-browser.js:21

So, how to work with Rollup?

**Comment by liajoy** [comment]
@RockyF have this issue been sovled? I got the same problem with rollup

**Comment by liajoy** [comment]
a simple rollup plugin can solve this.
```javascript
plugins: [
    {
      name: 'replace-code',
      transform (code, id) {
        if (!/nbind/.test(id)) return
        code = code.replace('_a = _typeModule(_typeModule),', 'var _a = _typeModule(_typeModule);')
        return {
          code,
          map: { mappings: '' }
        }
      }
    }
]
```
