### ISSUE TITLE
How to use both yoga and autolayout?

### ISSUE THREAD

**Issue by Naixor** [facebook/yoga#799]
```
public class DynamicView: UIView {
    public override func draw(_ rect: CGRect) {
        self.configureLayout { (layout) in
            layout.isEnabled = true
            layout.width = YGValue(rect.width)
            layout.height = YGValue(rect.height)
        }

        self.yoga.applyLayout(preservingOrigin: true)
    }

    public override var intrinsicContentSize: CGSize {
        return self.yoga.intrinsicSize
    }
}
```

**Comment by passy** [comment]
Hi @Naixor, could you please provide some more information on what you're trying to achieve? This leaves us with a bunch of guess-work. Feel free to open another issue with more information.

**Comment by fairysspring** [comment]
A.configureLayout { (layout) in
            layout.isEnabled = true
            ---
        }
        root.addSubview(A)

        B = UIView(frame: .zero);
        B.mas_makeConstraint{
            
        }
        root .addSubview(B);   how could I mix autolayout and  yoga layout
