### ISSUE TITLE
Incorrect default value for flexShrink

### ISSUE THREAD

**Issue by artman** [facebook/yoga#801]
# Report

- [X] I have searched [existing issues](https://github.com/facebook/yoga/issues) and this is not a duplicate

# Issues and Steps to Reproduce
On iOS, construct a UIView and inspect its `view.yoga.flexShrink` value.

# Expected Behavior
Expect the default value for flexShrink to be 1 (as per web standards and Yoga Layout documentation)

# Actual Behavior
Default value for flexShrink is 0.

**Comment by artman** [comment]
It seems that Yoga diverges on purpose from web standards unless `useWebDefaults` is specified. In this case it would make sense to update the documentation with the correct default value.

**Comment by passy** [comment]
cc @priteshrnandgaonkar

**Comment by Titozzz** [comment]
FYI Doc was updated: https://github.com/facebook/react-native-website/pull/2451

**Comment by NickGerleman** [comment]
Now documented at https://www.yogalayout.dev/docs/styling/#default-styles
