### ISSUE TITLE
YogaKit Missing Documentation

### ISSUE THREAD

**Issue by DavidQL** [facebook/yoga#806]
The YogaKit documentation is no longer available.

https://yogalayout.com/docs/api/yogakit/

**Comment by hahtml** [comment]
Could we bring YogaKit docs back?

**Comment by NickGerleman** [comment]
We are deprecating YogaKit as part of the Yoga 2.0 release. We are still going to release a new revision based on the current state of the repo, but won't be accepting new contributions, since we are going to be removing it from the repo after.
