### ISSUE TITLE
Flex-direction values in generated React Native code are invalid

### ISSUE THREAD

**Issue by dhruska** [facebook/yoga#807]
# Report

- [x] I have searched [existing issues](https://github.com/facebook/yoga/issues) and this is not a duplicate

# Issues and Steps to Reproduce
Generated React Native code uses incorrect `flex-direction` values.

To reproduce, go to https://yogalayout.com, select `flex direction`: `column reverse`, and then click `Get Code` -> `React Native`. The generated `style` prop in the `View` container will have `flexDirection: 'ltr'`, when it really should have `flexDirection: 'column-reverse'`.

I think this could be rectified by changing the value of `flexDirection` in `JSEnumLookup` within `CodeJavaScript` from `DIRECTION_` to `FLEX_DIRECTION_` ([code here](https://github.com/facebook/yoga/blob/master/website/src/components/Playground/CodeJavaScript.js#L23)). It also might be necessary to change the enum to `FLEXDIRECTION` due to the regex used [here](https://github.com/facebook/yoga/blob/master/website/src/components/Playground/CodeReactNative.js#L37) and [here](https://github.com/facebook/yoga/blob/master/website/src/components/Playground/CodeLitho.js#L40).

# Expected Behavior
Valid values for `flex-direction` should be used in the generated code in Yoga, such as [`row`, `row-reverse`, `column` or `column-reverse`](https://facebook.github.io/react-native/docs/layout-props#flexdirection).

# Actual Behavior
Invalid values for `flex-direction` are being used in the generated React Native code in Yoga - [they appear to be for the `DIRECTION` enum](https://facebook.github.io/react-native/docs/layout-props#direction). Values such as `ltr` and `count` are being used.

If this is indeed a real bug and I'm just not misreading things, I'd be happy to submit a PR.

**Comment by dhruska** [comment]
Related, but different: https://github.com/facebook/yoga/issues/732

**Comment by NickGerleman** [comment]
We are building a new playground as part of a website migration. There is no longer an option to translate to code, but the input is JSX https://yoga-website-next-fbopensource.vercel.app/
