### ISSUE TITLE
What is 'laid our' in the document?

### ISSUE THREAD

**Issue by krave1986** [facebook/yoga#808]
# Report
Maybe I didn't get the point.
But I guess that there may be some typo on document about Layout Direction in this [link](https://yogalayout.com/docs/layout-direction/).

- [ ] I have searched [existing issues](https://github.com/facebook/yoga/issues) and this is not a duplicate

# Issues and Steps to Reproduce
***Replaces this with steps to repro your issue.***

> LTR (DEFAULT) Text and children and _**laid our**_ from left to right. Margin and padding applied the start of an element are applied on the left side.

> RTL Text and children and **_laid our_** from right to left. Margin and padding applied the start of an element are applied on the right side.

# Expected Behavior
***Describe what you expected would happen.***
LTR (DEFAULT) Text and children are laid out from left to right. Margin and padding applied the start of an element are applied on the left side.

RTL Text and children are laid out from right to left. Margin and padding applied the start of an element are applied on the right side.

# Actual Behavior
***Describe what actually happened.***

# Link to Code
***If you have some code that maintainers can clone/test for themselves, bugs can be resolved much faster. Please paste a link here.***

***When applicable, use this [fiddle](https://jsfiddle.net/emilsjolander/jckmwztt/) to post a web repro.***

**Comment by PabloSichert** [comment]
This can be closed -has been fixed with https://github.com/facebook/yoga/pull/833

**Comment by krave1986** [comment]
@PabloSichert Thanks.
