### ISSUE TITLE
Open Source Adoption list petition 😄

### ISSUE THREAD

**Issue by diegomura** [facebook/yoga#809]
Hey!
First just wanted to say how awesome I think Yoga is. It really helps to shrink the distance between the web and so many different environments through the flexbox api. Thanks for your hard work pushing this project forward!

I'm the creator and maintainer or [react-pdf](https://github.com/diegomura/react-pdf), a PDF React renderer to create documents both client and server side. The project was nicely adopted by the community, and has proven to be valuable in production for many companies up to this date.

Yoga has been one of the foundation stones of the project almost from day one, and is the main reason why you can now easily create and layout PDF documents using JSX and Flexbox, which IMO is truly great.

I recently saw that the Yoga landing page has an Open Source Adoption list with some projects using it, and I thought it would be very cool to add react-pdf to that list, specially because it's also related with the React ecosystem. I can help with anything needed to do so. What do you think?

Thanks in advance 😄

**Comment by diegomura** [comment]
Thanks for the input @itzsaga ! Didn't know the site was hosted here also. I would be happy to do it but not sure if it would be merged then

**Comment by RodrigoEspinosa** [comment]
@sophiebits & @vjeux, would love to see this happen. Let me know if I can help! 😊

**Comment by vjeux** [comment]
@davidaurelio is now maintaining Yoga. I'll let him figure things out :)

**Comment by davidaurelio** [comment]
@diegomura would you mind sending a PR for https://github.com/facebook/yoga/blob/master/website/src/pages/index.js? Thanks!
