### ISSUE TITLE
Multiple static runtimes in Android NDK 

### ISSUE THREAD

**Issue by afjoseph** [facebook/yoga#813]
This is more of a question rather than an issue: [C++ Library Support guide](https://developer.android.com/ndk/guides/cpp-support#one_stl_per_app) in developer.android mentions that only multiple STLs defined in a single app can cause numerous unknown issues. 

Here's the relevant excerpt from the document:
```
In this situation, the STL, including and global data and static constructors,
will be present in both libraries. The runtime behavior of this application is
undefined, and in practice crashes are very common. Other possible issues
include:

 * Memory allocated in one library, and freed in the other, causing memory
   leakage or heap corruption.
 * Exceptions raised in `libfoo.so` going uncaught in `libbar.so`, causing your
   app to crash.
 * Buffering of `std::cout` not working properly.

```

There's also[ another older document](https://android.googlesource.com/platform/ndk/+/ics-mr0/docs/CPLUSPLUS-SUPPORT.html) in the NDK repo that mentions the same
```

On the other hand, if you have two shared libraries in your project
--
  | (e.g. libfoo.so and libbar.so) which both link against the same static
  | runtime, each one of them will  include a copy of the runtime's code in
  | its final binary image. This is problematic because certain global
  | variables used/provided internally by the runtime are duplicated.

```

I see that both [`libyoga.so`](https://github.com/facebook/yoga/blob/master/java/build.gradle) and [`libfb.so`](https://github.com/facebook/yoga/blob/master/lib/fb/build.gradle)  use `c++_static` runtime, which means that any other 3rd-party library existing in the app must use `c++_shared` or they might cause and incompatibility issue since using something like `gnustl_static` will cause multiple versions of the STL to exist in the same app multiple times.

I think the default for r18 will be `c++_shared` according to [one of the main maintainers](https://github.com/android-ndk/ndk/issues/744#issuecomment-406099077) of the NDK project.

Can you please advise if the scenario above is possible? Also, do you think it would be wise to simply make both with a `c++_shared` STL.

Thanks again

**Comment by NickGerleman** [comment]
Taking a look at this

https://developer.android.com/ndk/guides/middleware-vendors#using_the_stl

> If you distribute a shared library, you must either use libc++_shared or ensure that libc++'s symbols are not exposed by your library.

We compile libyoga with `-fvisibility-hidden` or similar CMake Visibility preset, so libyoga should not be reexporting libc++ symbols. I think. libfb doesn't exist anymore separately.

On https://developer.android.com/ndk/guides/cpp-support#shared_runtimes

> Caution: JNI libraries distributed with Java AARs must not use the shared runtime to avoid conflicting with other libraries and the app. The warnings below still apply. See the documentation for [Middleware Vendors](https://android.googlesource.com/platform/ndk/+/refs/heads/master/docs/user/middleware_vendors.md) for more information.

We also fit that category.


From those guidelines, we *should* use the static STL, but *should not* expose libc++ symbols, so I think the current setup meets the guidance.
