### ISSUE TITLE
gentests.rb broken with Chrome 67+

### ISSUE THREAD

**Issue by artdent** [facebook/yoga#822]
# Report

- [x] I have searched [existing issues](https://github.com/facebook/yoga/issues) and this is not a duplicate

# Issues and Steps to Reproduce
```
ruby gentest/gentest.rb
git diff
buck test //:yoga
```

# Expected Behavior
- Clean diff
- Tests build and pass
***Describe what you expected would happen.***

# Actual Behavior
- `git diff` adds lines like `YGNodeStyleSetMinWidthAuto(root_child0_child0, YGAuto);` to `tests/YGAbsolutePositionTest.cpp`, `root_child0_child0.setMinWidth("auto");` to `javascript/tests/Facebook.Yoga/YGAbsolutePositionTest.js`, etc.
- `buck test //:yoga` fails compilation with `error: use of undeclared identifier 'YGAuto'`.

Here's an example of a test fixture with changed behavior, from YGAbsolutePositionTest.html:
```
<div id="do_not_clamp_height_of_absolute_node_to_height_of_its_overflow_hidden_parent" style="height: 50px; width: 50px; overflow: hidden; flex-direction: row;">
  <div style="position: absolute; start: 0px; top: 0px;">
    <div style="width: 100px; height: 100px;"></div>
  </div>
</div>
```

Current Chrome (69) describes the innermost div as having a computed `min-width` of `auto`. I had to go back to Chromium 66 to find a version that doesn't cause gentest.js to add min-width: auto to the generated tests.

It's not obvious to me whether the newly added min-width lines are reasonable, in which case the solution is to fix the build errors, or whether the newly added lines are extraneous and `gentest.js` should try not to emit them.

**Comment by NickGerleman** [comment]
Test generation should work correctly as of fd180de774824b9b639ddb7fb43d87e983a7c248
