### ISSUE TITLE
inconsistent default for `flexDirection` and `flexShrink`

### ISSUE THREAD

**Issue by rozzzly** [facebook/yoga#835]
- [X] I have searched [existing issues](https://github.com/facebook/yoga/issues) and **this is totally a duplicate**_—we don't like having to nag you either, so tie your damn shoes._

#### Reproduction (js api)
```javascript
import * as yoga from 'yoga-layout';

const node = yoga.Node.create();
assert(node.getFlexDirection() === 2); // expected: 2 (row), actual: 0 (column)
assert(node.getFlexShrink() === 1); // expected: 1, actual: 0
```

### Expected
  * `flexDirection` defaults to `row` _**[[as specified in the docs]](https://yogalayout.com/docs/flex-direction)**_
  * `flexShrink` defaults to `1` _**[[as specified in the docs]](https://yogalayout.com/docs/flex)**_
### Actual
  * `flexDirection` defaults to `column`
  * `flexShrink` defaults to `0`

While I was creating this issue, I found #209 from back in 2016 so this is a known issue.

If the yoga team wants to use their own set of defaults which differ from the W3C spec, that's fine. **But your docs should not _explicitly_ state something false!** 💢

Anyway, thanks for providing this package, I find it very useful!

**Comment by NickGerleman** [comment]
This seems like a documentation issue, where the webpage does not acknowledge the need for UseWebDefaults for style defaults consistent with web.

**Comment by NickGerleman** [comment]
Now documented at https://www.yogalayout.dev/docs/styling/#default-styles
