### ISSUE TITLE
Yoga CocoaPod restricting compatible platforms

### ISSUE THREAD

**Issue by pablosichert** [facebook/yoga#837]
Hi there! Since Yoga is written in portable C/C++, I don't understand the rationale behind restricting the CocoaPod to iOS/tvOS only.

If you could consider lifting the restrictions, the Pod could be used on other platforms, without forking the core and diverging from the current implementation.

In my specific case, I want to use the Yoga Pod to implement bindings for AppKit/macOS. Ideally I'd like to share them upstream if you consider it useful (as I currently see, the maintenance/community efforts seem to be quite strapped at the moment).

**Issues and Steps to Reproduce**
```
$ pod install
Analyzing dependencies
[!] The platform of the target `Example` (macOS 10.13) is not compatible with `YogaKit (1.9.0)`, which does not support `osx`.
```

Please also see pull request https://github.com/facebook/yoga/pull/821, which would lift the platform restrictions.

---

- [x] I have searched [existing issues](https://github.com/facebook/yoga/issues) and this is not a duplicate

**Comment by priteshrnandgaonkar** [comment]
cc @davidaurelio @SidharthGuglani
