### ISSUE TITLE
flex-grow works wrong compared with the browsers

### ISSUE THREAD

**Issue by qcclcr** [facebook/yoga#840]
@davidaurelio # Report

- [x] I have searched [existing issues](https://github.com/facebook/yoga/issues) and this is not a duplicate

# Issues and Steps to Reproduce
 root node height is 500px, when I set flex-grow (1) to a node,  and the parent node height length is unset, then the node will get height 0,  different to web which get 500px. 

# Expected Behavior
 same as web

# Actual Behavior
  get zero

# Link to Code
```
<html>
<body>
  <div class="root" style="flex-direction:column; width:750px; height:500px;">
    <div class="unsetHeight" style="flex-direction:column; width:750px;">
      <div class="flexGrowItem" style="flex-direction:column; flex: 1 1 0; background-color: rgba(223,223,0,0.9);">
        <text class="text" style="font-size: 40px; color: black;">Hello World!</text>
      </div>
    </div>
  </div>
</body>
</html>

```

***When applicable, use this [fiddle](https://jsfiddle.net/emilsjolander/jckmwztt/) to post a web repro.***

**Comment by qcclcr** [comment]
this is the html code 

<html>
<body>
  <div class="root" style="flex-direction:column; width:750px; height:500px;">
    <div class="unsetHeight" style="flex-direction:column; width:750px;">
      <div class="flexGrowItem" style="flex-direction:column; flex: 1 1 0; background-color: rgba(223,223,0,0.9);">
        <text class="text" style="font-size: 40px; color: black;">Hello World!</text>
      </div>
    </div>
  </div>
</body>
</html>

**Comment by davidaurelio** [comment]
Thanks for reporting. Does your config use web defaults or not?

**Comment by emilsjolander** [comment]
A quick look makes me assume ‘flex: 1 1 0’ is the issue as everything else looks pretty normal. This sets flex-basis to 0px which is something yoga has had issues with before if the node with flex basis itself has children with a larger size.

Without a repro I can’t be sure but that would be my best guess. You putting this through the test generation script though (make sure it handles flex property first otherwise re-write it using flex -grow/-shrink/-basis)

**Comment by qcclcr** [comment]
> Thanks for reporting. Does your config use web defaults or not?

yes, i have tried both useWebDefauls ，it is the same

> Thanks for reporting. Does your config use web defaults or not?
i have not configured,  it seems that  when user set "flex", if i  split it to flexGrow,flexShrink,flexbasis is ok, otherwise when i just set flex in YGStyle it is different
