### ISSUE TITLE
iOS YogaKitSample build Err

### ISSUE THREAD

**Issue by helloXixi** [facebook/yoga#853]
# Report
you should remove this file /YogaKit/YogaKitSample/Podfile.lock
this file include Yoga version 1.7.0 which is out of date, when i download and run 'pod install' will tips Err.
you should delete this file and submit source code again, thanks.

**Comment by cntrump** [comment]
Fixed and updated in my PR: https://github.com/facebook/yoga/pull/1026

**Comment by NickGerleman** [comment]
We are deprecating YogaKit as part of the Yoga 2.0 release. We are still going to release a new revision based on the current state of the repo, but won't be accepting new contributions, since we are going to be removing it from the repo after.
