### ISSUE TITLE
Bump yoga podspec to 1.11 or 1.12?

### ISSUE THREAD

**Issue by Adlai-Holler** [facebook/yoga#863]
# Report

- [x] I have searched [existing issues](https://github.com/facebook/yoga/issues) and this is not a duplicate

Right now the YogaKit podspec points to 1.9.0 from 1.11.0. For users who don't need YogaKit, there's no way to get yoga itself through CocoaPods today. Can we bump that and push to specs repo?

**Comment by NickGerleman** [comment]
A newer pod has been released (and a new one will release soon) see  https://cocoapods.org/pods/YogaKit
