### ISSUE TITLE
Website component for Copy to Clipboard does not work in iOS Safari

### ISSUE THREAD

**Issue by galtenberg** [facebook/yoga#871]
# Report

- [x] I have searched [existing issues](https://github.com/facebook/yoga/issues) and this is not a duplicate

# Issues and Steps to Reproduce
- On iOS Safari, open https://yogalayout.com/playground
- In the right-hand panel, click Get Code, select any option
- Click 'copy to clipboard'
- Code is not on system clipboard

# Expected Behavior
- Code should be on system clipboard

# Actual Behavior
- System clipboard is unchanged

**Comment by NickGerleman** [comment]
We are building a new playground as part of a website migration. Clipboard button is working correct there https://yoga-website-next-fbopensource.vercel.app/
