### ISSUE TITLE
Swift version

### ISSUE THREAD

**Issue by KelaKing** [facebook/yoga#875]
# Report

- [x] I have searched [existing issues](https://github.com/facebook/yoga/issues) and this is not a duplicate

# Issues and Steps to Reproduce
<img width="423" alt="屏幕快照 2019-03-20 11 47 29" src="https://user-images.githubusercontent.com/13584044/54663095-2052ac80-4b1b-11e9-9ecb-fb83a603d8cd.png">

# Expected Behavior
Migrate the code to swift 4

# Actual Behavior
**YogaKit.podspec**
```diff
-spec.swift_version = '3.0'
+spec.swift_version = '4.2'
```

**Comment by PatrickNLT** [comment]
I submitted a PR: https://github.com/facebook/yoga/pull/878

**Comment by denisenkoaj** [comment]
Is there any plans to merge?

**Comment by PatrickNLT** [comment]
Fixed by d44a6d936fc6666fa509a0e4bdff209a8d22d381
