### ISSUE TITLE
Skipped layouts do not get rounded

### ISSUE THREAD

**Issue by Adlai-Holler** [facebook/yoga#877]
# Report

- [x] I have searched [existing issues](https://github.com/facebook/yoga/issues) and this is not a duplicate

# Issues and Steps to Reproduce
***Replaces this with steps to repro your issue.***
- Calculate layout on a tree such that the internal result requires rounding e.g. `{0, 200.015}`.
- The external result i.e. the width of the yoga layout will be rounded `{0, 200}`.
- Without dirtying the tree, calculate layout again with the same constraints.

# Expected Behavior
***Describe what you expected would happen.***
- The width of the node's layout should still be the same, and still rounded `{0, 200}`.

# Actual Behavior
***Describe what actually happened.***
- The width of the node is not rounded `{0, 200.015}`

Stepping through the code, I see that the second call gets `YGLayoutNodeInternal` returning `false`, which makes sense. `YGRoundToPixelGrid` is only called if `YGLayoutNodeInternal` returns `true` i.e. we don't round if the layout was skipped. code is here https://github.com/facebook/yoga/blob/14f3827491e9d1f14d0c098e48a1776d8371e08d/yoga/Yoga.cpp#L4094

An easy fix would be to unconditionally call `YGRoundToPixelGrid` before continuing, or to call it on the inside of `YGNodeLayoutInternal`, or (ideally) not to touch the layout in the case that it was skipped.

**Comment by Adlai-Holler** [comment]
Here's a snippet for a unit test that covers this, that I added to Texture: 

```objc
YGSize _measureFraction(YGNodeRef node,
                          float width,
                          YGMeasureMode widthMode,
                          float height,
                          YGMeasureMode heightMode) {
  NSCAssert(width != YGUndefined, @"Expected fixed width in measure function.");
  *(int *)YGNodeGetContext(node) += 1;
  return (YGSize){
      .width = width,
      .height = 100.75
  };
}

// Test for fix for https://github.com/facebook/yoga/issues/877
- (void)testYogaLayoutIsRoundedEvenIfCached
{
  YGNodeRef node = YGNodeNew();
  int *measureCount = new int(0);
  YGNodeSetContext(node, measureCount);
  YGNodeSetMeasureFunc(node, &_measureFraction);
  YGNodeCalculateLayout(node, 100, YGUndefined, YGDirectionInherit);
  XCTAssertEqual(YGNodeLayoutGetHeight(node), 101.0);
  YGNodeCalculateLayout(node, 100, YGUndefined, YGDirectionInherit);
  XCTAssertEqual(YGNodeLayoutGetHeight(node), 101.0);
  XCTAssertEqual(*measureCount, 1);
  delete measureCount;
  YGNodeFree(node);
}
```

**Comment by NickGerleman** [comment]
Current code rounds whole tree https://github.com/facebook/yoga/blob/c54e0e7fed30b8aa7a2cae0a180a6620d6137c8b/yoga/algorithm/PixelGrid.cpp#L65

This is separately kinda wasteful and not what we want for unowned nodes, but this specific bug should likely no longer exists.
