### ISSUE TITLE
Multi-step logging causes problems, especially when multithreading

### ISSUE THREAD

**Issue by Adlai-Holler** [facebook/yoga#879]
Currently the common logging pattern in yoga is like:

```
YGLog(YGLogLevelVerbose, "{1.")
YGPrint(node)
YGLog(YGLogLevelVerbose, "} d: 100 200")
```

This causes a few problems on the receiving side.
- When multithreading, the association between the three logs is broken.
- When using a logging system like iOS's `os_log` or `NSLog`, each log statement has a preamble (timestamp, module, thread, etc). We don't want to repeat this preamble 3 times for what is really one statement.
- The YGPrint callback isn't associable with the other two. It doesn't have a level etc.

I currently set up my logging callback to know this pattern, and to ignore the Print call and combine the other two into one log statement.

Unfortunately, since this pattern is only _mostly_, not _always_, my little setup breaks if another single-log comes through.

Would the authors of Yoga accept deprecating the Print API, and replacing it with a `void YGDescribeFunc(YGNodeRef node, const char *buf, int buf_size)` where Yoga gives me a little buffer (maybe 32 chars or whathaveyou) into which I can put a description of the node?

**Comment by NickGerleman** [comment]
It looks like https://github.com/facebook/yoga/commit/1b9053bc5dbc3b8f10e11d35b8765d81a3c61571 moved the referenced logging APIs to be internal to Yoga.

The `YGLogger` type supplied by users does accept a node ref, so a solution for this could be to maintain an external mapping of nodes to debug string.
