### ISSUE TITLE
Anyone interested in Dart implementation?

### ISSUE THREAD

**Issue by lesnitsky** [facebook/yoga#883]
Hi,
I'm actively working with Flutter and dart, I wonder if anyone will be interested in porting yoga to dart?
Possible use case: alternative layout engine for mobile apps powered by skia and dart

**Comment by Dimous** [comment]
https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/rendering/flex.dart

**Comment by matheusribeirozup** [comment]
Hi guys, sorry for the two years delay 😅. Today I published [yoga_engine](https://pub.dev/packages/yoga_engine), a package that uses Yoga to implement Flexbox in Flutter. I hope they are still interested and that it serves them well. Any questions, suggestions for improvement or bugs found, let me know.

**Comment by NickGerleman** [comment]
Thanks for the contribution!
