### ISSUE TITLE
Build Yoga.dll with Visual Studio 2017

### ISSUE THREAD

**Issue by zedalaye** [facebook/yoga#888]
# Report

- [X] I have searched [existing issues](https://github.com/facebook/yoga/issues) and this is not a duplicate

# Issues and Steps to Reproduce

Unable to build Yoga.dll using buck (to be fair I think I don't know how to use buck to build Yoga)

So... I decided to open the Facebook.Yoga.Desktop.sln solution. I then selected the "Release" target and "x86" platform before "Regenerate" on the Native/yoga project.

Linking failed due missing files (YGFloatOptional.cpp), I removed that file reference from "Source Files". Then compilation succeeded but build failed due to missing symbols (YGValueZero, YGValueUndefined and YGValueAuto and the log methods)

I had to add YGValue.h and YGValue.cpp and log.h and log.cpp to the project then regenerate and... yipee ! compilation and linking succeeded.

Now I'm asking whether to port Yoga code in Delphi (Object Pascal) or to wrap that Yoga DLL...

**Comment by wqweto** [comment]
It's been like this since 1.8 (or when the rewrite in C++ happened).

Doubt the tests on Windows are running at all so use the compiled DLL on your own risk.

**Comment by NickGerleman** [comment]
The C# bindings have not had a dedicated maintainer. We are removing them from the repo as part of cleanup for the next OSS release of Yoga.
