### ISSUE TITLE
XCode Build error in iOS React-Native 0.59.2 (after upgrade)

### ISSUE THREAD

**Issue by afilp** [facebook/yoga#889]
# Report

- [x ] I have searched [existing issues](https://github.com/facebook/yoga/issues) and this is not a duplicate

# Issues and Steps to Reproduce
Upgraded a React Native project from v0.57.8 to 0.59.2

# Expected Behavior
Running the app in iOS using XCODE to work (Build fails)

# Actual Behavior
Build fails with the following message:

<img width="344" alt="Screenshot 2019-04-17 at 10 57 11" src="https://user-images.githubusercontent.com/7850073/56271611-8b36d980-6101-11e9-8c64-8392f1e74950.png">

In Text:
**Semantic Issue**
- Use of undeclared identifier 'YGEdgeCount' YGNodePrint.cpp
- No member named 'getValue' in 'YGFIoatOptional' YGNodePrint.cpp
- Use of undeclared identifier 'YGEdgeCount' YGNodePrint.cpp
- Use of undeclared identifier 'YGEdgeCount' YGNodePrint.cpp

# Link to Code
***If you have some code that maintainers can clone/test for themselves, bugs can be resolved much faster. Please paste a link here.***

***When applicable, use this [fiddle](https://jsfiddle.net/emilsjolander/jckmwztt/) to post a web repro.***

**Comment by andrewhartwig** [comment]
Any luck?

**Comment by Mizibi** [comment]
Same here, still stuck with this Issue
with : react-native 0.59.5
any solutions ?

**Comment by Mizibi** [comment]
I just hotfixed by pasting this file : 
https://github.com/facebook/react-native/blob/0.59-stable/ReactCommon/yoga/yoga/YGNodePrint.cpp

That seems to be without errors.

**Comment by asutula** [comment]
Had the same problem in my react native project after upgrading to react-native 0.59.5. Somehow, an old version of yoga was hanging around in node_modules. I deleted node_modules, then `yarn install`ed, then since I use cocoapods, ran `pod install` in my `ios` directory. Long story short, the latest version of yoga compiles fine. This problem is related to an outdated version cached locally.

**Comment by burntzen** [comment]
`pod repo update` in the ios folder > delete node_modules folder > yarn install > go for it

**Comment by ranganaudara** [comment]
Have you tried changing your build system in project settings? Files>Project Settings>Build Systems

**Comment by NickGerleman** [comment]
It looks like this issue is stale. Please create a new issue on the `react-native` repo if you encounter build errors with a recent version.
