### ISSUE TITLE
C API / using YGFlexDirectionRow(Reverse) => crash

### ISSUE THREAD

**Issue by Robert-M-Muench** [facebook/yoga#891]
# Report

Using either 
```
YGNodeStyleSetFlexDirection(root,YGFlexDirectionRowReverse);
YGNodeStyleSetFlexDirection(root,YGFlexDirectionRow);
 ```
crashes my program, whereas when I use YGFlexDirectionColumn(Reverse) things work.

# Issues and Steps to Reproduce

````
  YGNodeRef root = YGNodeNew();
  YGNodeStyleSetWidth(root, win.windowWidth - 100);
  YGNodeStyleSetHeight(root, win.windowHeight- 100);
  YGNodeStyleSetFlexDirection(root,YGFlexDirectionRow);
  YGNodeCalculateLayout(root, win.windowWidth, win.windowHeight, YGDirectionLTR);
````
The call the YGNodeCalculateLayout bombs.

**Comment by Robert-M-Muench** [comment]
This problem seems to be related to some signing problem reported in other issues.

I fixed it (at least for my current case) be a one-line change and adding an ``ùnsigned```

```#define YG_ENUM_BEGIN(name) enum name: unsigned````

**Comment by nick-thompson** [comment]
Thanks @Robert-M-Muench; I just hit the same issue and can confirm this fix worked here as well

**Comment by NickGerleman** [comment]
It seems like this issue has been likely resolved since being opened. Please reopen if you encounter the same crash on the current version of Yoga.
