### ISSUE TITLE
Undefined symbols for architecture x86_64:

### ISSUE THREAD

**Issue by hejunbinlan** [facebook/yoga#896]
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -arch x86_64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator12.2.sdk -L/Users/hejunbin/Library/Developer/Xcode/DerivedData/YogaDemo-cmlkazwdoecwedeupfwxqleflkhh/Build/Products/Debug-iphonesimulator -L/Users/hejunbin/Library/Developer/Xcode/DerivedData/YogaDemo-cmlkazwdoecwedeupfwxqleflkhh/Build/Products/Debug-iphonesimulator/Yoga -L/Users/hejunbin/Library/Developer/Xcode/DerivedData/YogaDemo-cmlkazwdoecwedeupfwxqleflkhh/Build/Products/Debug-iphonesimulator/YogaKit -F/Users/hejunbin/Library/Developer/Xcode/DerivedData/YogaDemo-cmlkazwdoecwedeupfwxqleflkhh/Build/Products/Debug-iphonesimulator -filelist /Users/hejunbin/Library/Developer/Xcode/DerivedData/YogaDemo-cmlkazwdoecwedeupfwxqleflkhh/Build/Intermediates.noindex/YogaDemo.build/Debug-iphonesimulator/YogaDemo.build/Objects-normal/x86_64/YogaDemo.LinkFileList -Xlinker -rpath -Xlinker @executable_path/Frameworks -mios-simulator-version-min=8.0 -dead_strip -Xlinker -object_path_lto -Xlinker /Users/hejunbin/Library/Developer/Xcode/DerivedData/YogaDemo-cmlkazwdoecwedeupfwxqleflkhh/Build/Intermediates.noindex/YogaDemo.build/Debug-iphonesimulator/YogaDemo.build/Objects-normal/x86_64/YogaDemo_lto.o -Xlinker -export_dynamic -Xlinker -no_deduplicate -Xlinker -objc_abi_version -Xlinker 2 -fobjc-arc -fobjc-link-runtime -ObjC -lYoga -lYogaKit -framework UIKit -Xlinker -sectcreate -Xlinker __TEXT -Xlinker __entitlements -Xlinker /Users/hejunbin/Library/Developer/Xcode/DerivedData/YogaDemo-cmlkazwdoecwedeupfwxqleflkhh/Build/Intermediates.noindex/YogaDemo.build/Debug-iphonesimulator/YogaDemo.build/YogaDemo.app-Simulated.xcent -lPods-YogaDemo -Xlinker -dependency_info -Xlinker /Users/hejunbin/Library/Developer/Xcode/DerivedData/YogaDemo-cmlkazwdoecwedeupfwxqleflkhh/Build/Intermediates.noindex/YogaDemo.build/Debug-iphonesimulator/YogaDemo.build/Objects-normal/x86_64/YogaDemo_dependency_info.dat -o /Users/hejunbin/Library/Developer/Xcode/DerivedData/YogaDemo-cmlkazwdoecwedeupfwxqleflkhh/Build/Products/Debug-iphonesimulator/YogaDemo.app/YogaDemo

Undefined symbols for architecture x86_64:
  "std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::__init(char const*, unsigned long)", referenced from:
      std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::basic_string<std::nullptr_t>(char const*) in libYoga.a(YGNodePrint.o)
  "std::__1::__basic_string_common<true>::__throw_length_error() const", referenced from:
      std::__1::enable_if<__is_forward_iterator<std::__1::__wrap_iter<char*> >::value, void>::type std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::__init<std::__1::__wrap_iter<char*> >(std::__1::__wrap_iter<char*>, std::__1::__wrap_iter<char*>) in libYoga.a(YGNodePrint.o)
  "std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::append(char const*, unsigned long)", referenced from:
      std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::append(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) in libYoga.a(YGNodePrint.o)
      std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > std::__1::operator+<char, std::__1::char_traits<char>, std::__1::allocator<char> >(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, char const*) in libYoga.a(YGNodePrint.o)
  "std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::basic_string(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)", referenced from:
      facebook::yoga::appendNumberIfNotAuto(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, YGValue) in libYoga.a(YGNodePrint.o)
      facebook::yoga::appendEdgeIfNotUndefined(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, facebook::yoga::detail::Values<9ul> const&, YGEdge) in libYoga.a(YGNodePrint.o)
      facebook::yoga::appendNumberIfNotZero(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, YGValue) in libYoga.a(YGNodePrint.o)
  "std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::append(char const*)", referenced from:
      facebook::yoga::indent(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&, unsigned int) in libYoga.a(YGNodePrint.o)
      std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > std::__1::operator+<char, std::__1::char_traits<char>, std::__1::allocator<char> >(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&&, char const*) in libYoga.a(YGNodePrint.o)
  "___cxa_end_catch", referenced from:
      std::__1::vector<YGNode*, std::__1::allocator<YGNode*> >::shrink_to_fit() in libYoga.a(YGNode.o)
  "std::exception::~exception()", referenced from:
      std::__1::bad_function_call::~bad_function_call() in libYoga.a(Yoga.o)
  "std::__1::__vector_base_common<true>::__throw_out_of_range() const", referenced from:
      std::__1::vector<YGNode*, std::__1::allocator<YGNode*> >::at(unsigned long) const in libYoga.a(Yoga.o)
  "std::__1::__vector_base_common<true>::__throw_length_error() const", referenced from:
      std::__1::vector<YGNode*, std::__1::allocator<YGNode*> >::__vallocate(unsigned long) in libYoga.a(Yoga.o)
      std::__1::vector<YGNode*, std::__1::allocator<YGNode*> >::__recommend(unsigned long) const in libYoga.a(Yoga.o)
      std::__1::vector<YGNode*, std::__1::allocator<YGNode*> >::__recommend(unsigned long) const in libYoga.a(YGNode.o)
      std::__1::vector<char, std::__1::allocator<char> >::__vallocate(unsigned long) in libYoga.a(YGNodePrint.o)
  "std::exception::what() const", referenced from:
      vtable for std::__1::bad_function_call in libYoga.a(Yoga.o)
  "vtable for __cxxabiv1::__si_class_type_info", referenced from:
      typeinfo for std::__1::bad_function_call in libYoga.a(Yoga.o)
  NOTE: a missing vtable usually means the first non-inline virtual member function has no definition.
  "operator new(unsigned long)", referenced from:
      _YGNodeNewWithConfig in libYoga.a(Yoga.o)
      _YGConfigNew in libYoga.a(Yoga.o)
      _YGNodeClone in libYoga.a(Yoga.o)
      std::__1::__libcpp_allocate(unsigned long, unsigned long) in libYoga.a(Yoga.o)
      YGConfigClone(YGConfig const&) in libYoga.a(Yoga.o)
      std::__1::__libcpp_allocate(unsigned long, unsigned long) in libYoga.a(YGNode.o)
      std::__1::__libcpp_allocate(unsigned long, unsigned long) in libYoga.a(YGNodePrint.o)
      ...
  "typeinfo for std::exception", referenced from:
      typeinfo for std::__1::bad_function_call in libYoga.a(Yoga.o)
  "vtable for std::exception", referenced from:
      std::exception::exception() in libYoga.a(Yoga.o)
  NOTE: a missing vtable usually means the first non-inline virtual member function has no definition.
  "___cxa_allocate_exception", referenced from:
      std::__1::__throw_length_error(char const*) in libYoga.a(Yoga.o)
      std::__1::__throw_bad_function_call() in libYoga.a(Yoga.o)
      std::__1::__throw_length_error(char const*) in libYoga.a(YGNode.o)
      std::__1::__throw_length_error(char const*) in libYoga.a(YGNodePrint.o)
  "std::length_error::~length_error()", referenced from:
      std::__1::__throw_length_error(char const*) in libYoga.a(Yoga.o)
      std::__1::__throw_length_error(char const*) in libYoga.a(YGNode.o)
      std::__1::__throw_length_error(char const*) in libYoga.a(YGNodePrint.o)
  "typeinfo for std::length_error", referenced from:
      std::__1::__throw_length_error(char const*) in libYoga.a(Yoga.o)
      std::__1::__throw_length_error(char const*) in libYoga.a(YGNode.o)
      std::__1::__throw_length_error(char const*) in libYoga.a(YGNodePrint.o)
  "___cxa_throw", referenced from:
      std::__1::__throw_length_error(char const*) in libYoga.a(Yoga.o)
      std::__1::__throw_bad_function_call() in libYoga.a(Yoga.o)
      std::__1::__throw_length_error(char const*) in libYoga.a(YGNode.o)
      std::__1::__throw_length_error(char const*) in libYoga.a(YGNodePrint.o)
  "std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::~basic_string()", referenced from:
      YGNodePrintInternal(YGNode*, YGPrintOptions) in libYoga.a(Yoga.o)
      facebook::yoga::YGNodeToString(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&, YGNode*, YGPrintOptions, unsigned int) in libYoga.a(YGNodePrint.o)
      facebook::yoga::appendFormatedString(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&, char const*, ...) in libYoga.a(YGNodePrint.o)
      facebook::yoga::appendNumberIfNotAuto(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, YGValue) in libYoga.a(YGNodePrint.o)
      facebook::yoga::appendEdges(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, facebook::yoga::detail::Values<9ul> const&) in libYoga.a(YGNodePrint.o)
      facebook::yoga::appendEdgeIfNotUndefined(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, facebook::yoga::detail::Values<9ul> const&, YGEdge) in libYoga.a(YGNodePrint.o)
      facebook::yoga::appendNumberIfNotUndefined(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, YGValue) in libYoga.a(YGNodePrint.o)
      ...
  "___cxa_free_exception", referenced from:
      std::__1::__throw_length_error(char const*) in libYoga.a(Yoga.o)
      std::__1::__throw_length_error(char const*) in libYoga.a(YGNode.o)
      std::__1::__throw_length_error(char const*) in libYoga.a(YGNodePrint.o)
  "std::terminate()", referenced from:
      ___clang_call_terminate in libYoga.a(Yoga.o)
  "std::logic_error::logic_error(char const*)", referenced from:
      std::length_error::length_error(char const*) in libYoga.a(Yoga.o)
      std::length_error::length_error(char const*) in libYoga.a(YGNode.o)
      std::length_error::length_error(char const*) in libYoga.a(YGNodePrint.o)
  "___cxa_begin_catch", referenced from:
      ___clang_call_terminate in libYoga.a(Yoga.o)
      std::__1::vector<YGNode*, std::__1::allocator<YGNode*> >::shrink_to_fit() in libYoga.a(YGNode.o)
  "operator delete(void*)", referenced from:
      _YGNodeNewWithConfig in libYoga.a(Yoga.o)
      _YGConfigNew in libYoga.a(Yoga.o)
      _YGNodeClone in libYoga.a(Yoga.o)
      _YGNodeFree in libYoga.a(Yoga.o)
      _YGConfigFree in libYoga.a(Yoga.o)
      YGConfigFreeRecursive(YGNode*) in libYoga.a(Yoga.o)
      std::__1::__libcpp_deallocate(void*, unsigned long) in libYoga.a(Yoga.o)
      ...
  "___cxa_guard_release", referenced from:
      _YGConfigGetDefault in libYoga.a(Yoga.o)
  "___cxa_guard_abort", referenced from:
      _YGConfigGetDefault in libYoga.a(Yoga.o)
  "std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::__init(char const*, unsigned long, unsigned long)", referenced from:
      std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > std::__1::operator+<char, std::__1::char_traits<char>, std::__1::allocator<char> >(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, char const*) in libYoga.a(YGNodePrint.o)
  "vtable for std::length_error", referenced from:
      std::length_error::length_error(char const*) in libYoga.a(Yoga.o)
      std::length_error::length_error(char const*) in libYoga.a(YGNode.o)
      std::length_error::length_error(char const*) in libYoga.a(YGNodePrint.o)
  NOTE: a missing vtable usually means the first non-inline virtual member function has no definition.
  "___cxa_guard_acquire", referenced from:
      _YGConfigGetDefault in libYoga.a(Yoga.o)
  "___gxx_personality_v0", referenced from:
      facebook::yoga::detail::Values<9ul>::operator[](unsigned long) const in libYoga.a(Yoga.o)
      _YGNodeNewWithConfig in libYoga.a(Yoga.o)
      _YGConfigGetDefault in libYoga.a(Yoga.o)
      _YGConfigNew in libYoga.a(Yoga.o)
      _YGNodeClone in libYoga.a(Yoga.o)
      _YGNodeRemoveAllChildren in libYoga.a(Yoga.o)
      _YGNodeSetChildren in libYoga.a(Yoga.o)
      ...
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by hejunbinlan** [comment]
platform :ios, '8.0'

target 'YogaDemo' do
    pod 'YogaKit', '~> 1.14.0'
end

**Comment by adgarcia** [comment]
is this a react-native project? Because I ran into a similar issue recently

**Comment by githubzb** [comment]
me too

**Comment by tranty9597** [comment]
any update on it, I've intergrated my rn project into native app.

**Comment by openUmbrella** [comment]
me too

**Comment by rainris** [comment]
Is it the same to add `use_frameworks!` to `Podfile`?

```
platform :ios, '10.0'

use_frameworks!

target 'ProfileEditSample' do
  pod 'YogaKit'
end
```

**Comment by Karniej** [comment]
Hey guys, have you resolved this issue ? I encountered it just now for the first time.

**Comment by NickGerleman** [comment]
It looks like this issue is stale, so I am going to close it.

If the issue still happens on a standalone version of Yoga, please feel free to create a new issue on this repo.

If you see Yoga compilation failures on a recent react-native template, please create an issue on the `react-native` repo.
