### ISSUE TITLE
 aa71dbb / crashes app, former versions work

### ISSUE THREAD

**Issue by Robert-M-Muench** [facebook/yoga#897]
The  revision aa71dbb crashes our app in a way that even MSVC 2019 IDE crashes when debugging things.

The crash happens on a very simple call:

````
YGNodeStyleSetPadding(node, YGEdgeLeft  , 1.0);
````
I'm compiling the static link lib using MSVC 2019. I have an older version (but don't know the revision) compiled with MSVC 2019 which works.

Did anything subtle change in the last 6 weeks? Maybe some alignment etc. stuff?

**Comment by Robert-M-Muench** [comment]
Trying our code with 1.14 and it crashes too with this version... in this line:

````
 YGNodeCalculateLayout(root, width, height, YGDirectionLTR);
````

I really don't have a clue why that can happen. Did anything change there?

**Comment by Robert-M-Muench** [comment]
Ok, the crash is a problem in the yoga code (signed / unsigned missmatch). I think there is a PR that fixes the problem, which isn't yet merged.

Here are the changes I applied and get things working again:

````
diff --git a/yoga/YGEnums.h b/yoga/YGEnums.h
index f06b0e04..18960168 100644
--- a/yoga/YGEnums.h
+++ b/yoga/YGEnums.h
@@ -14,7 +14,7 @@ namespace yoga {
 namespace enums {

 template <typename T>
-constexpr int count(); // can't use `= delete` due to a defect in clang < 3.9
+constexpr unsigned count(); // can't use `= delete` due to a defect in clang < 3.9

 namespace detail {
 template <int... xs>
@@ -40,7 +40,7 @@ constexpr int n() {
   namespace yoga {                   \
   namespace enums {                  \
   template <>                        \
-  constexpr int count<NAME>() {      \
+  constexpr unsigned count<NAME>() {      \
     return detail::n<__VA_ARGS__>(); \
   }                                  \
   }                                  \
diff --git a/yoga/YGMacros.h b/yoga/YGMacros.h
index 9c2989ac..82361484 100644
--- a/yoga/YGMacros.h
+++ b/yoga/YGMacros.h
@@ -27,6 +27,6 @@
 #define YG_ENUM_BEGIN(name) NS_ENUM(int, name)
 #define YG_ENUM_END(name)
 #else
-#define YG_ENUM_BEGIN(name) enum name
+#define YG_ENUM_BEGIN(name) enum name: unsigned
 #define YG_ENUM_END(name) name
 #endif
diff --git a/yoga/YGNode.cpp b/yoga/YGNode.cpp
index 2fb4510c..690afc00 100644
--- a/yoga/YGNode.cpp
+++ b/yoga/YGNode.cpp
@@ -353,7 +353,7 @@ YGValue YGNode::resolveFlexBasisPtr() const {

 void YGNode::resolveDimension() {
   using namespace yoga;
-  for (int dim = YGDimensionWidth; dim < enums::count<YGDimension>(); dim++) {
+  for (unsigned dim = YGDimensionWidth; dim < enums::count<YGDimension>(); dim++) {
     if (!getStyle().maxDimensions[dim].isUndefined() &&
         YGValueEqual(
             getStyle().maxDimensions[dim], style_.minDimensions[dim])) {
````

**Comment by tobster-de** [comment]
Thank you. I was adapting the rather old VS solution an making the NUnit tests running again and got to the issue. The also fixes my tests.

**Comment by NickGerleman** [comment]
Thanks for filing this issue. It has been a while since this was originally filed, but I know of projects like `react-native-windows` which compile the current version of Yoga with MSVC, and don't seem to run into any hard crashes of the program or IDE. It looks like the underlying code for iterating through dimensions has also changed significantly.

Going to close this, but please feel free to reopen if it happens on a more current version.
