### ISSUE TITLE
JS Package has wrong license on NPM

### ISSUE THREAD

**Issue by theiliad** [facebook/yoga#904]
In the [package.json](https://github.com/facebook/yoga/blob/master/javascript/package.json
) file I can see that you've updated the license to `MIT`, however on NPM it still shows up as `BSD-3-Clause`

https://www.npmjs.com/package/yoga-layout

Could you please update that?

**Comment by theiliad** [comment]
Any updates on this?

**Comment by NickGerleman** [comment]
https://github.com/facebook/yoga/commit/7f44ec512e7d150b7312336ed7908ac86441b4cc did another major overhaul of the JS package. https://github.com/facebook/yoga/issues/941 tracks publishing the new package to NPM, including the updated license.
