### ISSUE TITLE
Notification / Event before/after node layout changed?

### ISSUE THREAD

**Issue by Robert-M-Muench** [facebook/yoga#912]
There is some work for YG_ENABLE_EVENTS. And the event types are:
````
 enum Type {
    NodeAllocation,
    NodeDeallocation,
    NodeLayout,
    LayoutPassStart,
    LayoutPassEnd,
    MeasureCallbackStart,
    MeasureCallbackEnd,
  };
 ````
When does NodeLayout happen? Before, after the node layout was calculated? I think it makes a lot of sense to have two events (start/end) so that the old layout can still be accessed on start, and get a before/after view of a node.

Is this currently possible?

**Comment by NickGerleman** [comment]
Event happens at end of laying out given node. Having two markers could make sense here, but could also be derived as time from last NodeLayout or pass start.

Right now events are not exposed to Yoga public API. Intent for them is to be used for tracing.
