### ISSUE TITLE
YGNode.h in podspec

### ISSUE THREAD

**Issue by Adlai-Holler** [facebook/yoga#916]
- [x] I have searched [existing issues](https://github.com/facebook/yoga/issues) and this is not a duplicate

YGNode.h is considered private in the podspec. Is it indeed a private header? It would be great to have direct C++ access when possible, instead of having to route through the C layer for each call. Thanks, love your product!

**Comment by NickGerleman** [comment]
`YGNode` practically won't change much, but I do not think it is considered as part of the public API surface, so breaks to it are possible.
