### ISSUE TITLE
Use Yoga in a Gradle-based non-Android Java project

### ISSUE THREAD

**Issue by kirill-grouchnikov** [facebook/yoga#929]
Adding `implementation 'com.facebook.yoga:yoga:1.9.0'` in a standalone, non-Android Java project built with Gradle adds these two AAR files:

<img width="382" alt="image" src="https://user-images.githubusercontent.com/52874/65161170-18f65800-da05-11e9-93ed-142d46892cfd.png">

But AARs are the Android thing, so it can't resolve `import com.facebook.yoga.*` so that I can use `YogaNode`.

Is there a way to declare a dependency on Yoga Java bindings outside of the Android-targeting environment?

**Comment by kirill-grouchnikov** [comment]
Following the instructions at https://medium.com/@morsetree/helloworld-with-yoga-a-flexbox-based-cross-platform-layout-engine-947f0d7edda1 and changing a few lines (`YogaNode root = YogaNodeFactory.create()` and `root.calculateLayout(YogaConstants.UNDEFINED, YogaConstants.UNDEFINED)`) creates a runnable jar that has the following in it:

<img width="874" alt="image" src="https://user-images.githubusercontent.com/52874/65161491-a9349d00-da05-11e9-89c8-52db78f11196.png">

Is it possible to create such a standalone jar without the full local copy of Yoga?

**Comment by Sm0keySa1m0n** [comment]
I've been looking to use Yoga in a non-Android Java project too, a solution to this would be incredibly useful.

**Comment by Charanor** [comment]
I'd like to know this too!

**Comment by NickGerleman** [comment]
Closing in favor of using https://github.com/facebook/yoga/issues/1242 to track
