### ISSUE TITLE
Should be call app applyLayout in LayoutSubviews  on iOS?

### ISSUE THREAD

**Issue by peanut196** [facebook/yoga#943]
UIViewController:

RootView *rootView = [[RootView alloc] init];
    [rootView setBackgroundColor:[UIColor cyanColor]];
    [self.view addSubview:rootView];
    
    [rootView configureLayoutWithBlock:^(YGLayout * _Nonnull layout) {
        layout.isEnabled = YES;
        layout.position = YGPositionTypeAbsolute;
        layout.width = YGPercentValue(60);
        layout.height = YGPercentValue(60);
        layout.flexDirection = YGFlexDirectionColumn;
        layout.justifyContent = YGJustifySpaceAround;
        layout.alignItems = YGAlignCenter;
    }];

RootView: 

- (instancetype)init {
    if (self = [super init]) {
        
        UIView *subview1 = [[UIView alloc] init];
        [subview1 setBackgroundColor:[UIColor redColor]];
        [subview1 configureLayoutWithBlock:^(YGLayout * _Nonnull layout) {
            layout.isEnabled = YES;
            layout.width = YGPercentValue(100);
            layout.height = YGPercentValue(40);
        }];
        
        
        UIView *subview2 = [[UIView alloc] init];
        [subview2 setBackgroundColor:[UIColor yellowColor]];
        [subview2 configureLayoutWithBlock:^(YGLayout * _Nonnull layout) {
            layout.isEnabled = YES;
            layout.width = YGPercentValue(100);
            layout.height = YGPercentValue(40);
        }];
        [self addSubview:subview1];
        [self addSubview:subview2];
    }
    return self;
}

- (void)layoutSubviews {
    [super layoutSubviews];
    [self.yoga applyLayoutPreservingOrigin:NO];
    [super layoutSubviews];
}

layoutSubviews method will call more than once, but root view is not correct!

**Comment by cntrump** [comment]
You should enable self.view's yoga in `ViewController`, I tested with swift and it works well:

```swift
class RootView: UIView {
    override init(frame: CGRect) {
        super.init(frame: frame)

        let subview1 = UIView()
        subview1.backgroundColor = .red
        subview1.configureLayout { (layout) in
            layout.isEnabled = true
            layout.width = 100%
            layout.height = 40%
        }

        let subview2 = UIView()
        subview2.backgroundColor = .yellow
        subview2.configureLayout { (layout) in
            layout.isEnabled = true
            layout.width = 100%
            layout.height = 40%
        }

        addSubview(subview1)
        addSubview(subview2)
    }

    required init?(coder: NSCoder) {
        fatalError("init(coder:) has not been implemented")
    }
}

final class BasicViewController: UIViewController {
    override func viewDidLoad() {
        super.viewDidLoad()

        view.configureLayout { (layout) in
            layout.isEnabled = true
        }

        let rootView = RootView()
        rootView.backgroundColor = .cyan
        view.addSubview(rootView)

        rootView.configureLayout { (layout) in
            layout.isEnabled = true
            layout.position = .absolute
            layout.width = 60%
            layout.height = 60%
            layout.flexDirection = .column
            layout.justifyContent = .spaceAround
            layout.alignItems = .center
        }
    }
}
```

If you want yoga auto apply layout, try my PR: https://github.com/facebook/yoga/pull/1026
