### ISSUE TITLE
aspectRatio not work as expected in yoga 1.14.0

### ISSUE THREAD

**Issue by zhenglibao** [facebook/yoga#944]
# Report

- [x] I have searched [existing issues](https://github.com/facebook/yoga/issues) and this is not a duplicate

# Issues and Steps to Reproduce
1. On iOS 12, yoga 1.14.0, init UIImageView with properties
aspectRatio: 1
width: 100

2. With SDWebImage to set remote image (size: 150 x 300)
3. The final size of the UIImageView is 100 x 300

# Expected Behavior
I hope the UIImageView size is 100 x 100

# Actual Behavior
The UIImageView size is 100 x 300

Before I use yoga 1.6.0, it works well

**Comment by NickGerleman** [comment]
We are deprecating YogaKit as part of the Yoga 2.0 release. We are still going to release a new revision based on the current state of the repo, but won't be accepting new contributions, since we are going to be removing it from the repo after.
