### ISSUE TITLE
Legal issue, Scheme language port of the original v1.0.0 release

### ISSUE THREAD

**Issue by amirouche** [facebook/yoga#945]
# Report

- [x] I have searched [existing issues](https://github.com/facebook/yoga/issues) and this is not a duplicate

# Issues and Steps to Reproduce

Port the [v1.0.0 release](https://github.com/facebook/yoga/releases/tag/v1.0.0) to another language.

# Expected Behaviour

The license is MIT.

# Actual Behaviour

The license is BSD with https://github.com/facebook/yoga/blob/486b9a84bf594f96184c69d3ed0f6efcaa4344ed/PATENTS

# Link to Code

See the above links.

**Comment by amirouche** [comment]
Can I consider the code v1.0.0 to be MIT license or I must base my work on https://github.com/facebook/yoga/blob/master/yoga/Yoga.cpp

Thanks in advance!

**Comment by SidharthGuglani** [comment]
Hi
Please use the latest released version [1.16.0](https://github.com/facebook/yoga/releases/tag/1.16.0)
Thanks
