### ISSUE TITLE
Strange project. Example not working

### ISSUE THREAD

**Issue by zim32** [facebook/yoga#947]
Simple example from Standalone page (https://yogalayout.com/getting-started/standalone/) not working.

It gives me thise results

**Root**:
bottom: 0, height: 300, left: 0, right: 0, top: 0, width: 500

**Child1**:
bottom: 0, height: 100, left: 0, right: 0, top: 50, width: 100

**Child2**:
bottom: 0, height: 100, left: 0, right: 0, top: 150, width: 100

Items are always stacked vertically. 
Latest version from npm

**Comment by NickGerleman** [comment]
> Items are always stacked vertically

The website currently sets `UseWebDefaults` as part of `YGConfig`. This is confusingly not set by default as part of Yoga standalone, leading to a default `flexDirection` of `column`.
