### ISSUE TITLE
Justify Items and Justify Self

### ISSUE THREAD

**Issue by jacobp100** [facebook/yoga#955]
# Report

- [x] I have searched [existing issues](https://github.com/facebook/yoga/issues) and this is not a duplicate

# Issues and Steps to Reproduce

This project does not support the justify items and justify self properties [MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/justify-items). All browsers since IE11 support this

I think the logic is pretty much the same as align items, so it might be possible to repurpose that code

# Expected Behavior

Not relevant

# Actual Behavior

Not relevant

# Link to Code

Not relevant

**Comment by Sm0keySa1m0n** [comment]
Any status on this?

**Comment by XuDeveloper** [comment]
Any status on this?

**Comment by jacobp100** [comment]
It supports justify-items now, and I was wrong on justify-self - that only applies to grid items, not flex items (which is the only thing Yoga supports)
