### ISSUE TITLE
`position:sticky` support

### ISSUE THREAD

**Issue by KingAmo** [facebook/yoga#957]
# Report
hi, is it possible to support `position:sticky` ?
similar issue https://github.com/facebook/yoga/issues/264
- [x] I have searched [existing issues](https://github.com/facebook/yoga/issues) and this is not a duplicate

# Issues and Steps to Reproduce
***Replaces this with steps to repro your issue.***

# Expected Behavior
***Describe what you expected would happen.***

# Actual Behavior
***Describe what actually happened.***

# Link to Code
***If you have some code that maintainers can clone/test for themselves, bugs can be resolved much faster. Please paste a link here.***

***When applicable, use this [fiddle](https://jsfiddle.net/emilsjolander/jckmwztt/) to post a web repro.***

**Comment by nandorojo** [comment]
@NickGerleman sorry for the random tag on a 5-year-old issue, but do you think this is the kind of feature that would get added to Yoga? (Tagging you since I saw you add `Feature Request` as a label).

I would definitely be open to sponsoring this feature or helping get reviewers.

Thank you!

**Comment by NickGerleman** [comment]
Scrolling containers do not involve relayout, so this would need to be implemented in higher level UI framework. E.g. inside RN, for support there.

E.g. RN sticky headers will sync apply transform during scroll to keep in perceived static position. But box in layout space is as if it is in original position.
