### ISSUE TITLE
YGNodeSetMeasureFunc not called

### ISSUE THREAD

**Issue by Robert-M-Muench** [facebook/yoga#959]
This is about the C-API.

I set a measure function with YGNodeSetMeasureFunc() and can assess that the node has a measure function later when the node is drawn, which is called after a layout was calculated. And the node is drawn.

However, during layout, the measure function is not called.

Are there are cases when this could be the case? I use YGNodeMarkDirty() in thought, that this will trigger a new measure round.

Code is hard to strip down at the moment...

**Comment by Robert-M-Muench** [comment]
Note: I use
```
setWidthPercent(100);
setHeightPercent(100);
```
on every node, so the node where I set the measure function has this set too. Could this be the problem? But IMO it shouldn't.

**Comment by Robert-M-Muench** [comment]
Bingo!! That's the cause. But I don't understand why this is the case? Is it because if ...Percent() is set, only the width of the parent is used?

**Comment by SidharthGuglani** [comment]
We do not call measure callback when algorithm can exactly determine the width and height of node. Here is the [code reference](https://github.com/facebook/yoga/blob/master/yoga/Yoga.cpp#L1698) where we check for this.
