### ISSUE TITLE
No method for setBaselineFunc on iOS

### ISSUE THREAD

**Issue by starFelix** [facebook/yoga#961]
# Report

- [x] I have searched [existing issues](https://github.com/facebook/yoga/issues) and this is not a duplicate

# Issues and Steps to Reproduce

On iOS, we use flexlayout by `YGLayout` . If  I want to align items by `baseline`, I found it didn't work. After searching the code of `Yoga`, I found that I should provide `baselineFunc`.
But there isn't any method for me to set `baselinefunc`, I can't get the node of view either.

# Expected Behavior

Providing a method to set `baselineFunc`.

# Link to Code
https://github.com/facebook/yoga/blob/master/YogaKit/Source/YGLayout.h

**Comment by NickGerleman** [comment]
We are deprecating YogaKit as part of the Yoga 2.0 release. We are still going to release a new revision based on the current state of the repo, but won't be accepting new contributions, since we are going to be removing it from the repo after.
