### ISSUE TITLE
building yoga core static libraries for ios

### ISSUE THREAD

**Issue by olilarkin** [facebook/yoga#962]
Hello,

sorry to post a question here on the issues page. I would like to build static libs of yoga core, for use in C++. On macOS i can do that with ```buck build --show-output //:yoga```

But it's not clear to me how to build static libs for arm and ios simulator platforms.

thanks

**Comment by NickGerleman** [comment]
This should be possible with the Yoga pod and `use_frameworks`. Note the current Yoga pod needs an update published to build again, which should be happening later this month.
