### ISSUE TITLE
"Child already has a owner, it must be removed first. "  How to remove owner?

### ISSUE THREAD

**Issue by cgx2012** [facebook/yoga#964]
# Report

- [ ] I have searched [Child already has a owner, it must be removed first](https://github.com/facebook/yoga/issues) and this is not a duplicate

# Issues and Steps to Reproduce
1 . create view1 and subview1
2. hold subview1 with viewcontroller
3. add subview1 to view1 and config layout
4. delay some time
5. create view2 
6. add subview1 to view2 and config layout

# Expected Behavior
show me Child already has a owner, it must be removed first

Can i remove subview1's owner

**Comment by SidharthGuglani** [comment]
You can use [`removeChildAt` ](https://github.com/facebook/yoga/blob/2d52b5a8733bccba663b15817685b13d8b5eb9da/java/com/facebook/yoga/YogaNode.java#L25)
and then [`addChildAt`](https://github.com/facebook/yoga/blob/2d52b5a8733bccba663b15817685b13d8b5eb9da/java/com/facebook/yoga/YogaNode.java#L19) APIs on YogaNode object if you are using Java APIs

Calling `removeChildAt` on view1 will remove the owner of subview1 and then it can be added to any other view.

**Comment by SidharthGuglani** [comment]
Closing this.

**Comment by trungnguyenthien** [comment]
I get the same issue on Swift version.
For now, Yoga (wrapped by swift) don't provide any way to remove owner (no way to `removeChildAt` or `addChildAt`) 

Thank you very much.

**Comment by 100mango** [comment]
Same issue.

**Comment by vfritzon** [comment]
Not sure the api is exactly the same, but in the standalone js version you can remove the child from the parent with `getParent` and then `removeChild` (given that you have a reference to the child node). See https://github.com/facebook/yoga/blob/64e245942786227b2f97ccfa5c30ce5c4fd62d79/javascript/sources/entry-common.js#L123

**Comment by KelaKing** [comment]
Swift +1
so how to remove owner?

**Comment by AFBiyik** [comment]
In swift, I think this error happens if you remove a view from superview and add the view to another. To remove the owner use this:
```swift
        let superview = theView.superview
        theView.removeFromSuperview()
        superview?.yoga.applyLayout(preservingOrigin: false)
```
