### ISSUE TITLE
Support Display: inline-block

### ISSUE THREAD

**Issue by invious** [facebook/yoga#968]
# Report

- [x] I have searched [existing issues](https://github.com/facebook/yoga/issues) and this is not a duplicate

# Expected Behavior
***Describe what you expected would happen.***
![image](https://user-images.githubusercontent.com/1996089/74041029-e092ee80-4992-11ea-8ddb-2f140c5ddeeb.png)

# Actual Behavior
***Describe what actually happened.***
![image](https://user-images.githubusercontent.com/1996089/74041035-e557a280-4992-11ea-9b50-206a610103c0.png)

I was wondering if the inline-block images in the first picture are possible? if so, how?

**Comment by AaronFriel** [comment]
This issue, downstream of Yoga, seems to be related:
- https://github.com/vercel/satori/issues/484

The Vercel library Satori uses Yoga as the layout engine for rendering React to SVG and PNG. An example of this behavior, from the issue above, rendered in the Vercel/OG (OpenGraph) Image playground:

https://og-playground.vercel.app/?share=7VRLaxsxEP4rg0pJCsYPyKFst74khQZaCCQ0F1-00uzuJFpJ1cOOa_zfO_IrbUrpqbfAHsbzffP8rNkI5TSKStSalgsLENPa4MfNptgAPVLXpwrOZtPp27PR3rkinfoXPk3RG7lmb2vw6egt9hUFVImcZUw5kwd7RKWhzl4nHGKB0CYMR-ghx0Tt-tKx05b6v8ONVI9dcNnqS2dcYPxN27anqhx1Sz-wgtnFL677wywX0-nB66XWZLsKFmI29U8LUdzb7cLOi1H3s_mNDLIL0vc8dOpdThC9tBHOVy48cui7qp4wbUf387ueIvAnOfPLOGnX-9gxfHEBByAf8wC69A-RmDBgGoFyNvK6MOUAUpOnqLgMoKE0hq8SeQ8ygu9lwBQkSAXJBf6K5dmShZUDN-FdzBgQGmrQai4Vuej3zIjKIWbu4yY4sidez6yAgTs5ZDwFKjcMTrsx3KKGJRrgTnME7DABV2IzOi0NcmZnNQ0sVR7GcFVqLZGFbDLLzn-RzlKMdByaSrKeVDbc9LdnnmSlD9vxgYayUgutzIrxCC4oApPVroME2aRAiksfx1C5IUOyDCnxQz3xLM6fat5f333eyQHnTXCPaP8tZF3o8yJnPdmZjL4K-ldB9-t6lvW0tP-gbj3h48WWGAnny6mJotqI3ZkS1Xt-7mJ_x0RV3r7Q2OROVK00EUcCB_dAd2tfjmBa7X5xnnIwPg0NalGlkHE7Ekk2zOjRGMeP32ix_Qk

I'm not qualified to say whether Satori is using Yoga correctly, I'm unsure. It might be good for Yoga leads (@NickGerleman, @) to connect with Satori leads (@shuding, @LuciNyan, @jackie1210) on how to handle this case. 

Reading through Satori's algorithm is a bit of a challenge, but it looks like each node in a tree of text (inline) elements is being positioned as if they were adjacent block elements rendered in a parent with `display: flex, flex-direction: row`. If Yoga is intended to be [oblivious to text (comment on #1296)](https://github.com/facebook/yoga/issues/1296#issuecomment-1628221680), then should Satori's algorithm act on a tree of text nodes as a single inline node and hint the size of the glyphs back to Yoga, to provide the bounding rect?

**Comment by NickGerleman** [comment]
Yeah, this is going to be an issue with Satori's handling of text. Text in Yoga is represented as a leaf node in the layout tree. The platform provides a callback to Yoga to let it ask for the dimensions of the laid out block of text.

RN directly translates spans into different text formatting that the system renders and measures. If you have content inside of that text that needs to be laid out with flex or block formatting (inline-flex or inline-block) that can be laid out in it's own Yoga tree, to be incorporated into the platforms text layout, to be fed to the outer Yoga tree. 

There's a world maybe where Yoga does some more of the coordination here, but not sure it's a right design.
