### ISSUE TITLE
Flexbox generator does not display well in my react application

### ISSUE THREAD

**Issue by kopax** [facebook/yoga#969]
# Report

I am testing https://yogalayout.com/playground and have created that template:

```js
import React, {Component} from 'react';
import {View} from 'react-native';

export default class MyLayout extends Component {
  render() {
    return (
      <View style={{
        flex: 1,
        width: 500,
        height: 500,
        justifyContent: 'space-between',
      backgroundColor: 'red',
      }}>
        <View style={{
          flex: 1,
          width: 100,
          height: 100,
          backgroundColor: 'blue',
        }} />
        <View style={{
          flex: 1,
          width: 100,
          height: 100,
          backgroundColor: 'green',
        }} />
        <View style={{
          flex: 1,
          width: 100,
          height: 100,
          backgroundColor: 'purple',
        }} />
      </View>
    );
  }
};
```

# Issues and Steps to Reproduce

I don't know it seems to be default

# Expected Behavior

I expect to have this result:

![image](https://user-images.githubusercontent.com/1866564/74091202-a9822180-4ae7-11ea-9861-b3183426a278.png)

# Actual Behavior

Instead, I have this:

![image](https://user-images.githubusercontent.com/1866564/74091205-ae46d580-4ae7-11ea-9452-6d30da78b9d7.png)

**Comment by kopax** [comment]
The answer is here:

https://stackoverflow.com/questions/60130603/flexbox-generator-does-not-display-well-in-my-react-application/60130640?noredirect=1#comment106357967_60130640

The code sample is missing `flexDirection: "row"` in the root container.

Should this be fixed? I expected the code generated to be valid.

**Comment by NickGerleman** [comment]
> Should this be fixed? I expected the code generated to be valid.

It seems like a bug that playground does not account for React Native style defaults.

**Comment by kopax-polyconseil** [comment]
Ok and weird, because it is labeled `react-native` mode :)

**Comment by NickGerleman** [comment]
The new Playground at https://www.yogalayout.dev/playground now works differently. It doesn't have a direct option to export to RN, but it can be more or less copy-paste transcribed now: https://www.yogalayout.dev/playground
