### ISSUE TITLE
GetPositionPercent?

### ISSUE THREAD

**Issue by Robert-M-Muench** [facebook/yoga#971]
If I'm using percent based positioning YGNodeStyleGetPosition is not giving any result. I assume it's because this function will only return pixel positions.

So, how can I get the percent position? Or do I have to calc it myself?

**Comment by SidharthGuglani** [comment]
After the layout calculation is done , you can obtain position values by using `YGNodeLayoutGetLeft`, `YGNodeLayoutGetRight`, `YGNodeLayoutGetTop`, `YGNodeLayoutGetBottom` apis.

**Comment by SidharthGuglani** [comment]
Closing this.
