### ISSUE TITLE
JustifyContent changes behaviour of minWidth

### ISSUE THREAD

**Issue by jacobp100** [facebook/yoga#973]
# Report

- [x] I have searched [existing issues](https://github.com/facebook/yoga/issues) and this is not a duplicate

# Issues and Steps to Reproduce

* Set up a view with `flexDirection: row` and a `minWidth` (can be px or percentage value)
* Add two or more children (styling is not too important here - they can have zero width)
* Set different values of `justifyContent` the parent view

# Expected Behavior

The width of the parent should not change when changing the value of `justifyContent`

# Actual Behavior

* Setting `justifyContent: space-around` grows the parent for 1+ children
* Setting `justifyContent: space-between` grows the parent for 2+ children

# Link to Code

https://codesandbox.io/s/yoga-layout-min-width-bug-bjhz4

**Comment by jacobp100** [comment]
Just a note if this helps at all, in our code we have a horizontal scrollview the full width of the device, and set a horizontal padding on the content container, and then a horizontal margin on each of the child nodes

Normally you'd set `minWidth: 100%`, but here, that's equivalent to `Dimensions.get('window').width`

The fudge factor below seems to work across all values of `preferredMargin` and `minimumMargin`. Not sure if this will be of any use for debugging

```js
const preferredMargin = 20 // 0-2 items
const minimumMargin = 10 // >3 items

const fudgeFactor = (preferredMargin - minimumMargin) / 2

const styles = StyleSheet.create({
  rowContentContainer: {
    minWidth: Dimensions.get('window').width - fudgeFactor,
    paddingHorizontal: preferredMargin - minimumMargin / 2
  },
  tileContainer: {
    marginHorizontal: minimumMargin / 2,
    width: (Dimensions.get('window').width - preferredMargin * 3) / 2
  }
})
```

**Comment by SidharthGuglani** [comment]
Can you help me reproducing this issue on [Yoga Playground](https://yogalayout.com/playground/) ? 

I am not able to follow what do you mean by 

> Setting justifyContent: space-around grows the parent for 1+ children
Setting justifyContent: space-between grows the parent for 2+ children

**Comment by jacobp100** [comment]
Sure! [Here you go](https://yogalayout.com/playground/?eyJ3aWR0aCI6IjUwMCIsImhlaWdodCI6IjEwMCIsIm1pbldpZHRoIjoiIiwibWluSGVpZ2h0IjpudWxsLCJtYXhXaWR0aCI6bnVsbCwibWF4SGVpZ2h0IjpudWxsLCJqdXN0aWZ5Q29udGVudCI6MywiYWxpZ25JdGVtcyI6MSwiYWxpZ25Db250ZW50IjowLCJwb3NpdGlvbiI6eyJ0b3AiOm51bGwsInJpZ2h0IjpudWxsLCJib3R0b20iOm51bGwsImxlZnQiOm51bGx9LCJjaGlsZHJlbiI6W3sid2lkdGgiOiIiLCJoZWlnaHQiOjEwMCwibWluV2lkdGgiOiIzMDAiLCJtaW5IZWlnaHQiOm51bGwsIm1heFdpZHRoIjpudWxsLCJtYXhIZWlnaHQiOm51bGwsImp1c3RpZnlDb250ZW50IjozLCJwb3NpdGlvbiI6eyJ0b3AiOm51bGwsInJpZ2h0IjpudWxsLCJib3R0b20iOm51bGwsImxlZnQiOm51bGx9LCJjaGlsZHJlbiI6W3sid2lkdGgiOjEwMCwiaGVpZ2h0IjoxMDAsIm1pbldpZHRoIjpudWxsLCJtaW5IZWlnaHQiOm51bGwsIm1heFdpZHRoIjpudWxsLCJtYXhIZWlnaHQiOm51bGwsInBvc2l0aW9uIjp7InRvcCI6bnVsbCwicmlnaHQiOm51bGwsImJvdHRvbSI6bnVsbCwibGVmdCI6bnVsbH19LHsid2lkdGgiOjEwMCwiaGVpZ2h0IjoxMDAsIm1pbldpZHRoIjpudWxsLCJtaW5IZWlnaHQiOm51bGwsIm1heFdpZHRoIjpudWxsLCJtYXhIZWlnaHQiOm51bGwsInBvc2l0aW9uIjp7InRvcCI6bnVsbCwicmlnaHQiOm51bGwsImJvdHRvbSI6bnVsbCwibGVmdCI6bnVsbH19XX1dfQ==)

To see the bug, select `root > 1`. It no width set, but does have min width set. Change `justifyContent` to `space around`, `space between`, and any other value. See that the size of the selected view changes

Here's a video demonstrating this

![ezgif-3-f743308845d9](https://user-images.githubusercontent.com/7275322/75567505-9066f380-5a49-11ea-8201-b41c03e2c41d.gif)

**Comment by NickGerleman** [comment]
I think we fixed this one: https://www.yogalayout.dev/blog/announcing-yoga-3.0#correct-main-axis-size-calculation-for-indefinite-containers-using-justify-content

**Comment by jacobp100** [comment]
Fantastic work on yarn 3 🎉
