### ISSUE TITLE
Will not install on Node v12 (current LTS)

### ISSUE THREAD

**Issue by nathan-muir** [facebook/yoga#979]
# Report

- [x] I have searched [existing issues](https://github.com/facebook/yoga/issues) and this is not a duplicate

# Issues and Steps to Reproduce

```sh
nvm install --lts
nvm use v12.16.1
npm install yoga-layout
# or cd yoga-layout/javascript && npm install
```

# Expected Behavior
Installation completes without error

# Actual Behavior

Installation / Compilation fails. 

``` 
12793 silly lifecycle yoga-layout@1.9.3~install: Args: [ '-c', 'npm run build:node' ]
12794 silly lifecycle yoga-layout@1.9.3~install: Returned: code: 1  signal: null
12795 info lifecycle yoga-layout@1.9.3~install: Failed to exec install script
12796 verbose stack Error: yoga-layout@1.9.3 install: `npm run build:node`

./.cache/node-gyp/12.16.1/include/node/v8.h:2704:39: note:   candidate expects 1 argument, 0 provided
nbind.target.mk:160: recipe for target 'Release/obj.target/nbind/sources/Config.o' failed
make: *** [Release/obj.target/nbind/sources/Config.o] Error 1
make: Leaving directory '.../yoga-layout/javascript/build'

```

Build is failing because the dependency `nbind` hasn't been updated to support node v12 [1].

 [1] https://github.com/charto/nbind/issues/133

**Comment by pirate** [comment]
`nbind`'s master branch is reported to work on Node v12, maybe try using that instead of their main npm release?

`yarn add https://github.com/charto/nbind`

**Comment by nathan-muir** [comment]
Yeah, there are some issues trying to use nbind from a git commit, and their master branch still has a typescript bug.

I'm just trying to get some feedback from this repos maintainers, whether they're going to continue supporting nodejs, and update to support node v12, or if I should migrate to an alternative.

**Comment by pirate** [comment]
Makes sense, we're personally switching away from nbind to N-API for our project.

**Comment by ivan133** [comment]
So any news here?

**Comment by samueldclarke** [comment]
Anyone got an update on this? As far as I can see this still doesn't install on Node 12?

**Comment by talentlessguy** [comment]
Doesn't install on Node 14.8.0 as well

```
  2861 |   V8_WARN_UNUSED_RESULT Maybe<double> NumberValue(Local<Context> context) const;
│       |                                       ^~~~~~~~~~~
│ /home/v1rtl/.cache/node-gyp/14.8.0/include/node/v8.h:2861:39: note:   candidate expects 1 argument, 0 provided
│ /home/v1rtl/.cache/node-gyp/14.8.0/include/node/v8.h: In instantiation of ‘void v8::PersistentBase<T>::SetWeak(P*, typename v8::WeakCallbackInfo<P>::Callback, v8::WeakCallbackType) [with P = node::ObjectWrap; T = v8::Object;
│ /home/v1rtl/.cache/node-gyp/14.8.0/include/node/node_object_wrap.h:85:78:   required from here
│ /home/v1rtl/.cache/node-gyp/14.8.0/include/node/v8.h:10867:16: warning: cast between incompatible function types from ‘v8::WeakCallbackInfo<node::ObjectWrap>::Callback’ {aka ‘void (*)(const v8::WeakCallbackInfo<node::ObjectW
│ 10867 |                reinterpret_cast<Callback>(callback), type);
│       |                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
│ /home/v1rtl/.cache/node-gyp/14.8.0/include/node/v8.h: In instantiation of ‘void v8::PersistentBase<T>::SetWeak(P*, typename v8::WeakCallbackInfo<P>::Callback, v8::WeakCallbackType) [with P = Nan::ObjectWrap; T = v8::Object; 
│ ../../../../node_modules/nan/nan_object_wrap.h:65:61:   required from here
│ /home/v1rtl/.cache/node-gyp/14.8.0/include/node/v8.h:10867:16: warning: cast between incompatible function types from ‘v8::WeakCallbackInfo<Nan::ObjectWrap>::Callback’ {aka ‘void (*)(const v8::WeakCallbackInfo<Nan::ObjectWra
│ make: *** [nbind.target.mk:154: Release/obj.target/nbind/sources/Config.o] Error 1
│ make: Leaving directory '/home/v1rtl/Coding/react-three-flex/node_modules/.pnpm/yoga-layout@1.9.3/node_modules/yoga-layout/build'
│ gyp ERR! build error 
│ gyp ERR! stack Error: `make` failed with exit code: 2
│ gyp ERR! stack     at ChildProcess.onExit (/home/v1rtl/.pnpm-store/pnpm-global/4/node_modules/.pnpm/pnpm@5.5.2/node_modules/pnpm/lib/node_modules/node-gyp/lib/build.js:194:23)
│ gyp ERR! stack     at ChildProcess.emit (events.js:314:20)
│ gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:276:12)
│ gyp ERR! System Linux 5.7.14-1-MANJARO
│ gyp ERR! command "/home/v1rtl/n/bin/node" "/home/v1rtl/.pnpm-store/pnpm-global/4/node_modules/.pnpm/pnpm@5.5.2/node_modules/pnpm/lib/node_modules/node-gyp/bin/node-gyp.js" "configure" "build"
│ gyp ERR! cwd /home/v1rtl/Coding/react-three-flex/node_modules/.pnpm/yoga-layout@1.9.3/node_modules/yoga-layout
│ gyp ERR! node -v v14.8.0
│ gyp ERR! node-gyp -v v7.1.0
│ gyp ERR! not ok 
│ npm ERR! code ELIFECYCLE
│ npm ERR! errno 1
│ npm ERR! yoga-layout@1.9.3 build:node: `npm run copy-sources && autogypi && node-gyp configure build`
│ npm ERR! Exit status 1
│ npm ERR! 
│ npm ERR! Failed at the yoga-layout@1.9.3 build:node script.
│ npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
│ npm ERR! A complete log of this run can be found in:
│ npm ERR!     /home/v1rtl/.npm/_logs/2020-08-19T12_11_26_636Z-debug.log
└─ Failed in 2s
```

**Comment by talentlessguy** [comment]
For everyone who comes to this thread

there's `yoga-layout-prebuilt`:

https://github.com/vadimdemedes/yoga-layout-prebuilt

**Comment by Skywalker13** [comment]
> there's `yoga-layout-prebuilt`:
> 
> https://github.com/vadimdemedes/yoga-layout-prebuilt

prebuilt has a major drawback.. it's limited with static memory of 64 MB and just unusable with large stuff

**Comment by oswaldoacauan** [comment]
Is there any plan for Yoga to support v12>?

**Comment by NickGerleman** [comment]
I've been taking a look at the bindings for Yoga. I don't think the JS or C# variants are in a great state at the moment.

I just merged https://github.com/facebook/yoga/commit/5a18ccdbe2f9363ddbe2d0bb78f3a7add2bc3ff8, which inadvertently fixed an issue where `position` has not worked correctly for C# or JS for the last two years, due to https://github.com/facebook/yoga/commit/fc88b2f774f0ab9090d7ca15de6680f26d7285ad shifting existing ordinals in the C ABI without updating the bindings for either language.

Yoga's C ABI is designed to be bindable, and there have been good examples where the community has leveraged this. E.g. [FlexLayout](https://github.com/layoutBox/FlexLayout) (the bindings, not the engine), added Swift support because there was enough demand. I suspect that the best outcome would be to deprecate/remove the current JS and C# bindings, and to give the community creating bindings the room to encourage better ones.

**Comment by NickGerleman** [comment]
As of 1813748eaa60e6129c1e1c00c08322b5687b1702 we no longer use nbind, and our tests are running against Node 18.

#941 tracks us publishing a new version to npm. Because we've made a lot of changes it may initially be a beta version.

**Comment by bvaughn** [comment]
I'm kind of confused. #941 is from 2019. Is that really even tracking anything at this point, or is it just a stale/forgotten issue?

**Comment by NickGerleman** [comment]
Yoga went through a long period where it was unmaintained. I do intend to release a new NPM package (we have had many recent changes). That issue is being used because it is where the existing conversation has happened.
