### ISSUE TITLE
Error calculating subview size in iOS

### ISSUE THREAD

**Issue by HaijunWei** [facebook/yoga#982]
Hello, On line 468 of the `YGLayout.m` file, no verification of `yoga.isEnabled`, This will incorrectly lay out the system controls and not get the correct width and height.
Call `applyLayout`  in `layoutSubviews`, UITableViewCell and UIScrollView will have a great chance to report an error. Because traversing the subviews gets a private view, such as ` _UITableViewHeaderFooterViewLabel`
```
  const CGPoint bottomRight = {
      topLeft.x + YGNodeLayoutGetWidth(node),  // will get NAN
      topLeft.y + YGNodeLayoutGetHeight(node), // will get NAN
  };
```

**Comment by pythons** [comment]
你使用的 view 不干净，比如拿了 viewController.view ，由于 subviews 有系统 view，导致的 nan 问题。解决方案要么前置规避，要么加上 if yoga.isEnabled then return;

**Comment by cntrump** [comment]
原因是视图里混有不使用 yoga 布局的视图，只能自己改代码。试一下我修改的 PR 能解决你的问题不：https://github.com/facebook/yoga/pull/1026

**Comment by HaijunWei** [comment]
我使用遇到Label经常有宽高计算不准确的情况，已放弃使用了，你们没遇到吗？

**Comment by cntrump** [comment]
> 我使用遇到Label经常有宽高计算不准确的情况，已放弃使用了，你们没遇到吗？

UILabel 计算没有问题的，你指的是第三方的富文本 Label ？
能有 demo 或者代码片段的话，可以分析一下。

**Comment by cntrump** [comment]
```objc
  view.frame = (CGRect){
      .origin =
          {
              .x = YGRoundPixelValue(topLeft.x + origin.x),
              .y = YGRoundPixelValue(topLeft.y + origin.y),
          },
      .size =
          {
              .width = YGRoundPixelValue(bottomRight.x) -
                  YGRoundPixelValue(topLeft.x),
              .height = YGRoundPixelValue(bottomRight.y) -
                  YGRoundPixelValue(topLeft.y),
          },
  };
```

你的问题可能是上面这段代码造成的，计算宽高的时候，应该是先相减再对结果进行对齐，官方的是先对齐再相减，会造成 UILabel 的宽高可能会小一点。我的 PR 里对这种情况做了处理。

**Comment by HaijunWei** [comment]
对的，刚使用的时候没仔细测试，都写了很多页面出来后，偶然发现UILabel存在宽高不正确，导致显示不全的问题。后面返工了...
