### ISSUE TITLE
Is the latest version aar not uploaded to Maven warehouse

### ISSUE THREAD

**Issue by chenjianping99** [facebook/yoga#992]
# Report

- [ ] I have searched [existing issues](https://github.com/facebook/yoga/issues) and this is not a duplicate

# Issues and Steps to Reproduce

https://mvnrepository.com/artifact/com.facebook.yoga/yoga?repo=jcenter

jcenter the latest version is 1.16.0
# Expected Behavior
***Describe what you expected would happen.***

# Actual Behavior
***Describe what actually happened.***

# Link to Code
***If you have some code that maintainers can clone/test for themselves, bugs can be resolved much faster. Please paste a link here.***

***When applicable, use this [fiddle](https://jsfiddle.net/emilsjolander/jckmwztt/) to post a web repro.***

**Comment by NickGerleman** [comment]
Please see https://mvnrepository.com/artifact/com.facebook.yoga.android/yoga-layout/1.19.0 for the latest published version. A newer version should be published soon as well.
