### ISSUE TITLE
[Playground] Setting `Basis` doesn't work

### ISSUE THREAD

**Issue by Huxpro** [facebook/yoga#993]
# Report

- [x] I have searched [existing issues](https://github.com/facebook/yoga/issues) and this is not a duplicate

# Issues and Steps to Reproduce

Open the playground and change the `Basis` value of the first child node to `200`.

# Expected Behavior

The first node should be rendered with the generated inline style `width: 200`.

# Actual Behavior

The first node is still rendered with the generated inline style `width: 100`.

# Notes

It works as expected in React Native thus I suspected it is a bug of the playground.

**Comment by NickGerleman** [comment]
We are building a new playground as part of a website migration. I verified that `flexBasis` works correctly in the latest version. https://yoga-website-next-fbopensource.vercel.app/
