### ISSUE TITLE
buck android app failed

### ISSUE THREAD

**Issue by chenjianping99** [facebook/yoga#996]
# Report

- [ ] I have searched [existing issues](https://github.com/facebook/yoga/issues) and this is not a duplicate

# Issues and Steps to Reproduce
***Replaces this with steps to repro your issue.***

chenjianpingdeMacBook-Pro:android chenjianping$ pwd
/Users/chenjianping/Downloads/yoga-master/android
chenjianpingdeMacBook-Pro:android chenjianping$ buck install -r android/sample
WARNING: Output when parsing /Users/chenjianping/Downloads/yoga-master/android/sample/BUCK:
| Traceback (most recent call last):
|   File "/Users/chenjianping/Downloads/yoga-master/.buckd/tmp/buck_run.ltmaIl/buck_python_program8907044429899559464/__main__.py", line 10, in <module>
|     from buck_parser import buck
|   File "/Users/chenjianping/Downloads/yoga-master/.buckd/resources/2018.08.20.01/buck_server/buck_parser/buck.py", line 3, in <module>
| ModuleNotFoundError: No module named '__builtin__'
Buck wasn't able to parse /Users/chenjianping/Downloads/yoga-master/android/sample/BUCK:
No content to map due to end-of-input
 at [Source: com.google.common.io.CountingInputStream@65170769; line: 1, column: 0]
chenjianpingdeMacBook-Pro:android chenjianping$ 

# Expected Behavior
***Describe what you expected would happen.***

# Actual Behavior
***Describe what actually happened.***

# Link to Code
***If you have some code that maintainers can clone/test for themselves, bugs can be resolved much faster. Please paste a link here.***

***When applicable, use this [fiddle](https://jsfiddle.net/emilsjolander/jckmwztt/) to post a web repro.***

**Comment by NickGerleman** [comment]
https://github.com/facebook/yoga/pull/1166 removed Buck logic in general. It has not been exercised in OSS, and we should be indexing on the existing Gradle/CMake logic. There is a followup here though, to update the sample to use Gradle.
