### ISSUE TITLE
When YogaKit intergrated with CocoaPods in a Objective-C project, compilation failed

### ISSUE THREAD

**Issue by wujianbotju** [facebook/yoga#998]
In version 1.17 of YogaKit, Swift source files were treated as SwiftExtension.
In version 1.18, you guys fixed the bug related the Xcode 11 not able to find swift related frameworks. File YGLayoutExtensions.swift was added to target project by default, if the target project is a Objective-C project, compilation will fail because  Xcode 11 can't be able to find swift related frameworks!

**Comment by artehg** [comment]
+1

**Comment by ali-tit** [comment]
+1

**Comment by cntrump** [comment]
Add a dummy swift file to your project can fix it.

**Comment by NickGerleman** [comment]
We are deprecating YogaKit as part of the Yoga 2.0 release. We are still going to release a new revision based on the current state of the repo, but won't be accepting new contributions, since we are going to be removing it from the repo after.
