### ISSUE TITLE
What is the meaning of the different YGMeasureMode values?

### ISSUE THREAD

**Issue by Robert-M-Muench** [facebook/yoga#999]
I have a text-measure function, which reports the correct width in px but YG layout is incorrect. Half of the text hangs into the next node's area.

YGMeasureMode for the height is YGMeasureModeExactly

YGMeasureMode for the width is YGMeasureModeAtMost (why is it different, what does it mean?) Looks like if this value is given exactly, YG creates a layout that is to narrow...

What should I return in my measure function for a rendered text-size, so that the correct bounding-box width leads to a layout which is not to narrow?

**Comment by Robert-M-Muench** [comment]
Could it be that the text node gets a narrow layout and I have to set a minimum size which is the same as the text?

**Comment by Robert-M-Muench** [comment]
That's was the solution. The YGSize width returned from the measuring function isn't taking into account, if YG can create a more narrow layout. It's optimized away.

To force a defined width you have to use MinWidth/Height.

**Comment by woehrl01** [comment]
Hi @Robert-M-Muench,

I suggest having a look at the comment at the function `YGNodelayoutImpl`, it greatly describes the differences between the different measure modes.

> 
> //    The spec describes four different layout modes: "fill available", "max
> //    content", "min content", and "fit content". Of these, we don't use "min
> //    content" because we don't support default minimum main sizes (see above
> //    for details). Each of our measure modes maps to a layout mode from the
> //    spec (https://www.w3.org/TR/CSS3-sizing/#terms):
> //      - YGMeasureModeUndefined: max content
> //      - YGMeasureModeExactly: fill available
> //      - YGMeasureModeAtMost: fit content

And yes if the layout finds a smaller version it will use that, if you want to have text with a minimum size you have to use `min-width` / `min-height`.
